### ISSUE TITLE
Help make examples

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#1]
**Latest Update**:

Alrighty! We're getting really close now! Just need to tie up some loose ends and make sure we cover all the use cases we want to (ALL OF THEM).

We've released an official "release candidate"

You can install it with:

```
npm install --save downshift@rc
```

If you want to help, try implementing an autocomplete/combobox/multi-select/etc. with downshift. You can:

1. fork [the example codesandbox here](http://kcd.im/ds-example)
2. give it a good title and description
3. Update the version (go to dependencies, type `downshift` for the "package name" and `rc` for the "version"). Do this even though it already appears in the list of dependencies.
4. Add the `downshift:example` tag. That way it shows up in [this search](https://codesandbox.io/search?refinementList%5Btags%5D%5B0%5D=downshift%3Aexample&page=1)
5. Ping us here when you're done. Thanks!

---

**Old Update**:

Hey folks! :wave: now that we've released a beta version, it's _much_ easier to make examples. Now you can make them _right in the browser_ :tada: (thank you @CompuIves!!!)

So, if you've made an example already, would you mind forking this example: http://kcd.im/rac-example and updating it to your example? Then give it a good title and description and **add the `react-autocompletely:example` tag** That way it shows up in [this search](https://codesandbox.io/search?refinementList%5Btags%5D%5B0%5D=react-autocompletely%3Aexample&page=1)

I'll add a link to that in the README so folks can go see all the awesome examples you all make. Thanks!!!

---

**Old stuff**

Hey :wave:

We need help making examples. I've scaffolded out things for the examples already, but we need more and need to improve the ones that we already do have. Here's a quick rundown of how to get up and running with the examples:

```bash
git clone https://github.com/kentcdodds/react-autocompletely.git
cd react-autocompletely
npm install
cd examples
npm install
npm start
```

Then open http://localhost:3000/example-name

In the `examples` directory, you'll find a `pages` directory. Each of those has an `index.js` file which is rendered at that route. For example, [`semantic-ui/index.js`](https://github.com/kentcdodds/react-autocompletely/blob/master/examples/pages/semantic-ui/index.js) will be rendered at: http://localhost:3000/semantic-ui

So, the idea for these examples is they can be examples of just about anything. I have a few in there to show examples of how to implement the API or look and feel that other libraries have. That's mostly to demonstrate the power of the primitives available in react-autocomplete.

Feel free to comment here on what example you're working on. You can update an existing example or create a new one. Just let us know so we don't step on each others toes. Thanks!

Oh, and one other thing, right now this repo is private because I need to clear things with legal before we open source it as a PayPal library. So I have to give you commit access. Regardless of that, if you could, please still make forks and don't commit directly to the repo :) Thanks!

**Comment by kentcdodds** [comment]
Hey folks! :wave: now that we've released a beta version, it's _much_ easier to make examples. Now you can make them _right in the browser_ :tada: (thank you @CompuIves!!!)

So, if you've made an example already, would you mind forking this example: http://kcd.im/rac-example and updating it to your example? Then give it a good title and description and **add the `react-autocompletely:example` tag** That way it shows up in [this search](https://codesandbox.io/search?refinementList%5Btags%5D%5B0%5D=react-autocompletely%3Aexample&page=1)

I'll add a link to that in the README so folks can go see all the awesome examples you all make. Thanks!!!

**Comment by karanjthakkar** [comment]
If anyone has any ideas for examples but are hard pressed on time, I'd love to pick those up.

**Comment by kentcdodds** [comment]
Here are some ideas. Try reimplementing components from the following libraries:

- [semantic-ui](https://semantic-ui.com/modules/dropdown.html)
- [react-autocomplete](https://github.com/reactjs/react-autocomplete)
- [react-select](https://github.com/JedWatson/react-select) (I think someone may be working on this one)

I expect there are others... :)

**Comment by karanjthakkar** [comment]
I can work on this: https://reactcommunity.org/react-autocomplete/managed-menu-visibility/ if no one already is.

**Comment by kentcdodds** [comment]
Sounds great :+1:

**Comment by souporserious** [comment]
Going to try an example like this soon
![image](https://user-images.githubusercontent.com/2762082/28682614-6d908546-72b2-11e7-8d88-7932532b191f.png)

**Comment by jtmthf** [comment]
@kentcdodds For future examples, do you prefer for them to be in code sandbox only or do you also want them here? Downside to code sandbox is that some examples might get out of sync as the API changes if their original authors don't update them.

**Comment by kentcdodds** [comment]
@jtmthf, good point. Though we're in the same situation either way...

It might be better to have a specific curated list that we as maintainers can manage. I wonder if @CompuIves could eventually add the idea of "Collections" and we could link to a collection of examples 🤔 

For now, let's just do everything in codesandbox, and maybe we can add a list of links to the README and keep that up to date ourselves.

**Comment by CompuIves** [comment]
Wow collections sounds like a great feature and not too hard to make!
That's a very nice way for users to curate examples and content to show to
others, nice idea!

For now you can add the sandboxes to the git repo and use CodeSandbox
import from git. This way everyone can edit the git and the changes are
automatically reflected on the sandbox. Sadly it isn't possible yet to add
tags to git sandboxes, I'm working on this. You can already search on git
repo on the search as alternative.

**Comment by kentcdodds** [comment]
If someone wants to do that I'm fine, but I think that long-term collections would be better so I'm happy to manually maintain a list on the repo until collections exist :smile:

**Comment by souporserious** [comment]
Are you cool with leaving Next in there or some sort of way to test out examples in a dev environment? I found it helpful when changing API's and what not so I could test real quick.

**Comment by kentcdodds** [comment]
Who wants to make [this](https://twitter.com/kentcdodds/status/890067048717586433) with react-autocompletely? :smile:

![ezgif-4-04a9f6be9a](https://user-images.githubusercontent.com/1500684/28685665-5b95b388-72bd-11e7-99eb-cf776d280046.gif)

**Comment by kentcdodds** [comment]
> Are you cool with leaving Next in there or some sort of way to test out examples in a dev environment? I found it helpful when changing API's and what not so I could test real quick.

Yes, we can do it for that purpose :+1: Though maybe we should clean it up to only have a few. And we should update the README to indicate the new purpose of that project.

**Comment by souporserious** [comment]
sounds great 👌 also, I might take a stab at the Twitter example this weekend 😉

**Comment by kentcdodds** [comment]
Another fun one would be to make an implementation of [`genie`](https://github.com/kentcdodds/genie) with `react-autocompletely`. Right now the demo is using angular :wink:

**Comment by zsid** [comment]
`genie` looks fun. I will have a go over the weekend.  😄

**Comment by kentcdodds** [comment]
I've updated the `Examples` section. Please make a PR to that section when you've made your example.

**Comment by souporserious** [comment]
Some more inspo:
![image](https://user-images.githubusercontent.com/2762082/28742067-a4c5fb58-73da-11e7-8d13-d68183c1bbf2.png)
I'm going to try and do one like above this weekend.

**Comment by kentcdodds** [comment]
There's been some breaking changes released. I've updated [kcd.im/rac-example](http://kcd.im/rac-example) with the latest :smile: Thanks everyone!

**Comment by kentcdodds** [comment]
Definitely. The example I liked to uses glamorous. You could just switch it to styled-components 😀

**Comment by zsid** [comment]
I am really sorry,  I won't be able to complete the [genie](https://github.com/kentcdodds/genie) example this weekend as something has come up 😞  `Genie` looks great and if anyone wants to pick it up please feel free to do it.

**Comment by geoffdavis92** [comment]
@kentcdodds You want us to update the README? I have my SpectreCSS example ([here](https://codesandbox.io/s/M89KQOBRB))

**Comment by kentcdodds** [comment]
Hey @geoffdavis92! Thanks for this! It looks like you're not using the latest react-autocompletely@beta but instead using a specific file in your sandbox. Would you be interested in updating it to the latest beta and adding it to the dependencies? (You can fork [this](http://kcd.im/rac-example))

**Comment by geoffdavis92** [comment]
@kentcdodds Sure thing, just updated. But it gives me an invariant violation. It doesn't seem to like the `Autocomplete.Menu` item.

**Comment by kentcdodds** [comment]
That was removed. Sorry, things change day around here until 1.0.0 is released. See the docs (use the controller). Thanks for any API feedback/help you can give us!

**Comment by geoffdavis92** [comment]
@kentcdodds Got it working. Do you allow non-contributors to edit the README? Otherwise my example link is here: https://www.codesandbox.io/s/M89KQOBRB

**Comment by kentcdodds** [comment]
Thanks! Yes, please open a pull request to the README 😀

**Comment by kentcdodds** [comment]
There's been a significant update! I've updated the README [the base example](http://kcd.im/rac-example).

Please give it a spin! I'm really excited about the flexibility of the new API! Thank you @jaredly for the inspiration here :tada:

**Comment by Corjen** [comment]
@kentcdodds great progress, love the new API! 🎉  Couldn't find the time this weekend, but just finished with the first react-select example, see https://codesandbox.io/s/JEKJXDJK

Would love some feedback!

**Comment by zsid** [comment]
Hey @kentcdodds,

I have started working on the example ([here](https://codesandbox.io/s/4zNL2WW1) is my example) but my experience with codesandbox is not positive:
* It keeps breaking when I navigate between `styles.css` and the `index.js`
* Doesn't always recognise my classes that I pass to the input. 
* I have spent around 1hour debugging to find out that codesandbox seems to randomly throw an error which when I refreshed was gone.

You have mentioned previously that examples could be kept in the `examples` folder. Is it in the pipeline to start doing that soon?

On a separate note I might have found the bug. Is that the expected behaviour?
<img width="1277" alt="screen shot 2017-08-05 at 21 27 13" src="https://user-images.githubusercontent.com/11786608/28998593-0f62419a-7a27-11e7-92fd-69d6d386c811.png">

**Comment by the-simian** [comment]
[I've made an example here](https://codesandbox.io/s/QMGq4kAY). Its based on material ui, thought it is a bit different from the existing material-ui example.
[As soon as I get some clarity about how to clear selection (correctly), I'd like to submit that to the existing examples.](https://github.com/paypal/downshift/issues/94)

**Comment by kentcdodds** [comment]
Hey everyone! :wave:

```
~/Developer/downshift (master)
🏎  $ npm publish --tag rc
+ downshift@1.0.0-rc.0
```

I need your help now! The library now has 100% code coverage and is ready to move forward! The first release candidate has been released. I think that the API is solid now and I'd love some feedback on things. Please build some examples and let me know what could be improved!

Please install the latest `rc`:

```
npm install downshift@rc
```

Or fork [this codesandbox](http://kcd.im/ds-example) and create your own examples! Thanks!

**Comment by nndung179** [comment]
sure I will update example & do some more :)

**Comment by kentcdodds** [comment]
Hey folks around here! There was a minor breaking change. Before the `onChange` handler accepted an object with a `selectedItem` property, now it is just passed the `selectedItem` property. See the README :smile:

```
~/Developer/downshift (master)
🏎  $ npm publish --tag rc
+ downshift@1.0.0-rc.6
```

**Comment by agirton** [comment]
Hi @kentcdodds 👋 , to help better understand the downshift API I built a `redux` version here: https://codesandbox.io/s/0o0w70lp8p does this look ok? I tried to keep it simple but also have some organization.

**Comment by kentcdodds** [comment]
That's great @agirton! Could you add it to the list of examples in the README? Thank you!

**Comment by agirton** [comment]
@kentcdodds sent a PR #157 with new examples 😄

**Comment by mplis** [comment]
@kentcdodds I've got a WIP example of a date picker built with Downshift: https://codesandbox.io/s/nwk52x9qo0

I have a few tweaks I'd like to make, but is there anything in particular you want me to clean up before I submit a PR?

**Comment by kentcdodds** [comment]
OH WOWOWOWOWOWOWOWOWOW!! That's super awesome!

I'm amazed at how simple it is!

I think it could use some fancy styling. Also, if I could change the month/year for the available selection that'd probably be good too, but this is super cool. Thanks @mplis!

**Comment by wcastand** [comment]
we can't do thread to respond, that's a shame, i don't to flood the conversation too much.
@mplis, maybe we could use [okami](https://github.com/wcastand/okami) to build the date picker with Downshift. 

I don't know if that could be a simpler thing but maybe it's worth looking into it :)

**Comment by kentcdodds** [comment]
I still want examples, but I'm trying to clean things up so I'm going to close this issue.

Thanks everyone!
