### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by souporserious** [paypal/downshift#10]
Pertaining to https://github.com/kentcdodds/react-autocompletely/issues/1 I personally think it would be beneficial to choose a name that promotes this library for multiple use cases. I think by naming it anything with `autocomplete` could paint the library into a corner. I'd love to see `Dropdown`, `Select` and other cool components made with this. The hard part is I have no idea what a new name could be 💩 

Some quick ones:
- rechoose - react + choose
- reelect - react + elect (maybe just elect by itself?)
- repick - react + pick
- picknic - 🤷‍♂️

**Comment by kentcdodds** [comment]
Ok, clearly the name is [confusing people](https://twitter.com/rem/status/892764754497941504).

I'm happy to rename this project, but it's gotta be good.

Why don't we come up with several suggestions, then I can make a twitter poll and see what folks think...

**Comment by souporserious** [comment]
😇 I'll give you selectly if you want it, since it's similar to the current name 😁

**Comment by kentcdodds** [comment]
We can make that an option. Though I'd like `react` in the name honestly. I don't expect that this'll work without (P)react...

**Comment by souporserious** [comment]
Sounds good 👍 `react-selectly` should be available. I'll try to think of some other names 🤔

**Comment by bernard-lin** [comment]
react-optionally 😂

**Comment by kentcdodds** [comment]
Ok, here's [the tweet](https://twitter.com/kentcdodds/status/892849013182955521) :smile:

**Comment by kentcdodds** [comment]
Because react-autocompletely can support such a wide variety of use cases, @markdalgleish [suggested](https://twitter.com/markdalgleish/status/892867022425436160) that we come up with a catching but totally meaningless name.

I like the idea! What do you think? Bonus points if it's in reference to something from ancient times (like greek mythology or Medieval times or something).

**Comment by kentcdodds** [comment]
Sometimes it might help to think of a logo/emoji first and then come up with a cool name. Here are some emoji that I think would be cool:

⚡️ 🔥 🔮 💫 ✨ 💥 🕵️‍♀️ 🔎

**Comment by bernard-lin** [comment]
I really like the Sherlock one...but probably because I really love the stories 😅

**Comment by kentcdodds** [comment]
Oh, what if we use a character from ["Mistborn"](http://mistborn.wikia.com/wiki/Mistborn) (I'm reading it right now):

> Mistborn are [Allomancers](http://mistborn.wikia.com/wiki/Allomancy) who are able to gain power from all Allomantic metals, and are some of the most powerful characters in the Mistborn series.

Basically, Mistborn are rare. More commonly you'll find Mistings. Mistings have one of 8 available powers, but Mistborn have all 8 powers. So the idea of flexibility is strong here.

So we could use [Kelsier](http://mistborn.wikia.com/wiki/Kelsier) ([not taken](https://www.npmjs.com/package/kelsier)). Though... we might run into trademark issues 🤔  #leftpad

As for an emoji/logo.... 💥 seems appropriate 🤔 

Maybe not 🙃

**Comment by kentcdodds** [comment]
[Azula](http://avatar.wikia.com/wiki/Azula) might be cool to go with 🔥

**Comment by sumorai** [comment]
react-selectively
react-positively
react-specifically
react-picky
react-choosey
react-pickle
react-pickly

**Comment by rouzbeh84** [comment]
that could be cool. i was thinking along the lines of animals like an owl 🦉 for all knowing wise, elephant 🐘 for it's memory/recollection, or even a golden-retriever 🐕 for it's....well, retrieving haha.  might be a bit of a stretch though.

maybe just `react-zoltan` like the fortune teller or `react-acadabra` with a 🎩  for a magician 😝

**Comment by mateo-io** [comment]
reactive-react

**Comment by souporserious** [comment]
react-choo 🚂
react-gather 👐
react-harvest 🌾
react-retriever 🐕 (credit to @rouzbeh84 from above, writing it out makes it sound so cool! 😎)

**Comment by kentcdodds** [comment]
I'm liking:

- react-kadabra 🔮
- react-retriever 🐕

But honestly I'm starting to think that `react-autocompletely` is pretty good and we should just stick with it. I dunno... It's already gotten a fair amount of traction.

**Comment by souporserious** [comment]
I vote for react-kadabra. I like that you can use the same emoji with it and since the library is still fairly new I think the name change would be fine. It hopefully help mitigate any confusion on it being more than an autocomplete component. I mean with kadabra we could make a reallllllly cool demo site since it has a sort of theme to it 😁

**Comment by kentcdodds** [comment]
> Plus, with a name like kadabra, we could make a reallllllly cool demo site since it has a sort of theme to it 😁

Alright, if you commit to making a cool demo site then consider it done.

**Comment by souporserious** [comment]
I'm soooo down 😍

**Comment by kentcdodds** [comment]
Nice!

**Comment by kentcdodds** [comment]
```
~/Developer/react-kadabra (master)
💪  $ npm publish --tag beta
+ react-kadabra@1.0.0-beta.7
```

**Comment by kentcdodds** [comment]
It'll take a little time for travis to update but hopefully it'll happen soon

**Comment by souporserious** [comment]
😱 🎉 yay! I'm leaving for vacation for two weeks soon, but when I get back I'm on it 💪

**Comment by rouzbeh84** [comment]
HOORAY! 👏🏽 🎉

@souporserious holler when you get back, i'll def try to help you out on the demo site if you'd like 🙏🏽

**Comment by kentcdodds** [comment]
I'll try to setup Netlify on this repo so we have an easy deployment story :smile:

**Comment by kentcdodds** [comment]
This is a good point: https://twitter.com/AntJanus/status/893116305431068673

<img width="626" alt="screen shot 2017-08-03 at 9 23 32 am" src="https://user-images.githubusercontent.com/1500684/28929545-6f0cc1c0-782d-11e7-9630-e529ca31ebc8.png">

We should probably avoid tying ourselves to the pokemon for this reason...

**Comment by kentcdodds** [comment]
And with that I'm honestly thinking that react-retriever 🐕 may be better... Yikes, all this naming stuff is giving me a headache.

**Comment by souporserious** [comment]
Oh dang that's a good point 😞 I always liked react-retriever as well. I don't know which is harder, a good API or naming something 💩

**Comment by kentcdodds** [comment]
Problem with react-retriever is it's not entirely easy to spell. Not a really common word people use...

Back to the drawing board....

**Comment by souporserious** [comment]
Orrr react-cadabra? Playing off of `Abracadabra` and not pokemon so there aren't any lawsuits 😁

**Comment by rouzbeh84** [comment]
`react-resilience` cause who knows what people are gonna put in your form inputs ;). Jk haha 

I like both of the resurgent finalists. FYI I only rethink in re-insert-words now 🤣😂

**Comment by alexkrolick** [comment]
I spelled "kadabra" wrong like 3 times (trying different variants  of abacadabra) whilw Googling after seeing it on Twitter and got really irrelevant results. Maybe as it gets more popular it will rank higher but right now... Not so great.

OTH I do like the Ruby convention of using somewhat fanciful or uncommon names for libraries to avoid giving the appearance of there being an official or "blessed" library in hot namespaces where there could be multiple competing projects. NPM, and react in general, is terrible in this regard (looking at you react-router!).

**Comment by kentcdodds** [comment]
I definitely want to keep this `react` specific as it is a react library, so having `react` in the name is important IMO (despite the drawbacks you mention).

> I spelled "kadabra" wrong like 3 times

Yeah, that's unfortunate... Let's go with something easy to spell.

**Comment by rossipedia** [comment]
react-completionist
react-volunteer
react-ucompleteme (please don't)

**Comment by alexkrolick** [comment]
> react specific as it is a react library

The react part is fine and makes sense, it's "well I'm the first library here so I get the most obvious name" part that isn't great. I.e., react-select, react-router are one of many.

Is there always an input box? If so, "react-typeahead-toolkit" is sufficiently specific to avoid future naming conflicts, without using nonsense words.

**Comment by souporserious** [comment]
That's part of the issue 😕 there doesn't always need to be an `input` it can be used to make a simple dropdown with keyboard navigation as well as other components.

**Comment by tkh44** [comment]
`downshift`

**Comment by kentcdodds** [comment]
I like that a lot actually @tkh44!

Now for a emoji... The first thing that comes to mind is 🏎  which is totally awesome 🕶 

Should it be `react-downshift` or just `downshift`?

Honestly... Someone could wrap this lib up in [`preact-habitat`](https://github.com/zouhir/preact-habitat) by @zouhir and they could use it in any framework. It'd be pretty slick (and small) actually!

So I'm thinking simply `downshift`...

**Comment by tkh44** [comment]
I would just use the word without the react prefix.

**Comment by bernard-lin** [comment]
second that!

**Comment by kentcdodds** [comment]
@souporserious what do you think?

**Comment by souporserious** [comment]
:shipit: 🏎 🎉

**Comment by souporserious** [comment]
I like single names as well :) I don't think it necessarily needs react in the name. Think of all of the jQuery plugins that came out that didn't prefix jQuery.

**Comment by souporserious** [comment]
You cool to wait to change until the multiple stuff is done? 😁

**Comment by kentcdodds** [comment]
Sure, if you're working on it now :wink:

**Comment by kentcdodds** [comment]
So here's what I'm thinking about for a logo:

![downshift](https://user-images.githubusercontent.com/1500684/28936529-407938f8-7845-11e7-9f02-c550e87a7b24.png)

That emoji is coming from [emojione](https://www.emojione.com/emoji/1f3ce) (which is where I got the glamorous logo from)

But someone suggested I use [the one from twemoji](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f3ce.svg):

<img width="184" alt="screen shot 2017-08-03 at 12 14 28 pm" src="https://user-images.githubusercontent.com/1500684/28936587-5db793ce-7845-11e7-9ad3-c24e70b983cf.png">

I like this because it means that the logo will look the same on the project as it does on twitter... But I kinda like the red one more...

Give an emoji response on the comment to indicate which you like better:

- Emojione (red car): :tada:
- twemoji (orange/blue car): 😄

**Comment by kentcdodds** [comment]
Another benefit is I don't have an SVG for the one from emojione so we'd have to make that ourselves....

**Comment by souporserious** [comment]
Coming from a design standpoint, I like the red car better 😁

**Comment by kentcdodds** [comment]
Ok! Rename is done and I added a simple png logo. Hoping to get a nice SVG soon!

**Comment by kentcdodds** [comment]
Oh snap. My friend @strack just sent me this as an SVG! :tada:

![screen shot 2017-08-03 at 1 08 38 pm](https://user-images.githubusercontent.com/1500684/28938937-df0eb4aa-784c-11e7-90e0-cbb5039984e3.png)

I'll update the logo on the README with this. Thanks tons Isaac!

**Comment by josephrexme** [comment]
Oops I guess I'm late. I did this https://gist.github.com/josephrexme/d35258ac2bc0ef5038795f2e8eee8860

**Comment by kentcdodds** [comment]
Ah, but 2 minutes! Thanks for working on it! I've already updated it with what Isaac sent me. I think I'll leave it as is. I really appreciate what you've done though, thank you :)

If you still want to help out, I'd love to have a help codesandbox (like [the one for glamorous](https://help.glamorous.rocks)). If you'd like to make that, I'd love it :smile:

**Comment by pqr** [comment]
*react-pqr* - simple, short, alphabet for everything
