### ISSUE TITLE
defaultValue can only be provided on initial render

### ISSUE THREAD

**Issue by ferdinandsalis** [paypal/downshift#101]
- `downshift` version: 1.0.0-beta.12
- `node` version: 8.2.1
- `npm` (or `yarn`) version: 5.3.0

**Problem description:**
When providing an initial value via `defaultValue` it will only be 'applied' on initial render. However when that value is only available at an later point (api call) it will be ignored.

**Suggested solution:**
Use component `componentWillReceiveProps` to handle the new `defaultValue`.

If this design is intended and my thinking is flawed feel free to close this issue. Though I would be happy for an explanation.

**Comment by kentcdodds** [comment]
I _think_ the new `defaultInputValue` prop will solve your issue :) Please update to the latest version and take a look at the docs :smile:

Thanks so much for the feedback! It's invaluable.

**Comment by ferdinandsalis** [comment]
I am glad I can help!
