### ISSUE TITLE
Better isOpen control

### ISSUE THREAD

**Issue by souporserious** [paypal/downshift#108]
I'm only on my phone so I haven't been able to test thoroughly, but since multiple logic has been removed, how should we handle keeping the menu open when selecting multiple values? I've actually wondered if this library should care about isOpen state the more I work with it. We use a Popover component at my work that takes care of this so I'm wondering if other people would face the same use case. I guess you could just ditch isOpen altogether and implement it yourself?

**Comment by kentcdodds** [comment]
Thanks for bringing that up @souporserious! I've updated [the multiple selection example](https://codesandbox.io/s/W6gyJ30kn) to handle this use case! I think this is really showing the power of `state props` where if a certain prop isn't doing what you want, you can simply control it yourself :smile:

Let me know if that's not quite what you were hoping for and if there's something we can do to make it easier (without making the API more complex).

**Comment by souporserious** [comment]
That looks great! I'll take a look when I get back. Thanks! 🤗
