### ISSUE TITLE
Make controlled component easier

### ISSUE THREAD

**Issue by jgoux** [paypal/downshift#111]
- `downshift` version: 1.0.0-beta.21

Hello all,

I find it still too hard to make the Autocomplete controlled.

The stateProps concept is great for edge cases, but I'd expect to have at least a `value` prop on Autocomplete so we can make it controlled without caring about the internal state.

I tried using the `selectedItem` but then I have to handle **all** other interactions to update it.

I think adding a value props is just a matter of checking if `nextProps.value !== this.props.value` in `componentWillReceiveProps` and then update the state accordingly?

The couple `value` + `onChange` props are pretty standard among inputs components, and defining a `value` prop is often what it takes to pass a component from uncontrolled to controlled.

What do you think?

**Comment by kentcdodds** [comment]
Could you explain what you mean by a `value` prop? I'm pretty sure what you are calling a `value` prop is the `selectedItem` prop. I agree that for some of the state your `onStateChange` handler will be called a LOT (every time the internal state changes). I think this is desireable behavior. However, for the `selectedItem` you can [use `onChange` callback to update your controlled item selection like this](https://codesandbox.io/s/VmwEnJO79).

Let me know if that helps clear things up at all.

**Comment by kentcdodds** [comment]
I'll go ahead and close this, but if I'm missing something let me know and we can discuss it :)
