### ISSUE TITLE
Relying on the id attribute for selecting an item fails for compound components

### ISSUE THREAD

**Issue by ferdinandsalis** [paypal/downshift#113]
- `downshift` version: 1.0.0-beta.21
- `node` version: 8.2.1
- `npm` (or `yarn`) version: 5.3.0

**What you did:**
Render a compound component as Item.

**What happened:**
Item does not get selected.

**Problem description:**
Item get selected only when the target node has the id attribute. With compound components this is clearly a problem.

**Suggested solution:**
We could walk up the dom tree to the nearest id attribute (maybe use data-item-id) instead.

I think this problem was also mentioned in https://github.com/paypal/downshift/issues/110

**Comment by kentcdodds** [comment]
I think that one of the requirements of using this is that when you apply any of the get props functions you must forward _all_ the props regardless of what those props are. I can't think of any way to avoid doing this, even with a `data-item-id` type thing. These properties need to make it to the DOM whether it's a `data-item-id` _or_ an `id` prop. I'm not sure what you mean by:

> We could walk up the dom tree to the nearest id attribute (maybe use data-item-id) instead.

Could you clarify?

**Comment by kentcdodds** [comment]
One thing that I think we could do is document the requirement a little better. While downshift does not have any opinions about _how, where, when, or what_ you render, it _does_ have a strong opinion about what props are applied to the elements you want to hook into the downshift context.

Does that make sense? Should probably document the importance of that better [here](https://github.com/paypal/downshift#prop-getters) ([PRs happily accepted](http://makeapullrequest.com/))

**Comment by ferdinandsalis** [comment]
This would mean you would need to apply the id to every element in the Item.

What I mean when an element is clicked, check if its has the id attribute and if check the parent until you hit the component boundary which should definitely have it. Hope that is clear.

**Comment by kentcdodds** [comment]
Yes, that is clear. I'll fix that now. Thank you!

**Comment by kentcdodds** [comment]
Fixed it locally. Making a PR now. Thanks!

**Comment by kentcdodds** [comment]
```
~/Developer/downshift (master)
😎  $ npm publish --tag beta
downshift@1.0.0-beta.22
```
