### ISSUE TITLE
RC release feedback

### ISSUE THREAD

**Issue by jgoux** [paypal/downshift#119]
`downshift` version: 1.0.0-rc.1

Hello,

As I'm working on a [material-ui / virtual-list example](https://codesandbox.io/s/LWMA9QZj) using downshift I have a little list of remaining issues : 

- [x] The [`onMouseUp` listener](https://github.com/paypal/downshift/blob/master/src/downshift.js#L583) seems to force a rerender everytime we click outside of the component, even if there is no state / props changes. You can see the log on my codesandbox demo, try to click outside of the 2 components multiple times.
- [x] The `selectedItem` prop works great to make the component controlled, but the `inputValue` gets updated only when we finally click outside of the component (onMouseUp again I think). In my demo, try to select a value in the first component, then you'll notice the second one isn't updated fully until you click outside.
- [ ] The scroll management done internally in the lib seems to be in conflict with windowing libraries. I suspect the `scrollIntoView` and other functions which need to access the items nodes to be the problem. As the list becomes virtual, it tries to scroll to them before they are rendered. I had to do weird tricks to make it somehow workable, like adding this to my input component : 
```javascript
onKeyDown: e => {
  if (
    !autocompleteProps.isOpen ||
    !["ArrowUp", "ArrowDown"].includes(e.key)
  ) {
    return;
  }
  const top =
    e.key === "ArrowUp" && autocompleteProps.highlightedIndex === 0;
  const bottom =
    e.key === "ArrowDown" &&
    autocompleteProps.highlightedIndex === filteredItems.length - 1;

  if (!top && !bottom) {
    return;
  }

  const scrollToIndex = top ? filteredItems.length - 1 : 0;

  // go to the top or bottom of the virtual-list
  scroll({
    scrollToIndex
  });

  // allows to wait that the node to be highlighted is mounted
  setTimeout(() => {
    autocompleteProps.setHighlightedIndex(scrollToIndex);
  }, 0);
}
```

- [ ] The mouse interaction with the virtual-list is fine, but the keyboard one is buggy. When you hold `ArrowUp` or `ArrowDown` and the scroll gets too fast, the highlight / focus on item is lost.

- [ ] Still virtual-list related, the `Enter` event listener seems to be active only on initial mounted nodes. When you try to hit `ArrowUp`, and go at the bottom of the list, you can't select an item hitting `Enter`.

Don't hesitate to play with my demo to verify all of these issues.

We are almost there, thanks **a lot** to all contributors for the great work! 👍

**Comment by kentcdodds** [comment]
Thank you so much for this great feedback! I've addressed the rerender issue: https://github.com/paypal/downshift/pull/120

I'm looking at your second issue now. I know what to do. Thanks!

**Comment by kentcdodds** [comment]
Ok, I think that I've solved all the issues as far as I am able. There is [a slight problem with `react-tiny-virtual-list`](https://github.com/clauderic/react-tiny-virtual-list/issues/19).

**Comment by kentcdodds** [comment]
Note: The react-virtualized works just fine :wink:

**Comment by jgoux** [comment]
Wow that was **fast**! 🏎 

I switched to react-virtualized in my [material-ui / virtual-list example](https://codesandbox.io/s/LWMA9QZj) so the scrolling can work fine.

So I have these two remaining issues : 

- [ ] We can't select an item with `Enter` when using a virtual-list if this item wasn't rendered when the menu appears. (Try to go to the bottom of the list and hit `Enter` on the items, nothing happens, both in my codesandbox and in the story of react-virtualized)

- [ ] The controlled components are buggy when you try to reinitialize them (passing a `selectedItem` from a `not null` value to a `null` one). When I try to clear one of the two components of my example, the second one isn't updated.

- [ ] Related to the above issue, if you play a little longer with clearing the component state (like select an item, click the clear button, select an item again) the synchronization between the two components starts acting weird, but it's probably due to the `null` value not being properly handled when updating the controlled component.

🏎🏎🏎🏎🏎🏎🏎🏎🏎Thanks again for the great work! 🏎🏎🏎🏎🏎🏎🏎🏎🏎

**Comment by kentcdodds** [comment]
Thanks again for all the great feedback! Really invaluable! I've fixed the issues and released a new release candidate.

```
~/Developer/downshift (master)
🏎  $ npm publish --tag rc
+ downshift@1.0.0-rc.5
```
