### ISSUE TITLE
change the onChange API

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#130]
Right now the `onChange` callback is called with `{selectedItem, previousItem}` but I'm starting to think we should just call it with `selectedItem`. I'm thinking this because the `onStateChange` is only called with the `changes, allState` and doesn't include the previous state.

I just built the [geniejs example](https://codesandbox.io/s/jRLKrxwgl) and found I had to preserve the `previousInputValue` myself. It wasn't difficult at all and made total sense that I would have to do that to support my use case. So I don't think I want to add supporting passing the previous state to the `onStateChange` callback.

I want to have consistency between these two APIs. And I don't think that it's too much to ask folks to keep track of the previous state if they need it. In fact, I think it's odd that people have to destructure out the `selectedItem` in the `onChange` handler. So for that reason, I'm going to make this change unless someone can convince me otherwise... :smile:

**Comment by the-simian** [comment]
I assumed that you had included the selected and previous in the 'same spot to give folks the ability to perform some comparison before they do a  mutation. That said, I've not needed that - I can't really select the same thing twice manually. The only thing I could see is if you'd set it via code twice in a row.. in this case I'd expect a developer to compare *before* setting at all.

In other words, I agree, just pass the value, like everything else does.

**Comment by kentcdodds** [comment]
```
~/Developer/downshift (master)
🏎  $ npm publish --tag rc
+ downshift@1.0.0-rc.6
```

**Comment by jgoux** [comment]
Hello,

I think this change introduced a bug.

`onChange` is no longer called when calling `clearSelection`.

**Comment by kentcdodds** [comment]
Ah! Yes, that's a problem! Will fix that in a few hours!
