### ISSUE TITLE
Feature Request: Backspace to delete last option

### ISSUE THREAD

**Issue by srph** [paypal/downshift#139]
Most *multiple* autocomplete implementations I used in the past, most recently react-select, would delete the last option if backspace was pressed when the input was already empty beforehand.

This is doable with this project as it is, but maybe we could make implement this feature directly to the core. Maybe something like `getInputProps` could accept an `onBackspaceRemove`.

**Comment by kentcdodds** [comment]
I'm pretty sure that I'd rather not encode the concept of _multiple_ in this library. Would you mind making an example of a component that supports this using `downshift` so we can see how hard it is?

**Comment by srph** [comment]
I agree. Been using Downshift for a while now (app redesign at work). Thanks for this project - I love it!

IMO, there should be a separate token input. I'm still working on this internally, and I haven't reached a conclusion yet if an additional work is needed in integrating the mentioned component.

**Comment by kentcdodds** [comment]
> IMO, there should be a separate token input

Could you explain what you mean?

I'm glad that you're enjoying the package! Any feedback on things is greatly appreciated before we publish 1.0.0 (in the next week or two). And if you could add some examples that would be fantastic! :tada:

**Comment by srph** [comment]
I apologize about the term, but I'm referring to something tagging inputs like [preact-token-input](https://github.com/developit/preact-token-input) (which is where I got the term). These inputs are complicated in their own right (if fully functional), and don't necessarily need autocomplete baked into its internals (or the other way around!).

> And if you could add some examples that would be fantastic! 🎉

Honestly, been looking forward to! Hopefully I can put submit something within the following weeks :D.

**Comment by dashed** [comment]
@srph I'm definitely looking forward to seeing this example! 👍
