### ISSUE TITLE
Feature: Tab key selects highlighted value

### ISSUE THREAD

**Issue by ansumanshah** [paypal/downshift#140]
Can we add Tab key as well to select the highlighted item [here](https://github.com/paypal/downshift/blob/master/src/downshift.js#L368)?

and is it possible to display the highlighted item in the input field as we write it, or if we move up and down the highlight section it should reflect in the input value as well (like typeahead.js)?

**Comment by kentcdodds** [comment]
All of this is currently possible with the existing API and I don't think I want to add support for these things in core. If you have terrible implementing this yourself, let us know and someone can help. Start here: http://kcd.im/ds-example
