### ISSUE TITLE
deprecate old package names on npm

### ISSUE THREAD

**Issue by Haroenv** [paypal/downshift#143]
the names `react-autocompletely` and `react-kadabra` are still published and have no mention of `downshift`. They should be `npm deprecate`d with a message that refers to this version.

**Comment by kentcdodds** [comment]
Ah, very true! I'll do that asap

**Comment by kentcdodds** [comment]
[done](https://www.npmjs.com/package/react-autocompletely) and [done](https://www.npmjs.com/package/react-kadabra) :smile:

Thanks!
