### ISSUE TITLE
Review the 1.0.0 blog post

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#150]
Hey folks who are watching the repo! I'd love it if you could give the 1.0.0 release blog post a review for me: https://medium.com/@kentcdodds/introducing-downshift-for-react-b1de3fca0817

Feel free to add your comments to the medium post or here. Either way is fine.

Thanks again!

**Comment by the-simian** [comment]
I just read through it, and I felt like it was a good as any clear overview could be. I can especially relate to the situation of having to repeatedly remake this component throughout one's career.

Let me know when its 'ok' to share the article, I can't wait.

**Comment by kentcdodds** [comment]
Feel free to [share it](https://twitter.com/kentcdodds/status/900361058069630977)! :tada:

**Comment by morajabi** [comment]
We have already shared it :)
