### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentNode' of undefined when root node is not a DOM element

### ISSUE THREAD

**Issue by okonet** [paypal/downshift#154]
- `downshift` version: 1.0.1
- `node` version: 8.1.3
- `npm` (or `yarn`) version: 0.24.6

Relevant code or config

```javascript
import React, {PropTypes} from 'react'
import Downshift from 'downshift'
import {
  ListView, ListViewFooter, ListViewHeader, ListViewRow, Text,
  TextInput
} from 'react-desktop'

const FilteredList = ({ heading, items, selectedItem, onChange }) => (
  <Downshift
    defaultSelectedItem={selectedItem}
    onChange={onChange}
  >
    {({
        getInputProps,
        getItemProps,
        getRootProps,
        isOpen,
        inputValue,
        selectedItem,
        highlightedIndex
      }) => {
      console.log(getInputProps({placeholder: ''}))
      return <ListView {...getRootProps({refKey: 'innerRef'})}>
            <ListViewHeader>
              <Text size="11" color="#696969">{heading}</Text>
            </ListViewHeader>
            {items
              .filter(i =>
                !inputValue ||
                i.toLowerCase().includes(inputValue.toLowerCase()))
              .map((item, index) => (
              <ListViewRow
                {...getItemProps({item, index})}
                key={item}
                background={highlightedIndex === index ? '#d8dadc' : null}
              >
                <Text color="#414141" size="13">{item}</Text>
              </ListViewRow>
            ))}
            <ListViewFooter>
              <TextInput {...getInputProps({placeholder: ''})} />
            </ListViewFooter>
          </ListView>
      }
    }
  </Downshift>
)

FilteredList.propTypes = {
  heading: PropTypes.string,
  items: PropTypes.array.isRequired, // eslint-disable-line
  selectedItem: PropTypes.string.isRequired,
  onClick: PropTypes.func.isRequired
}

export default FilteredList
```

What you did:

When using `ListView` (i.e. compound component and not the DOM element) as the root element, I'm getting `Uncaught TypeError: Cannot read property 'parentNode' of undefined when root node is not a DOM element`

The error occurs here: https://github.com/paypal/downshift/blob/master/src/utils.js#L17

**Comment by morajabi** [comment]
@okonet Why don't you wrap your `ListView` into a simple `div` or `span` tag? 
Like this example: https://codesandbox.io/s/9rWEmzEv8

**Comment by okonet** [comment]
@morajabi because `ListView` is my wrapper. Why would I want to add another wrapper for my wrapper?

**Comment by morajabi** [comment]
It's a common pattern in React, there are several cases you need to wrap components inside `div` tags.
I'm not familiar with the Downshift code base yet to know whether this behaviour can be changed or not. I just gave a suggestion based on what I've seen so far in the examples.

**Comment by okonet** [comment]
It's a bad practice to say at least but I don't want to start this discussion here since it's unrelated.

**Comment by kentcdodds** [comment]
Sorry, been busy, you shouldn't have to have another wrapper. I'll look at this when I get a second. If you could dig deeper I'd appreciate it!

**Comment by kentcdodds** [comment]
My guess is that `ListView` does not accept an `innerRef` prop. So your solution is to either make sure that `ListView` can provide you a prop that will allow you to get a DOM reference to the node it's rendering, or render a wrapper `div`.

downshift just needs to get a reference to the root Node you render and it uses `ref` to do this.

**Comment by okonet** [comment]
> downshift just needs to get a reference to the root Node you render and it uses ref to do this.

I believe this can be achieved without passing it down. I'll need to check the source to make sure though.

**Comment by okonet** [comment]
@kentcdodds any reason you're not doing this 

https://github.com/paypal/downshift/blob/master/src/downshift.js#L717-L723

for the composite components?

**Comment by kentcdodds** [comment]
Yes, react doesn't forward ref props 😔

**Comment by kentcdodds** [comment]
So we'd get a ref to the instance of the composite component, not the DOM node rendered.

**Comment by okonet** [comment]
Oh I see. That sucks :-/

**Comment by kentcdodds** [comment]
It does. I considered using [findDOMNode](https://facebook.github.io/react/docs/react-dom.html#finddomnode) but that's highly discouraged and a pretty slow API. I think that this workaround is better, despite being kinda annoying.

One thing that you could do is write [a DOM Node Finder component](https://codesandbox.io/s/my0lwo41kp):

```javascript
import React, {Component} from 'react'
import {render, findDOMNode} from 'react-dom'

class NodeFinder extends Component {
  setRef = reference => {
    this.props.innerRef(findDOMNode(reference))
  }
  render() {
    const {children, innerRef, ...rest} = this.props
    return React.cloneElement(children, Object.assign(rest, {ref: this.setRef}))
  }
}

class SomeComponent extends Component {
  render() {
    return <div>Hello world!</div>
  }
}

class App extends Component {
  logNode = node => {
    console.log(node)
  }
  render() {
    return (
      <div>
        {`Open the console and you'll see the node logged`}
        <NodeFinder innerRef={this.logNode}>
          <SomeComponent />
        </NodeFinder>
      </div>
    )
  }
}

render(<App />, document.getElementById('root'))
```

I could imagine there being some other way to find the node rather than using `findDOMNode`, but I'm not sure what it'd be 🤔

**Comment by okonet** [comment]
I believe `findDOMNode` was designed for such cases. I'm still using it in some of my components because of that. Not sure about performance implications. Any links?

**Comment by kentcdodds** [comment]
Just [this tweet](https://twitter.com/kentcdodds/status/892498164783218688)
