### ISSUE TITLE
Clicking item via dropdown not working with react-tether

### ISSUE THREAD

**Issue by nehero** [paypal/downshift#164]
- `downshift` version: 1.2.0

Relevant code or config:

https://codesandbox.io/s/jlkn76rvlw

What you did:

I'm using [react-tether](https://github.com/souporserious/react-tether) to hoist the dropdown menu (because of overflow issues) outside the parent (moves it to a child of `<body>`). 

What happened:

Using the arrow keys + enter to select an item works great. Clicking a dropdown item does not work though, it simply closes the menu. This same code works if you just remove the `<TetherComponent>` wrapping. Do I need to somehow use `getRootProps`? But my understanding was that this is for the wrapper of everything, e.g. including the input. But the issue seems to be with just the wrapper of the menu.

**Comment by souporserious** [comment]
I recommend using [react-popper](https://github.com/souporserious/react-popper). The [tether project](https://github.com/hubspot/tether) has seemed to have been abandoned. You can find [an example with react-popper here](https://github.com/paypal/downshift/blob/master/stories/examples/react-popper.js).

**Comment by FezVrasta** [comment]
react-popper works just fine with react-portal, make sure to wrap them in the right order (you want `react-portal` around `<Popper />` and not around the whole `<Manager />` or inside `<Popper />`

**Comment by nehero** [comment]
Yeah I had the portal working with popper, the issue is that when you click a dropdown item nothing happens, see this fiddle

https://codesandbox.io/s/oq0q5jmlqz

**Comment by kentcdodds** [comment]
> when you click a dropdown item nothing happens, see this fiddle

My guess is the fact that the portal is not a child of the downshift root element. In an effort to avoid performance issues of adding a bunch of click handlers on all the items every render, we put a single click handler on the root element of your downshift component:

https://github.com/paypal/downshift/blob/47ee3b82d8aa9233b0f1c904e01ce7cb59fb437d/src/downshift.js#L380-L395

So, if you click on an item outside the root element, then that click handler wont fire. [I'm trying to make things work](https://codesandbox.io/s/z2ywk80z6p) by manually adding a click handler on the item, but that isn't firing for some reason...

**Comment by kentcdodds** [comment]
Ah, the reason my attempt isn't working is because the menu is closed before the `click` event fires, so by the time the click event comes around the `div` item is no longer there to respond to the event.

I'll have to think about this... Unfortunately it wont be as easy as adding an `onClick` handler for you because that clearly doesn't work. I think what you'll have to do is control the `isOpen` state and not set it to what downshift says you should set it to if the user clicked in the popover... 🤔 

This one's a bit tricky.

**Comment by kentcdodds** [comment]
A definitely hack would be to control the `isOpen` state and do a `setTimeout` in your `onStateChange` handler whenever the `isOpen` state changes... I'll do that really quick just to make sure it'll work.

**Comment by kentcdodds** [comment]
So that hack works: https://codesandbox.io/s/z2ywk80z6p

I'm going to leave my investigation at that. I would love an improved solution, but I'm afraid [I don't have time](http://kcd.im/no-time) to look into it any further.

**Comment by nehero** [comment]
Thanks for taking the time to look at this Kent, I really appreciate all of the work that you do!

**Comment by techniq** [comment]
I had used @kentcdodds workaround for my [mui-downshift](https://github.com/techniq/mui-downshift) component, but while fixing the inability to click on an item, it still had an issue where clicking on the scrollbar and scrolling would close the menu on mouseup.

A better approach, that seems to solve both issues, is to add a `onMouseUp` handler on your popper/menu and stopping the event from propagating to the window

```jsx
<Popper onMouseUp={e => e.stopPropagation()}>
  // menu...
</Popper>
```

@kentcdodds maybe worth adding a `getMenuProps` with `onMouseUp` defined?

**Comment by kentcdodds** [comment]
Thanks for the idea @techniq! I think that would be great to add to our documentation, but I'm not sure that it's necessary for 95% of the use cases so I don't think I want to introduce an `onMouseUp` prop getter. Thanks again!

**Comment by techniq** [comment]
The idea was to add a `getMenuProps` prop getter, but I agree it's unnecessary for most use cases (although hitting the [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) problem with multiple menu's and using a portal to work around the issue is also probably something worth adding to the docs).  I don't think I'll be able to get to a PR soon to update the docs, but if I see no one has when I do get some time, I'll send one your way.

**Comment by kentcdodds** [comment]
I'll re-open this issue to invite others to add these docs. But they'd be best to be written by someone who's experienced and worked around the issue :+1:

**Comment by kentcdodds** [comment]
Going to close this for inactivity.
