### ISSUE TITLE
Suggestion: Adding a ToC above README?

### ISSUE THREAD

**Issue by morajabi** [paypal/downshift#170]
I was looking for the **Examples** section in the README and I had to scroll all the way down to find it.
I'm thinking it'd be easier to navigate this long README with a useful ToC.

Probably auto-generated with [doctoc](https://github.com/thlorenz/doctoc)? 

If you wish I can make a quick PR on this.

**Comment by kentcdodds** [comment]
Yes, let's do it! :+1:

**Comment by morajabi** [comment]
Done! #171
