### ISSUE TITLE
Console errors when using 'toggleMenu' action prop

### ISSUE THREAD

**Issue by ikovic** [paypal/downshift#182]
- `downshift` version: 1.3.1
- `node` version: 8.2.1
- `npm` (or `yarn`) version: yarn 0.27.5

Relevant code or config

```javascript
export default class LanguageDropdown extends Component {
  itemToString = item => item.name;

  toggleDropdown = () => this.setState(state => !state.isOpen);

  render() {
    return (
      <Downshift itemToString={this.itemToString}>
        {({ toggleMenu, isOpen, ...rest }) =>
          <div className={s.inputContainer}>
            <Title onClick={toggleMenu} />
            {isOpen ? <Menu {...{ items: languages, ...rest }} /> : null}
          </div>}
      </Downshift>
    );
  }
```

What you did:

I've tried using the `toggleMenu` action and `isOpen` props to control the visibility of a dropdown menu.

What happened:

`isOpen` value changes as expected, but the console shows a bunch of these errors:
<img width="860" alt="screen shot 2017-09-09 at 15 08 34" src="https://user-images.githubusercontent.com/1204170/30240438-d0f1f080-9570-11e7-8a29-3c1a1e397d14.png">

Problem description:

Console gets a couple of above errors on each execution of `toggleMenu` action.

Suggested solution:

I could easily get around this by managing the state of `isOpen` on my own, but it would be better if I could use the `downshift` actions for that simple use case.

**Comment by tansongyang** [comment]
I'm seeing the same thing. I made a [minimal reproduction](https://codesandbox.io/s/81q4voppl9) and I get the same errors.

**Comment by kentcdodds** [comment]
Hi! Yeah, so the problem is that `onClick` handlers are invoked with an `event` and `toggleMenu` accepts an argument called `otherStateToSet`. So if it's passed an `event`, then downshift tries to set state with the `event`.

So the solution is simple: `onClick={() => toggleMenu()}`...

You know... I think we could make this nicer for folks. In [`toggleMenu`](https://github.com/paypal/downshift/blob/a1490f070575ffcd71dac8c063fe7e092f840a67/src/downshift.js#L610-L623), we could check if `otherStateToSet` is an `event`, and if it is, then we don't spread it on the state we return in our `internalSetState` callback. This would be tested [here](https://github.com/paypal/downshift/blob/4fd6ae258948c70f214d7f90ac03490d854eb39a/src/__tests__/downshift.misc.js#L58).

Who wants to [do this](http://makeapullrequest.com/)?

**Comment by tansongyang** [comment]
@kentcdodds I've got time to do this today.

**Comment by tansongyang** [comment]
If we do this in `toggleMenu`, would we also want to do it in the other places that spread `otherStateToSet`?

**Comment by kentcdodds** [comment]
I'm glad you asked! Yes, we should probably do this for all the `actions` which would commonly be used in this way. (`openMenu` and `closeMenu` come to mind)

**Comment by tansongyang** [comment]
Wow, you respond quickly! I actually just edited my second comment. What do you think of the new points?

**Comment by kentcdodds** [comment]
Yes, I like your item 3 idea. To avoid the issues though, we'll need to pluck those values off of the given object at the first of the function rather than in the callback. I'm thinking something as simple as:

```
  toggleMenu = (otherStateToSet = {}, cb) => {
    const {highlightedIndex, inputValue, isOpen, selectedItem, type} = otherStateToSet
    this.internalSetState(
      ({isOpen}) => {
        return {isOpen: typeof isOpen === undefined ? isOpen : !isOpen, highlightedIndex, inputValue, selectedItem, type}
      },
      () => {
        const {isOpen} = this.getState()
        if (isOpen) {
          this.highlightDefaultIndex()
        }
        cbToCb(cb)()
      },
    )
  }
```

We wouldn't really need a util for this I think... But maybe.

**Comment by tansongyang** [comment]
Also, you mention `closeMenu` and `openMenu`, but they don't accept `otherStateToSet`. Should they?

**Comment by kentcdodds** [comment]
Haha, I thought they did, but looks like they don't. We're probably good to leave them as-is

**Comment by tansongyang** [comment]
Sounds great. I'll PR when I'm finished.
