### ISSUE TITLE
manually update downshift's internal state of input field

### ISSUE THREAD

**Issue by scottjason** [paypal/downshift#184]
- `downshift` 1.4.0:
- `node` version: 7.4.0
- `yarn`: 0.19.1

Relevant code or config

```javascript
  onStateChange(selected, dsProps) {
    this.props.setInputAndSelectedType(dsProps.getInputProps().value, selected.type)
  },
```

Problem description:

Hi again. I'm using downshift for Instacart's main new search component and need to be able to replicate what we're currently doing, which is:

When a user highlights a suggested item (presses down), replace the input field with whatever is highlighted. This behavior can also be seen on google's search bar.

Right now, under downshifts actions, I don't see any exposed functions I can call to update downshifts internal state of the input field. Also, all the examples show that the input field is not being updated to correspond with the highlighted item. 

So in the relevant code above, is there a way I can update downshift's internal state of the input field before setting this value in redux?

I understand that `inputValue` is a `Control Prop` and that my "child callback function" should be able to update this, but am still a bit unclear on how to do so.

Thanks for any help! :)

Suggested solution:

Expose function to update downshift's internal state of the input field.

**Comment by kentcdodds** [comment]
Check out [this example](http://downshift.netlify.com/?selectedKind=Examples&selectedStory=autosuggest&full=0&down=1&left=1&panelRight=0). [Here's the code](https://github.com/paypal/downshift/blob/1cb2743827640bc7f92e19f2b8175e4253534a6c/stories/examples/react-autosuggest.js)

If you'd like to clean up that example a bit and put it in a codesandbox then we could include it in the list on the README so folks will find it easier :)

Let me know if this doesn't solve your problem :)

**Comment by scottjason** [comment]
Great, thank you. Yes, I'll definitely try to clean up this example and put in a codebox. Thanks for being so quick to respond, @kentcdodds! 👍
