### ISSUE TITLE
Select item even if it isn't in the items list

### ISSUE THREAD

**Issue by bogdansoare** [paypal/downshift#190]
Hey there 👋 
First of all I would like to thank you for the project, I was searching a long time for something like this 🙏 .

I got stuck using downshift in creating an autocomplete that can also be used to select new items that don't appear in the list.
Could you please help me with some guidance?

Thank you.

**Comment by kentcdodds** [comment]
Glad you like downshift! I think you'll like this example: https://codesandbox.io/s/82m2px40q9

or this one: https://codesandbox.io/s/xy66ml554

Good luck!

**Comment by bogdansoare** [comment]
Cool, thanks for the examples .
The main problem for me is how to trigger onChange when I hinter enter when focused on the input no matter what text is inside the input. Should I supply a `onKeyPress` to the input and listen for the **Enter** key ?

**Comment by tansongyang** [comment]
@bogdansoare I think it would help if you show some code. Could you share a working example on codesandbox (or something similar) that demonstrates your problem?

**Comment by bogdansoare** [comment]
Sure, in https://codesandbox.io/s/54po93zr64 you can see a working example with material-ui and apollo. I would like to recreate the same autocomplete from the ground up .
In the example you can select colors even if the color isn't in the list of option.
Also it would be nice if you have some examples on how I could implement debounce like in the example.

Thank you ❤️

**Comment by tansongyang** [comment]
I should have clarified. I mean, have you tried to start building with downshift yet? Did the examples help?

**Comment by Yosiempresafo** [comment]
@bogdansoare you could recreate the same autocomplete from the ground up using downshift? (select colors even if the color isn't in the list of option). I thought about the same functionality but I failed to program it. 😢 

Thank you 👍

**Comment by kentcdodds** [comment]
Take a look at the examples in the README. There's at least one that does what you're saying if I remember correctly...
