### ISSUE TITLE
disabled prop?

### ISSUE THREAD

**Issue by brentertz** [paypal/downshift#191]
Greetings. I am building a Dropdown component based on Downshift and need to provide a way to disable it.  Disabled styles, disabled event handlers, etc.

Have you given any consideration to including a `disabled` prop to Downshift?  If true, the event handlers to open the menu would then be suppressed.

I can do this on my own by simply excluding the eventHandlers after calling `getButtonProps` or `getInputProps`.  It seems like something that might be useful in the core though.

**Comment by kentcdodds** [comment]
Hi! Thanks for the idea! I think it's great. Would you like to start work on it? I'm happy to help where needed 👍

**Comment by brentertz** [comment]
Thanks Kent.  I’d be happy too if I can find the time, but not presently.

**Comment by kentcdodds** [comment]
Ok, I'll leave you open to anyone else who would like to contribute for fun or profit 😉

**Comment by pbomb** [comment]
I might be able to start work on this soon. Are you thinking that the `<Downshift>` component would take an additional (optional) `disabled=boolean` prop that would de-activate the event handling? That seems pretty straight-forward. @kentcdodds, with this approach, would you also send the `disabled` prop to the func-as-child function? Or is that considered redundant?

**Comment by kentcdodds** [comment]
Thanks Matt!

I think it could be useful to pass it along, sure 👍

**Comment by brentertz** [comment]
LOL, sweet!  @pbomb 💥

**Comment by vejersele** [comment]
Not sure if somebody else is already working on this, but I'm looking into this and I'm having some questions: 

If `disabled` would be a property of the `<Downshift>` component we would have to transfer it to the state in the component. This would also require us to add a componentWillReceiveProps lifecycle method right? Otherwise the component won't re-render when the disabled prop changes ... 

Also, we probably want to set some additional properties on the button and input to disable them right?

**Comment by pbomb** [comment]
Hi @vejersele, thanks for looking into this! I don't believe anyone else has started on it yet.

I would treat the `disabled` prop similar to the other controlled vs uncontrolled props such that you would store it in state, pass it to the render prop function, and update it when the consumer changes its value. I think the typical use case will be that a component will not be disabled for its entire lifespan, but will be enabled / disabled by some other change within the consuming application.

**Comment by kentcdodds** [comment]
I've considered this a little bit further and I'm wondering now whether I want to do this. The original argument was:

> Have you given any consideration to including a disabled prop to Downshift? If true, the event handlers to open the menu would then be suppressed.

> I can do this on my own by simply excluding the eventHandlers after calling getButtonProps or getInputProps. It seems like something that might be useful in the core though.

However, now that I think of it, couldn't you just disable the input field and that would prevent event handlers functioning as well? 🤔 

I do want to be as usable as possible, but I also want to avoid bloating the library to make it overly complex unnecessarily... Thoughts?

**Comment by brentertz** [comment]
Sensible idea...  FWIW, I tried just disabling the trigger element (both input and button scenarios) in some of the Downshift examples and that seemed to work fine, until I tested in IE11.

**Comment by kentcdodds** [comment]
If you no longer have a need for it, let's close this issue. Can always reopen it if someone else needs it :+1:

**Comment by brentertz** [comment]
Sounds good to me.  Thanks!

**Comment by kentcdodds** [comment]
What if the solution was as simple as:

```javascript
<input {...(disable ? {} : getInputProps())}
```

🤔 I wonder how bad that would be...

**Comment by kentcdodds** [comment]
Or what if we did: `getInputProps({disabled: true})` and inside `getInputProps` we just change what we return? I think that would do it and it'd make total sense :+1:

If anyone wants to implement it this way then be my guest and I think I'd be willing to accept that.

Opening....

**Comment by andreiglingeanu** [comment]
That's actually how I'm handling it, just by [disabling the `input` element](https://github.com/bogdanbiv/TokenFilter/blob/18d42b96ea2a2bf5437aeffc45775b27c025a6cc/src/basic-autocomplete.js#L34). That's good enough for me. 

My guess is that we don't really need it to be handled by `getInputProps`, but that's only my opinion.

You could as well add a `placeholder` prop to downshift, which will get proxied into `getInputProps`. But who would need that when we've got render props?

**Comment by kentcdodds** [comment]
Thanks for the input @andreiglingeanu. Unfortunately simply disabling the input wasn't enough to prevent the events from firing in IE11 (at least that's what I assume @brentertz meant in his earlier comment).

**Comment by brentertz** [comment]
Everything worked fine in IE11 when disabling the input.  It was when using a button as the trigger element that did not work in IE11.  

This kind of makes sense, with an input a user cannot set a cursor in it to trigger a change event. 
 With button, a user can still click on it.  IE still executed the click handler even though the button was disabled.

**Comment by kentcdodds** [comment]
Ahhh, I see... Hmmm, yeah, that makes sense. I'd much rather have people pass `disabled` to the prop getters than have it configurable at the component level. And people will naturally want to disable the input and button when they wish to disable the event handlers so I don't think it's asking too much to pass `disabled` to both `getButtonProps` and `getInputProps`.

I'm going to go ahead and work on this right now because I'm itching to get some coding in. If someone else would prefer I save this for them though let me know. Happy to let someone else have some fun coding :)
