### ISSUE TITLE
`defaultHighlightedIndex ` is set back to `null` after first selection

### ISSUE THREAD

**Issue by SpaceK33z** [paypal/downshift#194]
- `downshift` version: 1.7.0
- `node` version: 8.3.0
- `npm` (or `yarn`) version: 5.4.2

What you did:

I set `defaultHighlightedIndex={0}` on the `<Downshift />` component.

What happened:

When selecting an item for the first time, it correctly highlights the first item. After changing the selection for a second time however, there is no default highlight on the first item anymore. This is because `highlightedIndex` is reset to `null` after the first selection. 

Reproduction repository:

https://codesandbox.io/s/vnkkw205kl

Problem description:

Most "fancy select" components automatically select the first item in the list, so the user can just press `<enter>`. E.g. react-select does this. I tried to imitate this functionality by using the `defaultHighlightedIndex` prop, but it did not behave like I expected.

Suggested solution:

Don't reset `highlightedIndex` to `null`, but reset it to the value in `defaultHighlightedIndex` after selecting an item. I don't know if that makes sense though, so perhaps what I'm asking is if there's another easy way to achieve this?

-----

Btw: I really like Downshift! This finally let me to understand why packages that only provide primitives are so powerful 👍

**Comment by kentcdodds** [comment]
Thanks @SpaceK33z!

I think this is a bug. Would you be willing to make a pull request to fix it? Check out the contributing guidelines 👍

**Comment by SpaceK33z** [comment]
Working on a fix now (or at least an attempt).
