### ISSUE TITLE
Cycle to input on arrow down and arrow up

### ISSUE THREAD

**Issue by denkristoffer** [paypal/downshift#196]
Hey! I'm trying to figure out if it's possible to make the suggestions cycle through to the input as well when navigating suggestions with the arrow keys? That's the way Google works, which seems to work really well to me.

**Comment by kentcdodds** [comment]
Hi @denkristoffer,

You mean [like this](http://downshift.netlify.com/?selectedKind=Examples&selectedStory=autosuggest&full=0&down=1&left=1&panelRight=0)? :smile:

Here's the implementation: https://github.com/paypal/downshift/blob/efbbe1992382753377312d008060d382629c4dc7/stories/examples/react-autosuggest.js

Good luck!

**Comment by denkristoffer** [comment]
Hey @kentcdodds, actually that example is what I've got up and running at the moment, but it's not quite the behaviour I'd like to end up with. I tried making a GIF that hopefully makes the difference clear: 

![myjimbibyr](https://user-images.githubusercontent.com/219017/30780710-d044cd68-a111-11e7-8812-aba01f5cf989.gif)

Have a great Sunday 🙂

**Comment by kentcdodds** [comment]
Yeah, that's definitely possible, but I don't have time to build it for you. Once you have it done, I think that'd be a super cool example!

**Comment by denkristoffer** [comment]
Awesome! But just to make sure, should this be possible with Downshift as it is now? If so, I'll dive into the code and see what I can come up with 🙂

**Comment by kentcdodds** [comment]
Yes, this is definitely possible with downshift as it is without any changes 👍

**Comment by garrettn** [comment]
Hi @denkristoffer, did you ever come up with a solution? I know this issue is closed but I'm facing the same problem now and I'm curious if you were able to come up with a working example.

**Comment by denkristoffer** [comment]
@garrettn Yeah, but it felt kind of dirty as I had to reimplement some Downshift internals, which is why I never shared it. Basically what I did was change `changeHighlightedIndex` to something like this:

```js
changeHighlightedIndex = (items, amount, highlightedIndex, setHighlightedIndex) => {
    const lastIndex = items.length - 1

    if (lastIndex < 0) {
      return
    }

    let baseIndex = highlightedIndex

    if (baseIndex === null) {
      baseIndex = amount > 0 ? -1 : lastIndex + 1
    }

    let newIndex = baseIndex + amount

    if (newIndex < 0 || newIndex > lastIndex) {
      newIndex = null
    }

    setHighlightedIndex(newIndex)
  }
```

**Comment by kentcdodds** [comment]
@denkristoffer, how did you go about changing that function? Did you have to fork `downshift`?

**Comment by denkristoffer** [comment]
Nope, I just pass a custom `onKeyDown` prop to `getInputProps` (which I had to do anyway for some other functionality) that handles `ArrowUp` and `ArrowDown`.

**Comment by kentcdodds** [comment]
Perfect! Do you use `event.preventDefault()` (supported by [`composeEventHandlers`](https://github.com/paypal/downshift/blob/22ed3d7e9be53320a94d41500ebccd611d1cac53/src/utils.js#L127-L141)) or do you just override the `onKeyDown` handler that comes from `getInputProps`?

I built things in such a way that doing something like this would not only be possible, but pretty easy. So either way, what you did isn't a hack but a supported feature :) 99% of people using downshift don't need this functionality, but for those who do, implementing it is (hopefully) fairly straightforward. I'm glad it's working for you!

If you'd like to [make and add an example](https://github.com/paypal/downshift#examples) of what you did that'd be super :+1:

**Comment by garrettn** [comment]
Ah! Thank you! `event.preventDefault()` was what I was missing. I was already doing a custom `onKeyDown` handler that sets the highlighted index to null if the user arrows out of range, but because of how `composeEventHandlers` works the index was getting overridden with a number. I didn't realize I could stop the composed event handler chain with `preventDefault`. Is that documented somewhere besides the source code? It's a really helpful thing to know.

**Comment by kentcdodds** [comment]
It's not documented actually! It was kinda experimental anyway. And the workaround is pretty easy (put your event handler outside the call to `getInputProps` directly on the element). But if you'd like to document this that'd be super :+1:

**Comment by denkristoffer** [comment]
Yeah, I found out about `event.preventDefault()` after digging through the source, it seemed cleaner than passing the prop directly on the input, as you say 🙂 I will try to remember to make an example on Codesandbox this week then!

**Comment by denkristoffer** [comment]
Here's where I'm at so far: https://codesandbox.io/s/2k1klkk0y – I'd like to polish it before creating a PR but it'll probably have to wait until the weekend. I'm just saving the link here 😉

**Comment by kentcdodds** [comment]
That looks awesome! I love that you only `preventDefault` when it's the keys you're interested in. That shows me that the `composeEventHandlers` is actually useful because it allows you to preserve the existing behavior except for certain cases :+1: Good work!
