### ISSUE TITLE
index prop required in getItemProps

### ISSUE THREAD

**Issue by hozefaj** [paypal/downshift#207]
The [Readme](https://github.com/paypal/downshift#getitemprops) mentions that `index` is optional  parameter in `getItemProps`. 

However omitting `index` out, leads to error. Checkout https://codesandbox.io/s/rkn35nxjm. Once user types a value into the `input` field, code throws the error.

**Possible fix**
Update doc to reflect this behaviour. Happy to send a PR with the change.

**Comment by tansongyang** [comment]
Closing because the linked example uses version 1.0.0. `index` was made optional in [1.2.0](https://github.com/paypal/downshift/releases/tag/v1.2.0). You can get the behavior you want by upgrading.

**Comment by hozefaj** [comment]
In that case can we update the example code  & Readme to reflect that update. Latest codebox: https://codesandbox.io/s/3830k2o0yp with updating the dependency.

**Comment by kentcdodds** [comment]
Nice catch. I've updated it. Thank you!
