### ISSUE TITLE
Add downshift intro blog post references to the README

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#211]
I want this above the horizontal line above the badges in the readme:

```
> See [the intro blog post](https://blog.kentcdodds.com/introducing-downshift-for-react-b1de3fca0817)
```

Please follow [the CONTRIBUTING.md](https://github.com/paypal/downshift/blob/master/CONTRIBUTING.md) instructions.

I'm going to open this issue to first timers only. This means that if you've ever contributed to an open source project before, please let someone else take this one.

First person to comment with: "I'm working on this right now" will have their pull request iterated on and merged :) I'm happy to help you out!

**Comment by rickMcGavin** [comment]
I'm working on this right now
