### ISSUE TITLE
Add reference to the prop getters blog post

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#212]
I want this right below the title [prop getters](https://github.com/paypal/downshift#prop-getters)

```
> See [the blog post about prop getters](https://blog.kentcdodds.com/how-to-give-rendering-control-to-users-with-prop-getters-549eaef76acf)
```

Please follow [the CONTRIBUTING.md](https://github.com/paypal/downshift/blob/master/CONTRIBUTING.md) instructions.

I'm going to open this issue to first timers only. This means that if you've ever contributed to an open source project before, please let someone else take this one.

First person to comment with: "I'm working on this right now" will have their pull request iterated on and merged :) I'm happy to help you out!

**Comment by Ronolibert** [comment]
I"m working on this right now!

**Comment by kentcdodds** [comment]
Well done @Ronolibert!
