### ISSUE TITLE
preact support removed?

### ISSUE THREAD

**Issue by throngar** [paypal/downshift#218]
- `downshift` version: 1.7.0 and up

Problem description:
Is `preact` still supported? In version 1.6.0 there were `preact` specific module versions in `dist`: https://unpkg.com/downshift@1.6.0/dist/. Starting from version 1.7.0 the `preact` modules are gone: https://unpkg.com/downshift@1.7.0/dist/ or https://unpkg.com/downshift@1.11.0/dist/.

**Comment by kentcdodds** [comment]
Sorry about that. I think I've fixed it. Give it a few minutes. Let me know.

**Comment by throngar** [comment]
Wow that was fast. Thx, works great now. I guess readme could be updated to state new location of the preact modules.

**Comment by kentcdodds** [comment]
Good idea! Would you be willing to do that?
