### ISSUE TITLE
Flow typed

### ISSUE THREAD

**Issue by souporserious** [paypal/downshift#23]
How do you feel about adding Flow to this project? Could even add inline comments while doing this so docs can be generated later.

We could even take it a step further and remove PropTypes in favor of just Flow with [babel-plugin-react-flow-props-to-prop-types](https://github.com/thejameskyle/babel-plugin-react-flow-props-to-prop-types).

**Comment by nitin42** [comment]
Can I work on this ? (PR) I've used Flow earlier!

**Comment by nitin42** [comment]
having a type system makes it easy to understand the codebase rather than increasing verbosity @kentcdodds

**Comment by kentcdodds** [comment]
I'm not worries about increased verbosity. I'm worried about familiarity for beginners. But maybe that concern is overblown and it won't be bad. Feel free to submit a pull request. Thanks!

**Comment by nitin42** [comment]
Awesome!!

**Comment by kentcdodds** [comment]
I'll tell you what. If we can add a short intro and links to resources in the CONTRIBUTING.md, then I say let's go for adding flow to the project :+1:

**Comment by nitin42** [comment]
Intro and links about setting up Flow or ?

**Comment by kentcdodds** [comment]
Intro and links about the basics of what Flow is and the syntax. Everything someone would need to know to contribute to a flow codebase for the first time.

**Comment by kentcdodds** [comment]
Could just be a link to a blog post.

**Comment by nitin42** [comment]
Sure! I'll add a section for Flow in the `CONTRIBUTING.md` 👍

**Comment by vejersele** [comment]
Hi All,

I see that the PR for this added a .flow.js file which is awesome, but what about actually adding types to the code itself? It would make code changes a lot safer since you would have static type checking and there would be one type definition less to maintain, since it can be automatically generated?

**Comment by kentcdodds** [comment]
Hey @vejersele! I've definitely considered adding flow to my libraries. My main concern is that it will hinder contributions because folks who are unfamiliar with flow will have a hard time contributing....

**Comment by ttamminen** [comment]
If the source code itself is going to be typed then TypeScript should be also evaluated. I am biased towards TypeScript, so I will stay out of the discussion. Just reminding about the options. 😊

The feature sets on both type systems are more than enough.

What should be evaluated then?

- activity on 3rd party library definition creation [TS](https://www.npmjs.com/~types#packages) & [Flow](https://github.com/flowtype/flow-typed/tree/master/definitions/npm)
- tooling
- which libraries have taken the TypeScript/Flow to the internals

**Comment by kentcdodds** [comment]
Thanks for chiming in @ttamminen.

So long as I'm a maintainer on this project, it's very unlikely I'll choose TS over Flow. I don't have time to go into it, but just know that if I do add types, it'll be flow, not TypeScript.

**Comment by nitin42** [comment]
I'll start working on the Flow definition files (busy with some personal work). @ttamminen thanks for your suggestion but let's avoid adding types to the codebase and keep it minimal and clean. Also, let's not forget about the other contributors who are yet not comfortable with the JavaScript toolchain (Flow, TypeScript, etc). I remember, I started adding types to the codebase (downshift) but it affected the readability so we went with the option of creating the type declaration files instead.

**How you can help ?**

I'll continue to work on the Flow PR (type declaration file) and you can collaborate with me. You can also check its progress here #180

**Comment by stereobooster** [comment]
Hi. Everybody who want to participate are welcome to comment on this PR https://github.com/paypal/downshift/pull/399. Thank you

**Comment by stereobooster** [comment]
@dashed they are merged in next branch and will be released as part of v2.0

**Comment by kentcdodds** [comment]
downshift@2.0.0 will be released soon with this! Thanks @stereobooster!

Learn more: #461
