### ISSUE TITLE
onChange not called when selectedItem is already set to the inputs value

### ISSUE THREAD

**Issue by robin-drexler** [paypal/downshift#232]
- `downshift` version: 1.13
- `node` version: codesandbox
- `npm` (or `yarn`) version: codesandbox

Problem description:

Go to the [typeahead example](https://codesandbox.io/s/82m2px40q9)

 - Type "orange"
- Wait for the selection list to appear.
- Select "orange"

The alert "You selected orange" does not appear, because `onChange` is not triggered.
Probably caused by: https://github.com/paypal/downshift/blob/master/src/downshift.js#L283

Suggested solution:
Would anything speak against calling `onChange` even if the value did not change, as long as `selectedItem` is part of `stateToSet`? Or maybe allow by flag?

**Comment by kentcdodds** [comment]
Thanks @robin-drexler,
Hmm... The `onChange` shouldn't happen if the selected item is the same (it doesn't change). I don't think I want to allow it by a flag either. I think that would add unnecessary complexity. You should be able to get it from `onStateChange` though. Do you think you could workaround this issue?

**Comment by robin-drexler** [comment]
thanks @kentcdodds for the quick reply! :)

Maybe if `stateChangeTypes` were considered stable and clicking on an item would produce a type that is not unknown, it might be possible to workaround, but I'm not sure yet (especially considering the `inputValue` might already be updated at this point once #230 is merged).

Regardless of this particular issue: 
Have you thought about switching from `onChange` to `onSelect`? onSelect could always be called when an item is selected, regardless of prior values. If yes, what were the reasons to go against it? It's one of the things that came as a surprise to me when I first discovered downshift.

**Comment by kentcdodds** [comment]
Hmmm... What if you added a `onClick` handler to your items? `<div {...getItemProps({item, onClick: handleItemSelection})} />`

I'd just really prefer to workaround this issue as I don't think it's a very common situation.

**Comment by robin-drexler** [comment]
I guess that could work if I also added a `keyDown` handler for the input field to also account for the user picking by keyboard. I'd probably call `selectItemAtIndex` with `highlightedIndex`. But that feels like re-implementing a large portion of the downshift api. Will need to think about it, but we can close the issue here if a fix/change won't be accepted to address the issue directly in downshift.

**Comment by robin-drexler** [comment]
Would you be open to some sort of `onResetRequested` callback that would be called in `reset` and return state to be merged with Downshift's defaults?

This way one could override `inputValue`, but keep the rest as is.

Something like:

> downshift.js

```js
reset = (otherStateToSet = {}, cb) => {
    
    otherStateToSet = pickState(otherStateToSet)
    this.internalSetState(
      ({selectedItem}) => ({
        isOpen: false,
        highlightedIndex: null,
        inputValue: this.props.itemToString(selectedItem),
        ...this.props.onResetRequested(),
        ...otherStateToSet,

      }),
      cbToCb(cb),
    )
  }
```

> consumer
```js
<Downshift
          onStateChange={({ inputValue }) => {
            console.log(inputValue)
            return inputValue && this.setState({ inputValue })
          }}
          onChange={selection => alert(`You selected ${selection}`)}
          onResetRequested={() => ({inputValue: this.state.inputValue })}
        >
</Downshift>
```

**Comment by robin-drexler** [comment]
Ah, nevermind. This would not fix the issue if the user selects the same value for the second time.

type apple -> select apple -> onSelect called
press arrow down -> select apple -> onSelect not called

**Comment by kentcdodds** [comment]
Hmmm... So I'm thinking that maybe adding an `onSelect` may not be a terribly bad idea. This behavior (the current behavior) makes sense to me:

type apple -> select apple -> `onChange` and `onSelect` called
press arrow down -> select apple -> `onChange` not called, `onSelect` called

I think that's what you suggested in the first place. Is that right?

**Comment by robin-drexler** [comment]
Yes, that is what I had in mind. :)

I could try to prepare a PR if you'd be open to merge something that goes in that direction.

**Comment by kentcdodds** [comment]
Yep, after considering it, I'll merge any PR that implements this in a way that's as simple as possible, is tested, and documented :+1:
