### ISSUE TITLE
npm deprecate all version before 1.13.1

### ISSUE THREAD

**Issue by tansongyang** [paypal/downshift#233]
In light of the recent security patch, I think we should run this so that users are warned next time they download the dependency (similar to what `minimatch` does when you try to install versions < `3.0.2`:

    npm deprecate downshift@"< 1.13.1" "Please update to downshift 1.13.1 or higher to prevent an XSS attack vector"

[Source](https://docs.npmjs.com/cli/deprecate).

Of course, we can change the wording if we want to.

**Comment by kentcdodds** [comment]
Done! Thank you very much :clap:

<img width="869" alt="screen shot 2017-10-18 at 7 40 14 am" src="https://user-images.githubusercontent.com/1500684/31721800-9dcde8d2-b3d7-11e7-9011-8f3f90917465.png">
