### ISSUE TITLE
Extend auto-selection options

### ISSUE THREAD

**Issue by erikfox** [paypal/downshift#24]
As discussed in #9, explore expanding user options to tailor auto-selection of items to their needs.

Thoughts so far:
- In cases were selection must be a listed item, auto-selection of best match seems appropriate.
- In cases were input is not required to be listed item (e.g. creating a new item), auto-selection of a best match may be counter to intuitive behavior.
- In cases where selection may or may not be a listed item, auto-selection of best match may be preferred, but functionality must exist to intuitively allow user to submit input as-is (no selection).
- Some users type and submit/tab/enter too quickly to recognize that a selection has been automatically selected for them. In this case they will have to go back to the input and change the value, breaking flow.
- Some users would like to use custom submit behavior to delineate selections (e.g. typing a `,` to delineate a new tag.

**Comment by ansumanshah** [comment]
#140 +1 for this, and would like to help any update on the progress?

**Comment by kentcdodds** [comment]
Going to go ahead and close this for inactivity.
