### ISSUE TITLE
How to detect mouse leaving item list?

### ISSUE THREAD

**Issue by MaxGraey** [paypal/downshift#245]
It will be nice to have ```Downshift.stateChangeTypes.itemMouseLeave``` (as a counterweight to ```Downshift.stateChangeTypes.itemMouseEnter)``` or some callback listener like ```onOuterEnter(Leave)``` to determine when user leave opened dropdown menu and make possibility close it.

**Comment by kentcdodds** [comment]
Thanks for the issue! However no state changes when that event occurs so we won't as that, but you can definitely add an event handler on the item element that you render yourself.

Let us know if you need an example of doing that and I'm sure someone can help. Thanks again! And good luck!

**Comment by mmesar** [comment]
When the mouse is leaving item with a sense that it doesn't enter another item on item list highlightedIndex should change to -1 to note that nothing is highlighted. In that sense it is state change.
