### ISSUE TITLE
Missing dependencies for some examples.

### ISSUE THREAD

**Issue by CarlRosell** [paypal/downshift#246]
I was just browsing the docs when I noticed that some of the examples were broken and did not load as expected. I believe that this can have a harmful impact and that new users might be afraid of using it.

Here are all the "broken" examples:
- [Bare bones autocomplete](https://codesandbox.io/s/6z67jvklw3)
- [Type Ahead Example](https://codesandbox.io/s/82m2px40q9) (uses controlled `selectedItem` API).
- [Integration with `react-instantsearch`](https://codesandbox.io/s/kvn0lpp83) from Algolia
- [Integration with `fuzzaldrin-plus` (Fuzzy matching)](https://codesandbox.io/s/pyq3v4o3j)

I can fix all these examples, but that would mean forking and taking the credit for all hard the work. What would be a proper solution for this?

**Comment by kentcdodds** [comment]
Hi @CarlRosell, thanks for bringing this up! They seem to be working to me 🤔 
Anyone else see them broken? Try refreshing?

**Comment by CarlRosell** [comment]
Might have been something on codesandbox then. Now they were loading twice, once with the error still there and then refresh and now they all work. 🤔
