### ISSUE TITLE
How to not lose focus after selection but let user tab out ?

### ISSUE THREAD

**Issue by ShockiTV** [paypal/downshift#249]
- `downshift` version: 1.16.0
- `node` version: 8.6.0
- `npm` (or `yarn`) version: 5.3..0

What you did:
I want to control blur events and highlight so user can pick/select multiple items one after another. And than tab out to next form component.
I tried to control the blur behaviour by re-focusing element after each blur state change, but than I am not able to let user tab-out manually.

What happened:
As there is no onBlur or any similar event handler which let you counter-act focus disabling, only place to manage it seems to be onStateChange.
But there is the only type "__autocomplete_blur_input__" and no way how to distinguish the source of event. If it is automatic state update, or user TAB forced blur.

I had similar issue with onInputValueChange handler as it get called after each selection, but I was able to extract type from stateAndHelpers object and change my state only if it is "__autocomplete_change_input__" to prevent automatic forcing inputValue to empty string.

But there is no handler for blur event itself, so I have no way of detecting what caused it nor preventing it by calling .preventDefault or returning false from handler so framework know to not execute the automatic blur event triggered by some action. And onStateChange's stateAndHelpers object have no type property.

Suggested solution:
Add onBlur handler with stateAndHelpers object which would have type from source event which triggers it.

Another solution would be breaking change - to let user control state update before it happens and not only call onStateChange after the action is already done.  Currently we are just trying to reconstruct what could have possibly changed after change already happened with already lost previous state. Which does not seems to be very happy approach.

**Comment by ShockiTV** [comment]
Sorry, it was my bad cause I was doing .focus on other element in DOM in my onSelect handler.
Now it is keeping focus correctly as I would expect till I hit tab.

**Comment by kentcdodds** [comment]
Sounds good. Glad you got it worked out @ShockiTV!
