### ISSUE TITLE
Replace scrollIntoView with scroll-into-view-if-needed

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#253]
I'd like to reduce the amount of code to maintain and `scrollIntoView` is probably the most complicated code in this project. [Richard pointed me](https://twitter.com/richardszalay/status/928128167117701120) to [`scroll-into-view-if-needed`](https://github.com/stipsan/scroll-into-view-if-needed). Looks like it could be a good replacement.

Anyone want to make a PR to [replace `scrollIntoView`](https://github.com/paypal/downshift/blob/22ed3d7e9be53320a94d41500ebccd611d1cac53/src/utils.js#L50) and see how it impacts the examples?

**Comment by Drapegnik** [comment]
It would be interesting to me, but at the moment there is no time. I can try to do it during the week

**Comment by razh** [comment]
Note that [`scroll-into-view-if-needed`](https://unpkg.com/scroll-into-view-if-needed@1.2.8/dist/) (`bundle.js`is 9.51 kB unminified) includes the [amator](https://github.com/anvaka/amator) animation library [(8.13 kB unminified)](https://unpkg.com/amator@1.1.0/dist/).

**Comment by kentcdodds** [comment]
Ah, that's good to know @razh! Thanks for bringing that up! We definitely don't want that :-/

Maybe we should just take ours and extract it to an isolated package if we can't find something else? I feel like there's gotta be a good, small solution to this!

**Comment by Drapegnik** [comment]
@kentcdodds how you see the best way:
1. fork `scroll-into-view-if-needed`, get rid of `amator` and:
    1. use it by direct link on github fork repo?
    2. publish new package and use it?
2. completely extract source code as new package

In first case we'll still be able to update ours fork from parent

**Comment by kentcdodds** [comment]
Well, if we can't find anything better than what we have built ourselves, then I say let's make a new package out of what we have.

Alternatively we could just not worry about it and leave things as they are 😅 Maybe I'm just complicating things...

**Comment by Drapegnik** [comment]
How about use [`patch-package`](https://github.com/ds300/patch-package)?

**Comment by kentcdodds** [comment]
Interesting! I've never heard of that before! That is _definitely_ overkill though. I thought about this as a passing idea that would make downshift a little easier to maintain. It's not really a big sticking point for me, and I feel like doing something like that would overcomplicate things...

**Comment by stipsan** [comment]
Hey guys, just want to let you know that we just introduced a simpler API interface for `scroll-into-view-if-needed`. Next step is to get rid of amator and reduce bundle size as much as possible 😄

**Comment by kentcdodds** [comment]
Cool! If you're able to make it small and satisfy the use case we have then I'd love to use it!

**Comment by stipsan** [comment]
The plan is to replace https://github.com/anvaka/amator with https://github.com/chrisdickinson/raf, that decision was an easy one.
But for letting you control the easing in userland I'm still on the lookout for a minimal library that lets you set a cubic bezier like easing. Best package I've found is https://github.com/arian/cubic-bezier but I'm not sure if it's the way to go.

Speaking of which is animated transitions within your use case or not? If it's not I could publish another file you can import from the package that don't include any animation logic so you don't have to pay the cost 🙂

**Comment by kentcdodds** [comment]
Yeah! We don't need animations, so if you could make it so I don't have to include that but that would be great!

**Comment by stipsan** [comment]
ah! Then you don't need to wait for a animation refactor, I'll publish an update for you soon 😄

**Comment by stipsan** [comment]
Does this look good for your use case? https://github.com/stipsan/scroll-into-view-if-needed/pull/152

**Comment by kentcdodds** [comment]
See the PR for an explanation for why this is closed.
