### ISSUE TITLE
Examples 「Integration with Redux」TypeError

### ISSUE THREAD

**Issue by madeinfree** [paypal/downshift#256]
- `downshift` version: 1.0.0-rc.18
- `node` version:
- `npm` (or `yarn`) version:

[Example Link](https://codesandbox.io/s/0o0w70lp8p)

Relevant code or config

```javascript
// reducer.js
export const select = createReducer(initialState, {
  [ADD_ITEM]: (state, { item }) => ({
    selectedItem: item
  }),
  [REMOVE_ITEM]: (state, { item }) => ({
    selectedItem: item
  })
});
```

What you did:

#### Select a item from input.

What happened:

#### The `items` state is missing in store.

Reproduction repository:
<img width="289" alt="2017-11-11 12 31 17" src="https://user-images.githubusercontent.com/4027049/32668154-c4f53e4e-c677-11e7-88c0-02cbdb6ac454.png">

Problem description:

#### Thanks for great example and work. not the project issue, but maybe other developer possibly feel weird in this example ~

Suggested solution:
```javascript
// maybe change into Object.assign

export const select = createReducer(initialState, {
  [ADD_ITEM]: (state, { item }) => {
    return Object.assign({}, state, { selectedItem: item })
  },
  [REMOVE_ITEM]: (state, { item }) => {
    return Object.assign({}, state, { selectedItem: item })
  }
});
```

**Comment by kentcdodds** [comment]
Ah, good catch, thanks! Feel free to make a pull request to update it to a new codesandbox that fixes this issue. Thanks!

**Comment by madeinfree** [comment]
Thank you @kentcdodds !
