### ISSUE TITLE
Question: Event for selecting an item?

### ISSUE THREAD

**Issue by chrisjlee** [paypal/downshift#267]
Is there an event to listen to for when the user selects an item from the autocomplete dropdown via the keyboard or via the mouse input?

Also, to the corollary, is there an event when an item is deselected?

**Comment by kentcdodds** [comment]
Hi @chrisjle,

You can use [`onStateChange`](https://github.com/paypal/downshift#onstatechange) for both of these. If you have further questions, please provide an example of what you're trying to accomplish by forking [this codesandbox](http://kcd.im/ds-example).

Good luck!
