### ISSUE TITLE
Keying down from last item to first item doesn't scroll all the way

### ISSUE THREAD

**Issue by Zashy** [paypal/downshift#274]
* `downshift` version: v1.22.1
* `node` version: v8.9.0
* `npm` (or `yarn`) version: v5.5.1

Relevant code or config is a bunch of custom internal junk, but I reproduced it at the [example](https://codesandbox.io/s/9rWEmzEv8).

What you did:
1. Load up the example
2. Click on the dropdown arrow
3. Press the down arrow key
4. Press the up arrow key
5. Press the down arrow key

What happened:
Where did the highlight go? (hint the math calculating what to scroll to didn't scroll all the way to the top)
![image](https://user-images.githubusercontent.com/1706342/33575282-b9abd77c-d901-11e7-92ec-f97571ead02f.png)

Reproduction repository:

Internal stuff bleh, but I used your example, hopefully that works.

Problem description:

The math calculating where to scroll to doesn't account for the parent's position properly when the node is above the page viewport.

Suggested solution:

This code seems to work for me, but I haven't fully tested it yet

```JavaScript
if (nodeRect.top < 0) {
    // the item above view
    scrollParent.scrollTop += nodeRect.top - scrollParentTop;
    return;
  }
```

**Comment by kentcdodds** [comment]
Thanks for this! If you could [make a PR](http://makeapullrequest.com/) with tests that would be super duper! :smile: Thanks 🗡

**Comment by Zashy** [comment]
I can sure try. Just not sure how fast I'll get my head around Jest for adding a test, heh.

**Comment by kentcdodds** [comment]
If you're an egghead subscriber maybe this will help: http://kcd.im/egghead-jest

If you're on Frontend Masters then maybe this: http://kcd.im/fm-testing

Thanks! :)

**Comment by kentcdodds** [comment]
Thanks a bunch @Zashy! 🎉
