### ISSUE TITLE
onUserAction typings issue

### ISSUE THREAD

**Issue by srishanbhattarai** [paypal/downshift#275]
* `downshift` version: 1.22.1
* `node` version: 8.9.10
* `npm` (or `yarn`) version: yarn 0.27.5

What you did:
Tried following the autosuggest [example](https://github.com/paypal/downshift/blob/efbbe1992382753377312d008060d382629c4dc7/stories/examples/react-autosuggest.js) in TypeScript.

What happened:
Could not use the `type` property on `onUserAction`'s callback parameter - as seen [here](https://github.com/paypal/downshift/blob/efbbe1992382753377312d008060d382629c4dc7/stories/examples/react-autosuggest.js#L23).

Problem description:
The [typings](https://github.com/paypal/downshift/blob/master/typings/index.d.ts#L37) for `onUserAction` options do not contain the `type` string which leads to the usual
`Property 'type' does not exist on type 'StateChangeOptions'` error. 

Suggested solution:
The typings need to be updated. ~~Also, it seems that the `onUserAction` callback is not documented~~. I can open a PR with these fixes.

EDIT: Just realized its plainly [stated](https://github.com/paypal/downshift/blob/master/src/downshift.js#L99-L106) that this wont be documented.

**Comment by kentcdodds** [comment]
I'd be willing to accept a pull request to update the TypeScript definitions. I'm warming up to the "experimental feature" anyway :)

**Comment by tansongyang** [comment]
If no one's taking this, I've got time to work on it.

**Comment by tansongyang** [comment]
Closing because this has already been merged.
