### ISSUE TITLE
Mouse interferes with keyboard navigation

### ISSUE THREAD

**Issue by jlongster** [paypal/downshift#280]
* `downshift` version: 1.22.3
* `node` version: 7.9.0
* `npm` (or `yarn`) version: 4.2.0

Relevant code or config

I made a sandbox, which is just the "basic" example from the site with some extra items: https://codesandbox.io/s/x3y2xzppyw

What you did:
What happened:

Here's a video: http://jlongster.com/s/downshift-scroll.mov

In Chrome, if you hover over an item and then try to use the keyboard to scroll down, it keeps highlighting the item that the mouse is hovered on. This is probably because whenever the element is scrolled, the `onMouseEnter` event is firing.

Suggested solution:

I have no idea. I actually started looking into this because I'm experiencing a different, but related bug, in my app but I can't boil it down to a reproducible test case. I'm hoping that whatever fix is made for this that it might help my bug too.

**Comment by kentcdodds** [comment]
Thanks James. I think this is a duplicate of: https://github.com/paypal/downshift/issues/240

**Comment by jlongster** [comment]
It does look like the same. Ideally we'd ignore all `mouseenter` events if we are manually scrolling. I don't have a local version of downshift right now to try that, but you could set `this.scrolling = true` before setting the `scrollTop` and then set `this.scrolling = false` afterwards.

I'm surprised because I thought `mouseenter` events weren't fired due to scrolling. It's problematic for me in a weirder way because when I scroll with the trackpad, it's firing these events as well, but  for some reason downshift thinks it needs to scroll the element that just fired `mouseenter` into view, causing janky scrolling. I don't know why it thinks it needs to scroll it into view (obviously it doesn't if it's an element triggering `mouseenter` from scrolling it into the cursor). I can look into that separately, but I'm hoping whatever fix for this bug will fix my bug too. (Although I just realized it probably won't, since it'll be specific to the above workflow)

**Comment by jlongster** [comment]
Finally able to reproduce my original issue! Opening a new bug.
