### ISSUE TITLE
Improved Mapping of ARIA Roles and Attributes.

### ISSUE THREAD

**Issue by cycomachead** [paypal/downshift#283]
* `downshift` version: 1.22.3
* `node` version: n/a
* `npm` (or `yarn`) version: n/a

Relevant code or config
See any example. :)

Problem description:
Currently, the ARIA roles used by downshift don't seem to map to the suggested locations. 
The ARIA Authoring Practices lists a few examples which are basically what downshift aims to solve:
https://w3c.github.io/aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

Suggested solution:

* The `combobox` role should be on the parent tag of the `<input>`. Since downshift already provides `getRootProps()`, I propose moving the role there and  updating docs to say this is a required function.
    * Secondarily, the related aria attributes for expanded and controlled should be moved here.
* The `input` should have have the role `textbox` and it should have `aria-controls` pointing to the items container. we can just update `getInputProps`
* There is a role (`listbox`) that should be applied to the element that contains the list. It would also need an `id` (for the aria-controls attribute above), and in the example provided, it should be `aria-labelledby` the main label. 
    * All this suggests we need a function `getItemListProps()` or something? 
* Each item needs a role of `option` and should have a state for `aria-selected` (which would be when an item is highlighted).

Additionally, I think we could make some improvements to the examples to use `ul` and `li` as the Authoring Practices suggest, which is a bit more semantically accurate. 

I'd also propose adding a section which illustrates the resulting DOM and prop getters mappings:

```jsx

<div {...getRootProps()}>
  <label {...getLabelProps()}>...</label>
  <input {...getInputProps()} />
  <ul {...getItemListProps()}>
    <li {...getItemProps()}>...</li>
  </ul>
</div>
```

phew...That was a lot, sorry! I'm happy to start working on a PR for these if it sounds like changes you'd like to make. I'm most unsure about adding another props getter, and what to call it.

**Comment by kentcdodds** [comment]
This is all fantastic! If you could make a pull request for these changes, we can iterate on the solution, and then I'd love to have it merged!

Instead of `getItemListProps` we could call it `getMenuProps` because I think that makes the most sense for folks using downshift.

Thanks again!

**Comment by kentcdodds** [comment]
This has been fixed and merged in the `next` branch. Should be part of v2.0.0 which should hopefully be released in the next week or so.
