### ISSUE TITLE
Selection via mouse click does not work when menu is inside a portal

### ISSUE THREAD

**Issue by Antontelesh** [paypal/downshift#287]
* `downshift` version: 1.3.0
* `node` version:
* `npm` (or `yarn`) version:

What you did:

Trying to implement simple select component using Downshift. The requirement for my select is that menu is inside a portal. I'm using `react-portal` npm package that leverages React's native `createPortal()` API.

What happened:

After I've put menu inside portal, selection via mouse stopped working. Menu is being closed as always, but selection does not happen.

Reproduction repository:

Here's a sandbox: https://codesandbox.io/s/w7p91ol19k
You can try selecting one of menu items. The `onChange` is not happening, the state is not changed. Try removing `Portal` element. Without portal everything works as expected.

I believe, there is something to do with mousedown and blur event handlers.
I have found that there are native event listeners for mousedown and mouseup events.
They are preventing the selection of item due to calling `reset` prior to that.

**Comment by Antontelesh** [comment]
I have found: https://github.com/paypal/downshift/blob/master/src/downshift.js#L796-L800

Here there is a check for mouseup event target to be inside the root element. Due to mouseup being browser native event and not a react synthetic one, this condition is met. That's because the menu is outside of Downshift root element.

**Comment by kentcdodds** [comment]
Thanks for the report! We could probably add a feature for the upcoming getMenuProps function (see the pull requests) which would apply a ref so we can check that as well as the root ref... Unless someone else has another idea.

**Comment by Antontelesh** [comment]
Thank you for so quick response. `getMenuProps` sounds like a good idea.

**Comment by circlingthesun** [comment]
I've just hit this problem. Is there maybe a workaround in the meantime?

**Comment by kentcdodds** [comment]
I'm at a cabin with my family right now with very limited internet access, but there is a work around. Any time you don't like what downshift does with state, you can control it yourself (see the readme). There's an example you can see here: https://github.com/paypal/downshift/blob/master/stories/examples/controlled.js

It's not an example of the workarounds necessarily, but hopefully that will point you in the right direction. If someone would like to help out by providing an example in codesandbox or something that'd be great!

**Comment by skywinston** [comment]
+1 for `getMenuProps` or any solution that would allow use with a Portal.  The behavior of the menu pushing all content below it down the page is undesirable in many circumstances.  It would be great render the menu in a portal passing in the values from `this.button.getBoundingClientRect()` so the menu can be positioned absolutely below the button without pushing content down.  

`Downshift` has been a total joy to work with so far @kentcdodds.  Terrific work and I'm looking forward to the updates.

**Comment by kentcdodds** [comment]
> The behavior of the menu pushing all content below it down the page is undesirable in many circumstances.

You can avoid that with a well-placed `position: relative` on the container and `position: absolute` on the menu. You shouldn't need portals for that.

> Downshift has been a total joy to work with so far

I'm so glad!

**Comment by skywinston** [comment]
@kentcdodds You're totally right.  That bit of CSS knowledge decided to escape my brain whilst working on this component.

**Comment by use-strict** [comment]
Menus have to be rendered inside portals because an arbitrary parent can have an 'overflow: hidden', clipping the menu.

**Comment by kentcdodds** [comment]
Depends on your situation, but yes, that's definitely a situation where it'd be nice to use a portal. I'll get to reviewing https://github.com/paypal/downshift/pull/285 now :+1:

**Comment by mperrotti** [comment]
Is there an estimate on when Portal support will be available? I saw https://github.com/paypal/downshift/pull/285, but not much activity the past two weeks.
I've been working on adding Portal support independently, but I don't want to step on anybody's toes.
I'm more than happy to help get this working! :)

**Comment by kentcdodds** [comment]
Thanks @mperrotti! I've made a comment in that PR.

**Comment by daphnesmit** [comment]
Really hoping this will be added soon:D

**Comment by rhinoceraptor** [comment]
@circlingthesun One workaround I've found works (courtesy of @techniq at [https://github.com/paypal/downshift/issues/164](https://github.com/paypal/downshift/issues/164))is to add ```onMouseUp: e => e.stopPropagation()``` to your ```getItemProps```. For my use case, I'm rendering my items inside of an existing context menu component I wrote that uses portals.

**Comment by circlingthesun** [comment]
@rhinoceraptor thanks. My workaround was to use `onMouseDown={e => selectItem(item)}`. That looks less hacky :)

**Comment by MarkFalconbridge** [comment]
Any idea when this will be resolved?

**Comment by kentcdodds** [comment]
I'm planning on spending time soon to finish #285 and resolve this among other updates.

If anyone wants that to happen sooner then please feel free to open a PR :)

**Comment by kentcdodds** [comment]
Hey folks! #285 was merged (into the `next` branch). Anyone want to work on adding a `refKey` prop to the new `getMenuProps` method? Make sure you make your branch off the `next` branch!

**Comment by kentcdodds** [comment]
lol, I was just working on this and having a really hard time reproducing it. I finally upgraded [the original codesandbox](https://codesandbox.io/s/wzvj823r8) to the latest version of downshift and the bug is gone!

However, it's still possible to reproduce if the user clicks on a non-item that's rendered within the portal, [like here](https://codesandbox.io/s/wn98on1015). So I'll fix that :)

**Comment by kentcdodds** [comment]
This has been merged into `next` which should be merged into `master` soon.

**Comment by renaudtertrais** [comment]
I still had the issue (v3.2.10). The solution of @circlingthesun solve it:

> @rhinoceraptor thanks. My workaround was to use `onMouseDown={e => selectItem(item)}`. That looks less hacky :)
