### ISSUE TITLE
onInputValueChange fire when tabbing out of input

### ISSUE THREAD

**Issue by riax** [paypal/downshift#289]
* `downshift` version: 1.22.5
* `npm` (or `yarn`) version: Yarn 1.0.2

Relevant code or config

https://codesandbox.io/s/w61oovz4v5

What you did:
1. Write some text in the input
2. Press TAB key

What happened:
onInputValueChange fire with empty value. 

Problem description:
Since the value has not changed this cause problems. Also the empty value provided is incorrect.

Suggested solution:
Do not fire onInputValueChange on TAB since the value has not changed

**Comment by kentcdodds** [comment]
Hi @riax,

Sorry, but when the `blur` event fires on the input, `reset` gets called which will reset the `inputValue` to the `itemToString` value of `selectedItem`. When that happens, the `inputValue` is changed and hence we call `onInputValueChange`. Does that make sense?

If you don't like this behavior, you can change it by adding an `onBlur` handler in `getInputProps` and call `event.preventDefault()` in your own blur handler. Like this: https://codesandbox.io/s/vjzk7rnwm3

Good luck!

**Comment by AnaRobynn** [comment]
Hi @kentcdodds!

It makes sense in the way I understand why it gets reset, however I'm not sure if it makes sense to have the behaviour. What was the reasoning behind resetting the inputValue onBlur?
The example seems to be behaving the exact same way as the @riax's Issue. 

Nice work with the library thought, really helped that autocomplete behaviour.

**Comment by kentcdodds** [comment]
Glad you got it worked out :)

**Comment by epeli** [comment]
I was looking for the same thing and I came here from Google but it seems that the preventDefault() solution does not work anymore in 3.2.10.

But it is also preventable using the state reducer:

```tsx
         stateReducer={(state, changes) => {
                // Do not clear search input content on blur
                if (changes.type === Downshift.stateChangeTypes.blurInput) {
                    return state;
                }

                return { ...state, ...changes };
            }}
```
