### ISSUE TITLE
Broken links in contributor notification email.

### ISSUE THREAD

**Issue by boykoc** [paypal/downshift#292]
* `downshift` version: Master?
* `node` version: N/A
* `npm` (or `yarn`) version: N/A

Relevant code or config

`N/A`

What you did:

Made a commit, did not add myself as a contributor, received notification emails regarding the PR, merging and adding myself as a contributor, and tried to click the links in the email.

What happened:

After submitting a Pull Request I received the typical automated email notifications. **The last notification regarding adding myself as a contributor** said _"Would you like to [add yourself](http://../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](http://../#contributors)?"_.
However, these links are incomplete and show a redirect notice page:

_"Redirect Notice
The page you were on is trying to send you to an invalid URL (http://../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor).
If you do not want to visit that page, you can [return to the previous page](https://www.google.com/url?hl=en&q=http://../blob/master/CONTRIBUTING.md%23add-yourself-as-a-contributor&source=gmail&ust=1514036479347000&usg=AFQjCNHi1z6nEEPlzQ_SONg7cnuaIVDVBg#)."_

Reproduction repository:

N/A - I believe this is a build setting/configuration or githook but I am unable to locate where it is. I have looked at the follow places to see if I could find the config setting:

* downshift repo
* the contributor package repo
* kcd-scripts repo  

Problem description:

See the above "What happened" section.

Suggested solution:

Update config url for this notification to use an absolute path maybe.

**Comment by kentcdodds** [comment]
Hi! Thanks for reporting this.

It wasn't a bot. It was really me. But I use it so often that I have a GitHub "Saved Reply" for it.

<img width="339" alt="screen shot 2017-12-22 at 3 57 46 pm" src="https://user-images.githubusercontent.com/1500684/34314427-df8a880c-e730-11e7-91b5-8f18780cd340.png">

I know that it only works when you're on github.com. I have a LOT of repositories that I use that saved reply for, so making it an absolute path isn't reasonable. So I figure it's fine as is, despite this limitation.

Thanks anyway!
