### ISSUE TITLE
getRootProps refKey error only shows up on production build

### ISSUE THREAD

**Issue by tiansijie** [paypal/downshift#294]
* `downshift` version: 1.22.5
* `node` version: 8.9.2
* `npm` (or `yarn`) version: 5.5.1

Relevant code or config

https://codesandbox.io/s/y320wwj4z

What you did: 
I am using one of the example on your repo as an example. When I run this code under development, it's totally fine. But when I run a production build of it, it shows up the error.

What happened: 
production build shows up error 
`You must apply the ref prop "ref" from getRootProps onto your root element`
<img width="730" alt="screen shot 2018-01-03 at 8 51 11 pm" src="https://user-images.githubusercontent.com/3675602/34547263-eb7286c4-f0c7-11e7-8761-337c02ba4c6f.png">

Reproduction repository:

Problem description:

Suggested solution:
https://github.com/paypal/downshift/blob/master/src/downshift.js#L906
here we are using the `hasOwnProperty` to check if `ref` is exist or not. But somehow on development build of React, ref is exist but with a `undefined` value. Therefore, this check is skipped. Maybe we can do a simple check as like this 
```js
if (!getElementProps(element)[refKey]) {
...
}
```

**Comment by kentcdodds** [comment]
Thanks for finding this issue! I like your solution. Feel free to [make a pull request](http://makeapullrequest.com/) to implement this! Thanks so much!
