### ISSUE TITLE
Example for integration with redux-form

### ISSUE THREAD

**Issue by moimael** [paypal/downshift#297]
* `downshift` version: 1.22.5
* `node` version: 8.9.4
* `npm` (or `yarn`) version: 5.6.0

Problem description:

I'm trying to integrate Downshift with redux-form. Right now when selecting an item, redux-form get the full object, so my input displays `[Object: object]`

Suggested solution:

Add an example in the repo on how to integrate with redux-form

**Comment by moimael** [comment]
Thanks ! I actually implemented the itemToString function but it doesn't seems to be called before passing the payload to redux-form. Redux form gets the full object instead.

**Comment by moimael** [comment]
I actually managed to display the right thing by overriding the item prop in getItemProps, but then how do i get the id of the selected item ? Because now it's only storing the text value. I'd need something similar to the way the select input works so I get the id and the value of the selected item in the autocomplete.

**Comment by kentcdodds** [comment]
Could you make what you have so far in a codesandbox.io ? You could start with kcd.im/ds-example

That would really help.

**Comment by donysukardi** [comment]
@moimael 

I added a simple redux-form integration example with list of strings to the list of examples https://codesandbox.io/s/k594964z13.

As for your use case, you can check https://codesandbox.io/s/pm4zrq97vj.
`onStateChange` is only required if you're making a typeahead/autocomplete component. Otherwise if it's a select component, `onChange` alone should suffice.

```
const DownShiftInput = ({ input, meta, label, items }) => (
  <Downshift
    onChange={selectedItem => input.onChange(selectedItem.value)}
    onStateChange={({ inputValue }) => input.onChange(inputValue)}
    itemToString={item => (item ? item.value : "")}
  >
```

**Comment by moimael** [comment]
I ended up doing something like this: https://codesandbox.io/s/7yrrjv4396
The only issue i still have is when I use it with apollo, then the field is rerendered when I select an item in the liust and it clears the text in the input. Because I need to store the id of the selectedItem in redux-form and display the text. Still haven't figured out how to do this.

**Comment by donysukardi** [comment]
You need to bind back the redux-form's value from `input.value` back to `selectedItem` on your Downshift component to make it a controlled component. Otherwise the text that you see in the input textbox comes from Downshift's internal state.

**Comment by ssilve1989** [comment]
@donysukardi In your example when the field loses focus, a change event with an `undefined` payload gets triggered. This doesn't overwrite the value in the form state, but doesn't look like it should be happening? 

I modified the sandbox to use `redux-logger` so you can see. Put some text in, click outside the field, observe undefined payload.

https://codesandbox.io/s/6zxk83jwn3

**Comment by brenoos** [comment]
> You need to bind back the redux-form's value from `input.value` back to `selectedItem` on your Downshift component to make it a controlled component. Otherwise the text that you see in the input textbox comes from Downshift's internal state.

Hello.

Can you please show how can I made this?

Thanks
