### ISSUE TITLE
Focus not reapplied to input when an item is selected with the mouse

### ISSUE THREAD

**Issue by MarkFalconbridge** [paypal/downshift#301]
* `downshift` version: 1.3

What you did:

Using the example [here](https://codesandbox.io/s/zx1kj58npl), open the drop down and select an item with the mouse, once selection has happened, focus should go back to the input element but it doesn't. Focus does go back to the input element if you use the keyboard (actually I suspect it never leaves the input) to select an item so mouse selection should do the same.

What happened:

Focus isn't returned to the input.

It is very easy to work around this by handling the onSelect prop but I had expected this to be taken care of by default.

**Comment by kentcdodds** [comment]
Yes, I agree this should be handled by default. Would you like to [make a pull request](http://makeapullrequest.com)?

**Comment by donysukardi** [comment]
But the expected behavior when using keyboard and mouse should be slightly different.

If user clicks the arrow button to open the dropdown and make a selection, I'm not entirely sure if user actually expects the input to get focus (and opens up the keyboard on mobile).

**Comment by kentcdodds** [comment]
I think that if the user's using the mouse they don't care where the focus goes after they click an item. Makes just as much sense for it to go to the input as the body (which is where it would go otherwise).
