### ISSUE TITLE
Input field examples

### ISSUE THREAD

**Issue by mshaw-nm** [paypal/downshift#303]
* `downshift` version: 1.23.2
* `node` version:
* `npm` (or `yarn`) version:

Are there any examples where we need to have some more control over the input field or where the control functions like react-select.

A few things that I'm trying to achieve that I'm not able to figure out from the examples/documentation. 

The input field should already be populated with a value when the control is first shown. When the user clicks in the input field, I would like the menu to open, the existing text/value should be removed and the cursor placed at the beginning of the input for the user to filter the full list. If the user cancels after typing some text, the existing value still stays, if the user types then the list filters. 

I am able to get the list to open when the user clicks the input field, however when I try to pre-populate a value using the inputValue prop, I can no longer do anything in the input field.

Any ideas/examples on how to achieve something like this?

**Comment by kentcdodds** [comment]
Hi @mshaw-nm!

Maybe someone could help build an example for you. If I'm able to find the time then I'll do it myself.

The basics of what you want is to control the `inputValue` and use `onStateChange` to decide when to update your `inputValue` state. See the docs in the README about control props.

Hopefully it provides some assurance that what you're describing is totally possible with downshift without any weird hacks 👍

**Comment by mshaw-nm** [comment]
ok, I believe I have most of what I'm looking for, but I'm experiencing one issue that I can't resolve, whenever I type into the input field (i.e. John). I am able to delete all the characters except for the J.

this is my onStagechange handler
```
handleStateChange = changes => {
        if (changes.isOpen) {
            this.setState({ inputValue: '' });
        }
        return changes.inputValue && this.setState({ inputValue: changes.inputValue });
};

**Comment by kentcdodds** [comment]
That's a falsyness issue with JavaScript because `changes.inputValue` would be `''` in that case. Try this instead:

```javascript
handleStateChange = changes => {
  if (changes.hasOwnProperty('isOpen')) {
    this.setState({ inputValue: '' });
  }
  if (changes.hasOwnProperty('inputValue')) {
    this.setState({ inputValue: changes.inputValue })
  }
};
```

**Comment by mshaw-nm** [comment]
that did it thanks

**Comment by kentcdodds** [comment]
Awesome! Would you like to give back by making an example for the README? :)

**Comment by mshaw-nm** [comment]
Sure, I would have to clean up the example that I have since it was for a work project.

**Comment by JofArnold** [comment]
Just stumbled over this question when I was trying to figure out how I'm managed to get the parent and Downshift's state out of sync.

Here's an example https://codesandbox.io/s/4879rjw289

And here's the important bits of the code if you can't access codesandbox:

```
class TypeAhead extends React.Component {
  state = {
    isOpen: false,
    selectedItem: null,
    inputValue: "",
    highlightedIndex: null,
  }

  render() {
    return (
      <div>
        {this.state.inputValue != "" &&
          `Selected Fruit: ${this.state.inputValue}`}
        <Downshift
          onStateChange={state => this.setState({state})}
          onChange={selection => alert(`You selected ${selection}`)}
          {...this.state.state}
        >
```

**The important bit:** Downshift tests props against `!== undefined` so for every value you want to be controlled, to avoid sync issues you must define their initial state as something other than `undefined` eg `null`

Hope that helps someone.

**Comment by JofArnold** [comment]
Opinionated side-note: if you're going controlled I recommend you only use `onStateChange` and completely take control of Downshift's internal state. I've saved myself a lot of headaches this way. For instance, if you want to clear a selection you'll need to clear all of `selectedItem`, `inputValue`, `highlightedIndex` or the next time you type Downshift may end up reverting to internal state for `selectedItem` and the result will be confusing.

**Comment by kentcdodds** [comment]
Feel free to make a PR to add an example. I'm going to go ahead and close this for inactivity for now. Thanks!
