### ISSUE TITLE
onOuterClick only fired when isOpen is true

### ISSUE THREAD

**Issue by natenorberg** [paypal/downshift#311]
This is more a question than a bug, but it looks like `onOuterClick` isn't fired if the menu has been closed already. It looks like this is explicitly checked for but I wasn't sure why.

https://github.com/paypal/downshift/blob/master/src/downshift.js#L812

* `downshift` version: 1.22.5
* `node` version: 8.9.4
* `yarn` version: 1.3.2

Relevant code or config

```javascript
<Downshift
  onChange={this.handleChange}
  selectedItem={value}
  inputValue={this.state.inputValue}
  itemToString={i => (i ? i.label : '')}
  onOuterClick={this.resetToSelectedValue}
  render={downshift => (
    <div>
      {this.renderLabel(downshift)}
      {this.renderInput(downshift)}
      {!disabled && this.renderPopup(downshift)}
    </div>
  )}
/>
```

What you did:
1. Focus the field and search for something
2. Click a button that calls `toggleMenu` to close it
3. Click away from the field

What happened:

`onOuterClick` is not called.

Suggested solution:

I could add a note to the docs for `onOuterClick` if we can't get rid of the `isOpen` check

**Comment by kentcdodds** [comment]
Yes, let's add a note to the docs. `onOuterClick` is for a very specific use case (which can actually be accomplished other ways) and I don't want to put much more work into it to make it more general.

Thanks @natenorberg!

**Comment by natenorberg** [comment]
That makes sense, it was easy to work around. Added a note to the docs in #312

**Comment by kentcdodds** [comment]
Thanks @natenorberg!
