### ISSUE TITLE
Downshift content won't open when there's autoFocused component inside {isOpen} logic

### ISSUE THREAD

**Issue by philipyoungg** [paypal/downshift#318]
* `downshift` version: 1.26.1
* `node` version: 8.9.1
* `npm` (or `yarn`) version: 1.3.2

Relevant code or config

```javascript
const App = () => (
  <form>
    <Downshift>
      {({isOpen, getButtonProps, getInputProps}) => (
        <div>
          <button {...getButtonProps()}>
            ay
          </button>
          {isOpen &&
            <div>
              <input type='text' {...getInputProps()} autoFocus /> // autoFocus is the issue
              <div>content</div>
            </div>
          }
        </div>
      )}
    </Downshift>
  </form>
);
```

What you did: 
> Content won't open because there's a `onBlur` event on button introduced on https://github.com/paypal/downshift/pull/314.
> - When button clicked, it's focused
> - It opened input which is autofocused. 
> - …which triggers `onBlur` event: this make the dropdown toggled back to close.

Reproduction repository: 
> https://codesandbox.io/s/pwn92r9plx

Problem description:
> I implemented UX similar to below on client project. Updating from 1.16.1 to 1.21.1 breaks this.
To make it easier for user, I autofocused on the input when the dropdown button is clicked
![onblur](https://user-images.githubusercontent.com/11477718/35558269-2e732cfe-05da-11e8-93e1-60244c3d9d1d.gif)

Suggested solution:
Honestly, I'm lost. 
- Maybe a props called `defaultOnBlurButtonEnabled` might help?
- Or (which is more dirty)—automatically disable the event when there's no `<input />` element present. Not sure if this possible or even make sense.

Anyway, I don't know if my use case is general enough for this to be implemented. I can stay of `1.16` if it didn't :)

**Comment by notruth** [comment]
Oh. @philipyoungg, It's not **Button->onBlur** fault.
Same problem with [Button into Input](https://codesandbox.io/s/8xo2y6xw28) too;
The fact is that any Downshift-operated element(with getButtonProps or getInputProps) inside the another element(with getButtonProps or getInputProps) will be cause conflict. It looks like antiPattern...
In Your case, the Button needs to be handled manually i think(Like **onClick, onFocus -> .openMenu()**)

**Comment by philipyoungg** [comment]
`getButtonProps` and `getInputProps` are sibling here https://codesandbox.io/s/pwn92r9plx

`onClick` and `onFocus` is a great idea! But I do need the `getButtonProps` to get `aria-...` and other accessibility tags right?

**Comment by notruth** [comment]
Oh, sure. Then You can do like: [https://codesandbox.io/s/4jw91lynyw](https://codesandbox.io/s/4jw91lynyw)

**Comment by philipyoungg** [comment]
@notruth dude, why I didn't think of that -_-

Thanks for the help these past 2 days!
