### ISSUE TITLE
"closeOnSelection" property(Multiple selection out of box)

### ISSUE THREAD

**Issue by notruth** [paypal/downshift#319]
I want to propose new Prop named `closeOnSelection`.

What happened, Problem description:
[This codesandbox-example](https://codesandbox.io/s/y0oo25o591)([Your Multi-select example](https://codesandbox.io/s/W6gyJ30kn) with latest Downshift version) contains hardcoded solution: Menu doesn't close(as it were), it open after close. Because of this, the `highlightedIndex` is reset; as well as existence of a lot of handlers that just control the state of `isOpen`.

Suggested solution:

```javascript
  defaultProps = {
    // ...
    closeOnSelection: true,
    // ...
  }
  
  selectItem = (item, otherStateToSet, cb) => {
    otherStateToSet = pickState(otherStateToSet)
    this.internalSetState(
      {
        ...this.props.closeOnSelection
          ? {
              isOpen: false,
              highlightedIndex: this.props.defaultHighlightedIndex, 
            }
          : {},
        selectedItem: item,
        inputValue:
          this.isControlledProp('selectedItem') &&
          this.props.breakingChanges.resetInputOnSelection
            ? this.props.defaultInputValue
            : this.props.itemToString(item),
        ...otherStateToSet,
      },
      (...args) => {
        this.focusInput()
        typeof cb === 'function' && cb(...args)
      },
    )
  }
```

**!NOTE:** At now this will work fine only for the case with `Input` element, because it's [focusing after select]( https://github.com/paypal/downshift/blob/master/src/downshift.js#L296).

**Comment by kentcdodds** [comment]
Seems like a good idea!

What if we made the solution more powerful. What if we added a prop called `modifyStateChange` and we put it [here](https://github.com/paypal/downshift/blob/e4846d86544a9a23ed05d8573ee9d6f5eb0ca054/src/downshift.js#L347):

```js
stateToSet = this.props.modifyStateChange(stateToSet, state)
```

Where the default would simply return `stateToSet` but you could provide your own function that could modify the state that will be set. You could check the `type` property of `stateToSet` against [this list](https://github.com/paypal/downshift/blob/e4846d86544a9a23ed05d8573ee9d6f5eb0ca054/src/downshift.js#L109-L124) to know whether you want to modify how the state is changed.

This would actually allow people to not have to control state quite as much I think which would be pretty handy!

What do you think?

**Comment by notruth** [comment]
@kentcdodds, Yeah! Looks great! i like this solution 👍, thanks.
And, the last important problem for me 😊  - its `.focusInput()`. I think, `focus`ing on Input element after reset - is bad pattern. What if we `focus` **last focused element BEFORE reset**? This will be flex solution.
Probably need to Cash this element...🤔
What do you think?

**Comment by kentcdodds** [comment]
> What if we focus last focused element BEFORE reset?

Yep, I love that :+1:

Would you like to work on both of those? They should be in different PRs I think :)

**Comment by notruth** [comment]
Yes, i can. Of course, different.
I'll start a little bit later(in 2-3 hours).
Thanks for support!

**Comment by kentcdodds** [comment]
Loving the ideas coming here. Thank you!
