### ISSUE TITLE
getButtonProps() returns different result locally and in production

### ISSUE THREAD

**Issue by HansWurst90** [paypal/downshift#322]
* `downshift` version: 1.22.5
* `node` version: 8.9.4
* `npm` version: 5.6.0

### Problem description:

In a project I am working on there is a discrepancy between the output of `getButtonProps()` when I run the project locally and when it is in production. The Element that is created with downshift has `"type": "button"` when in production but when it is run locally it does not have that property.

### Relevant code or config
Output of `getButtonProps()`:

- local with `npm start`:

```javascript
{
  "role": "button",
  "aria-label": "open menu",
  "aria-expanded": false,
  "aria-haspopup": true
}
```

- built and deployed:

```javascript
{
  "type": "button",
  "role": "button",
  "aria-label": "open menu",
  "aria-expanded": false,
  "aria-haspopup": true
}
```

Do you have any hints where I could start looking for the root of that problem?

**Comment by kentcdodds** [comment]
Hi @HansWurst90!

Make sure that you're using the same version locally that you are in production. A recent release added `type: "button"`.

I'm going to bet that's the issue. If  you want it to have a different type, then you can do: `getButtonProps({type: 'submit'})`

I'll go ahead and close this.

**Comment by HansWurst90** [comment]
> I'm going to bet that's the issue.

You won that bet 😄 . 

`getButtonProps({type: null})` helped me to get the same result as before.

Thanks a lot!

**Comment by kentcdodds** [comment]
Thanks! Sorry for the breaking change. I didn't expect anyone actually wanted the button to have a type of submit so I considered it a bug.
