### ISSUE TITLE
How to get selected object, not selected values?

### ISSUE THREAD

**Issue by futurfutur** [paypal/downshift#329]
Passing array of objects as **suggestions** array. In **onChange** function I get selected string value, how can I get the assosiated object?

**Comment by donysukardi** [comment]
Make sure you pass in your item object to `getItemProps`. Here's a sandbox example https://codesandbox.io/s/7jqv565mlj.

**Comment by futurfutur** [comment]
yep, with **itemToString** function works like a charm. Thanks a lot for a really quick and helpful response!

**Comment by donysukardi** [comment]
Awesome! You're most welcome 🏎
