### ISSUE TITLE
Add render prop parameter for opening via button

### ISSUE THREAD

**Issue by rhinoceraptor** [paypal/downshift#335]
Sorry if this has already been suggested, I searched for this and didn't find anything.

I'd like to propose an enhancement for ```isOpen```, by adding something like ```isOpenViaButton``` (or some other name). I'd like to be able to show all of my items if the user clicks the button, or filter by the input value if the menu is open via typing.

```isOpenViaButton``` would be set to true when the button is pressed, and then set to false whenever the input text changes.

* `downshift` version: 1.28
* `node` version: 8.9.4
* `npm` (or `yarn`) version: 5.6.0

For example:

```javascript
<Downshift
  render={({
    getButtonProps,
    getItemProps,
    getInputProps,
    inputValue,
    isOpen,
    isOpenViaButton
  }) => (
    <input {...getInputProps()} />
    <button {...getButtonProps()}>Show items</button>
    {isOpen ? items
      .filter(item => isOpenViaButton || item.includes(inputValue))
      .map(item => (
        <div {...getItemProps({ key: item, index, item })}>{item}</div>
      ))
    }
  )}
/>
```

**Comment by newyork-anthonyng** [comment]
@rhinoceraptor I think passing your own `isOpen` prop to `<Downshift />` and controlling it would get the desired effect you're looking for.

Take a look at this [CodeSandbox demo](https://codesandbox.io/s/vnkrqo8r4y). Notice how I passed in `onStateChange` and `isOpen` to `<Downshift />`.

Take a look at the docs about [Control Props](https://github.com/paypal/downshift#control-props) for more info.

**Comment by rhinoceraptor** [comment]
Yep, that's what I ended up doing, just adding some component state to set a flag on button click, and unset it on input change.
