### ISSUE TITLE
Does resetIdCounter() work?

### ISSUE THREAD

**Issue by jaredpalmer** [paypal/downshift#340]
Currently upgrading an app to React 16 and it seems that downshift is breaking hydration. To confirm, I was able to reproduce on a brand new Razzle app. 

See https://github.com/jaredpalmer/downshift-razzle-bug

Thoughts?

**Comment by notruth** [comment]
@jaredpalmer, hm... 🤨
It seems that `webpack`(under the hood of the `razzle`) uses same [`idCounter`](https://github.com/paypal/downshift/blob/master/src/utils.js#L1) on both(client and server) sides. And this happens only in DEV mode...

I don't know why this feature was added in Downshift, but the solution is to shove [this variable](https://github.com/paypal/downshift/blob/master/src/utils.js#L1) and relevant logics into the `Downshift` constructor scope(i think).

I recommend You to pass `ID`s manually, like:
javascript```
<input {...getInputProps({
  id: 'my-input-id',
  placeholder: 'Favorite fruit ?'
})} />
```
this solution is cleaner;)

**Comment by kentcdodds** [comment]
The feature is intended for server side rendering and there's actually an existing test for it. Not sure what is going on, but @notruth's workaround will work. You can also pass an ID prop to downshift directly.

But we should probably figure out what's going on 🤔

I won't have time to work on this myself though.

**Comment by notruth** [comment]
@kentcdodds, The problem is that `webpack` uses the same [`idCounter`](https://github.com/paypal/downshift/blob/master/src/utils.js#L1) on both(client and server) sides in DEV mode. In `razzle` DEV mode client and server sides works parallel, and `webpack`(core of `razzle`) uses the same module(`downshift/utils.js`) on both sides.

I can add a PR tomorrow with the relevant decision.

**Comment by notruth** [comment]
Simply put, the [`idCounter`](https://github.com/paypal/downshift/blob/master/src/utils.js#L1) variable shouldn't stick out. Because `webpack` uses the same variable address for both sides(If u increment it on server, it increments on client).

**Comment by notruth** [comment]
I found.

This(root) [`generateId()`](https://github.com/paypal/downshift/blob/master/src/downshift.js#L72) calls in Init time and `idCounter` right away rises to `2`.

On **server-side** after that we reset the `idCounter` to `0` every render time.
It means that others `generateId()`'s begin counting from `0`.
But on **client-side** others `generateId()`'s begin counting from `2`, because no reset occurs.

![](https://user-images.githubusercontent.com/4060187/36569418-b99fe938-17fb-11e8-972c-6a21eb527972.png)

### Solution:
* Set default `idCounter` to `0`(instead of `1`):
```javascript
let idCounter = 0
```
* And replace resetting logic with code below:
```javascript
/**
 * Resets idCounter to last idCounter value after init. Used for SSR.
 */
let idCounterAfterInit
function resetIdCounter() {
  if (idCounterAfterInit === void 0) {
    idCounterAfterInit = idCounter
  }

  idCounter = idCounterAfterInit
}
```

**Comment by kentcdodds** [comment]
That sounds fine to me! Thanks for researching that @notruth!

Two things:

1. Let's definitely add a brief code comment over the initialization of the `idCounterAfterInit` variable to explain what its purpose is because it seems nonsensical without some context.
2. Instead of `void 0` let's just use `undefined` :)

Thanks!

**Comment by notruth** [comment]
@kentcdodds, Thanks for review.
About `void 0` - sure.
But I prefer the first solution 'Migrate this generateId() into constructor() handler', it's more more semantic: render time = render id. What do you think?

**Comment by kentcdodds** [comment]
Oooh! I missed that! That's actually a bug! What it's currently doing is setting an id for _all_ instances of downshift, not each individual instance. Yes, we should definitely fix this. Except, I would remove the `defaultProp` for the `id` [here]() (that's the bug), and add `id = this.props.id || generateId('downshift')` above [this line](https://github.com/paypal/downshift/blob/a1bf4ddc8deb78f0099e95b3c65a43d0f25fc0f2/src/downshift.js#L134), then do as you suggested with `getItemId` :+1:

A PR would be appreciated for this. I wonder if there's any way we could add a test for this as well 🤔

**Comment by donysukardi** [comment]
Yeah. Looking at it, I think the first solution, i.e. moving `generateId` to constructor makes more sense.

**Comment by notruth** [comment]
@kentcdodds, @donysukardi, Thanks for approve.
About `test`: I'm think it will not be difficult. Just need to check that the `idCounter` value is equals to `0` after Downshift initialized...

**Comment by kentcdodds** [comment]
Cool, thanks all! I love working on downshift with you fine folks!

**Comment by kentcdodds** [comment]
Note: we do currently have tests for SSR: https://github.com/paypal/downshift/blob/master/other/ssr/__tests__/index.js

If you could update those to catch this that would probably be best 👌

**Comment by kentcdodds** [comment]
Though now that I think about this, I'm not sure that'd be the right place for it. 🤔 Whatever you think is best

**Comment by notruth** [comment]
Yeah, probably it's better to do a separate test for this...

**Comment by jaredpalmer** [comment]
@kentcdodds confirmed workaround is just passing an `id` to `getInputProps()` and removing `resetIdCounter()`. 

2 Questions:

- From a DX perspective, I was surprised that downshift needed special SSR consideration. What do you think about about calling this out bit earlier in the documentation?  
- How do you feel about making `id` required in `getInputProps()` in the interim? (At minimum in TS types and perhaps by explicitly by using `invariant()` or an assertion)?

**Comment by kentcdodds** [comment]
> What do you think about about calling this out a bit earlier in the documentation?

We do have this mentioned in [the FAQ](https://github.com/paypal/downshift/blob/748d0f338b41f2e5d23ee18f5f6811175ea9f408/README.md#faq). I suppose we could mention it earlier. Or perhaps we could add an entire section to the docs about server side rendering. That way it would appear in the table of contents. Would you like to do that?

> How do you feel about making id required in getInputProps() in the interim? (At minimum in TS types and perhaps by explicitly by using invariant() or an assertion)?

Nope, sorry. 99% of use cases for downshift (more?) don't require SSR. I'm not going to put pain on 99% of users to make the DX of 1% of users _slightly_ better. The `id` is _not_ required, except for SSR.

Perhaps we could make this happen if you're rendering downshift on the server (no `window` object or something). I would rather have a warning logged though I think. Thoughts?

**Comment by jaredpalmer** [comment]
@kentcdodds a warning if window is undefined is a great idea

**Comment by kentcdodds** [comment]
Cool! Let's do it. Who wants to give it a go?!

**Comment by donysukardi** [comment]
That didn’t quite address the actual issue with the mismatch as @notruth pointed out. I think once we resolve that, providing id is no longer necessary.

@jaredpalmer, to answer your first question, it’s quite a common approach to reset auto generated counter (in this case the id). A similar approach is also used by
https://github.com/reactjs/react-tabs/blob/master/README.md#resetidcounter-void.

**Comment by donysukardi** [comment]
This should be working as intended with `downshift@1.28.2` now. No explicit id is required 🎉

**Comment by kentcdodds** [comment]
Thanks!
