### ISSUE TITLE
itemToString warning under certain circumstances

### ISSUE THREAD

**Issue by austintackaberry** [paypal/downshift#342]
* `downshift` version: 1.22.3
* `node` version: codesandbox
* `npm` (or `yarn`) version: codesandbox

**Relevant code or config**

[simple downshift example](https://codesandbox.io/s/6z67jvklw3)
![image](https://user-images.githubusercontent.com/29493001/36579667-23c0d5f8-1819-11e8-96be-dda6fdb9b315.png)

**What you did:** 

IF you type/delete a letter AND:

- the autocomplete menu is open
- there is only one item in the menu before you type/delete the letter
- that item is the only item in the menu after you type/delete the letter
- that item is not highlighted

In the above example: each time you change the input value between 'app' and 'appl'...

**What happened:**

THEN: You get the following warning:
```javascript
"downshift: An object was passed to the default implementation of `itemToString`. You should probably provide your own `itemToString` implementation. Please refer to the `itemToString` API documentation."
"The object that was passed:"
Object {}
```

**Suggested solution:**

Not sure yet, but I would like to work on this if this isn't already being worked!

**Comment by kentcdodds** [comment]
Here's the problem:

https://github.com/paypal/downshift/blob/748d0f338b41f2e5d23ee18f5f6811175ea9f408/src/downshift.js#L796

This gets passed to `itemToString` and causes the error. So the solution would be to just remove `|| {}`. I'm pretty sure there shouldn't be any problems with that. Thoughts?

**Comment by austintackaberry** [comment]
Ah, I thought it was that line, but I couldn't tell if it was ever passed to itemToString. I'll look into it a little bit more and make a PR!
