### ISSUE TITLE
Selecting text in the input can lead to reset()

### ISSUE THREAD

**Issue by jduthon** [paypal/downshift#350]
* `downshift` version: 1.27.1
* `node` version: 8
* `npm` version: 5.5.1
(But I believe all versions are concerned)

When clicking to select the text from the input that `downshift` controls, if you end the selection outside of the input it can end up resetting the input to the `selectedItem` value, while the user is actually trying to interact with the input and select the full text to replace it.

It is reproducible on the simplest version of downshift from the examples in this repo : https://codesandbox.io/s/6z67jvklw3

Steps to reproduce are the following : 
1. Type and select `banana`
2. Change `banana`to `bana`
3. Click on the input, slightly to the right of `bana` (so not directly on the text)
4. Select the full text, and end the text selection outside of input
The input is reset to `banana`, whereas you were trying to edit it.

(If this description is not perfectly clear, which I assume could be the case, I may do a video to demonstrate this, feel free to ask)

The problem clearly comes from https://github.com/paypal/downshift/blob/master/src/downshift.js#L832 

Suggested solution:
I believe a check could be added to know if the `mouseDown` event happened on the input, if it's the case downshift should not reset.
I tend to believe though that this reset on outerClick is not necessarily useful, as `downshift` is already resetting `onBlur` and I cannot see any use case right now where `outerClick` will happen, but not `onBlur`, except the one from this bug.

**Comment by austintackaberry** [comment]
When you say 

> 3. Click on the input, slightly to the right of banana (so not directly on the text)

At this point, shouldn't the input value be "bana" not "banana"? Also, when I click on the input slightly to the right of "bana", nothing happens. I only see the behavior you describe onBlur.

**Comment by jduthon** [comment]
@austintackaberry yes absolutely correct, sorry. I will edit

**Comment by austintackaberry** [comment]
I was able to reproduce this issue with your version and the latest version of downshift. As you mentioned, this is clearly a bug.

I like your suggested solutions; however, it looks to me like the onBlur is a button prop not an input prop:
https://github.com/paypal/downshift/blob/1dec961ad5e787ad29556c85afe8ddc8bb05968f/src/downshift.js#L543

**Comment by jduthon** [comment]
Good (kind of haha).
Well let's wait a bit to have an opinion on how to fix it better.
I wouldn't mind doing it as soon as we know which way to go.

**Comment by austintackaberry** [comment]
I could be wrong, but it seems like onOuterClick doesn't actually do anything by default. It is only there to allow the user the opportunity to customize an onOuterClick function. Whereas onBlur has functionality and cannot be customized.

I agree that the issue is with the line you linked. Since all the action is triggered on `mouseUp`, you would need to find a way for that function to know what element was clicked on. Is there a better solution than adding additional state?

**Comment by jduthon** [comment]
@austintackaberry the problem is effectively not with the `onOuterClick` directly, I expressed myself wrongly I believe.
The problem is that at the line I pointed, `downshift` is also doing a `reset` of the state. (and then calling the `onOuterClick` prop, so I meant more the idea of clicking outside, not the `onOuterClick` prop).

And I believed you can actually customize the `onBlur` by passing your own `onBlur` function to `getInputProps()`, or am I mistaken?

**Comment by austintackaberry** [comment]
Sorry, yes. The reason you would have both is if you wanted to customize `onBlur` to have different behavior than `onOuterClick`.

What do you think about removing `isMouseDown` from the state and replacing it with something like `mouseDownOnElement` and setting it equal to `event.target` `onMouseDown`? And then `onMouseUp` you could check if `mouseDownOnElement` is the input element. Then at the end of the function just set it equal to something falsy. Thoughts?

**Comment by jduthon** [comment]
I was thinking of something similar, even though I would personally go with a `onMouseDown` on the `input` and `items`, so the `isMouseDown` would still be useful as a `boolean`, maybe rename it to `wasInnerMouseDown`. And then just check if `wasInnerMouseDown`, if it's `true` then just set it to `false` and that's it as the `mouseUp` is matching it, otherwise do what is done now :  reset the state and call `onOuterClick`.
Advantage of this one I believe is not to listen to all the `mouseDowns` but only the one we are actually interested in.

**Comment by austintackaberry** [comment]
Looks like we need to listen to all the `mouseDowns` anyways based on this comment:

https://github.com/paypal/downshift/blob/master/src/downshift.js#L817

**Comment by jduthon** [comment]
Hmmm but in the comment, the case where this is useful if is user clicked on an `item` no?
I was proposing to listen for `mouseDown` on `input` and `items` :)

**Comment by austintackaberry** [comment]
Ah, my bad. Sounds good to me!

**Comment by jduthon** [comment]
Awesome!
Should we wait for some more opinion(s) or do you think I can already go ahead with a PR?

**Comment by austintackaberry** [comment]
It might be good to wait. Thanks for opening this issue!

**Comment by kentcdodds** [comment]
Thanks @jduthon!

> I believe a check could be added to know if the mouseDown event happened on the input, if it's the case downshift should not reset.

I think this makes sense. Feel free to [make a pull request](http://makeapullrequest.com) for that :+1:

Thanks so much
