### ISSUE TITLE
Support `onChange` and `onChangeText` props for React Native

### ISSUE THREAD

**Issue by eliperkins** [paypal/downshift#361]
[After having some discussion around implementing a test suite for React Native](https://github.com/paypal/downshift/pull/328#discussion_r167035528), we realized there's some tweaks that we should make with regards to the `onChange` prop supplied to a `Downshift` component on React Native.

### Problem description:

The `onChange` prop is meant to emulate the prop of the same name that is used with `<input>` elements. On React Native, `<TextInput>` elements take in either `onChange` or `onChangeText`. The difference is that `onChange` sends an event, with the input value wrapped as part of the event, while `onChangeText` [sends only the input value](https://github.com/facebook/react-native/blob/6f007e8957c9bf5652b0184cba65f385050a8236/Libraries/Components/TextInput/TextInput.js#L925-L927).

Currently, Downshift will call `onChange` with the text input value, rather than an event object, which isn't super intuitive for React Native developers who are familiar with `<TextInput>`'s API.

### Suggested solution:

If we want to support what React Native developers would expect to supply as props here, we should support both `onChange` and `onChangeText` as values supplied to `getInputProps`.

This will likely mean checking for the existence of both keys as input to `getInputProps` when on React Native, and firing both/either `onChange` and/or `onChangeText` with the appropriate payloads, keeping Downshift's state in sync with the component.

**Comment by kentcdodds** [comment]
That solution sounds fine to me :+1: Don't worry about breaking changes because the React Native support is still currently experimental :+1:

**Comment by kentcdodds** [comment]
What's the status here? I feel like this is probably needed before we say react native is official (which will happen with downshift 2.0.0

**Comment by kentcdodds** [comment]
I might be publishing 2.0.0 this week. What are the chances we can make this happen by then?
