### ISSUE TITLE
Space keyDown to toggle menu can't be used without resetting input

### ISSUE THREAD

**Issue by austintackaberry** [paypal/downshift#364]
* `downshift` version: v1.29.1

Relevant code or config

https://github.com/paypal/downshift/blob/68499b42eff38474947e55e9ea636a340984608e/src/downshift.js#L681-L685

**What you did and what happened:**

https://codesandbox.io/s/vv3km9z9m5

![undefined](https://user-images.githubusercontent.com/29493001/37124186-0ff2fd1e-221c-11e8-8b84-cf16aed6b5da.gif)

**Problem description:**

Using default behavior, the user cannot toggle the menu using only the keyboard without resetting the input

**Suggested solution:**

Don't reset the input onBlur by default if the activeElement is a downshift button?

**Comment by austintackaberry** [comment]
Thoughts anyone??

**Comment by kentcdodds** [comment]
Thanks for bringing this up @austintackaberry. I like your suggested solution :+1:

Anyone can feel free to open a PR to fix this behavior. Please include tests! (Perhaps a Cypress test would be best for this one).

**Comment by austintackaberry** [comment]
Thanks, I'll give it a try!

**Comment by kentcdodds** [comment]
This was resolved :+1: thanks @austintackaberry
