### ISSUE TITLE
this._rootNode ends up being null, causing `cannot read property 'contains' of null` errors

### ISSUE THREAD

**Issue by petetnt** [paypal/downshift#366]
* `downshift` version: ^1.10.1
* `node` version: 8.9.*
* `npm` (or `yarn`) version: 5.7.1

What you did:

Not sure why this happens, but sometimes under heavy load (for example on page load on a rather data heavy application) `this._rootNode` ends up being null which fails on the `mouseUp` handler

What happened:

```
Uncaught TypeError: Cannot read property 'contains' of null
    at onMouseUp (downshift.esm.js:780)
    at wrapped (build.umd.js:1306)
onMouseUp	@	downshift.esm.js:780
wrapped	@	build.umd.js:1306
```

Suggested solution:

I guess adding a `null` check in the lines below would be enough:

https://github.com/paypal/downshift/blob/68499b42eff38474947e55e9ea636a340984608e/src/downshift.js#L838-L843

```js
(event.target === this._rootNode || (this.rootNode && !this._rootNode.contains(event.target))
```

Not sure what the actual cause at this point is though 🤔

**Comment by kentcdodds** [comment]
Weird. So the real problem is that `this._rootNode` could ever be null. Could you figure out why it's ever null?

**Comment by petetnt** [comment]
At least I figured out what causes the error now, its not heavy load, it happens to me when I switch a (sub) route so that a certain `DownshiftInput` unmounts and then switch back so the route the error starts occurring.

I guess the issue is that the cleanup is not being called when it should, but I guess it could be an application error on my side too (the logic is rather complex there).

**Comment by kentcdodds** [comment]
Interesting. Well, I'm pretty sure that there's something else going on here. It would help if you could reproduce the issue here: http://kcd.im/ds-example then we can see whether a change within downshift is necessary.

**Comment by petetnt** [comment]
For sure! I'll see if I get down to the issue tomorrow!

**Comment by petetnt** [comment]
This is getting super weird: the issue only occurs if the route with Downshift is mounted on first render, but does not occur if its not.

Tried to replicate the issue in here https://codesandbox.io/s/q9ynk5rj89  (with something close to my setup, with `react router` and styled-components` to no avail.

**Comment by kentcdodds** [comment]
I think we can go ahead and do a `null` check. I'm fine with that :+1:

**Comment by petetnt** [comment]
FWIW I just started to dig around the issue again to check if the null-check fixes the issue properly and while it fixes the issue (as in Downshift works after the error), the `onMouseUp` handler still stays alive and gets called with the null rootNode.

I wish I could replicate this on some easier setup to get to the root cause.

**Comment by kentcdodds** [comment]
If you find anything concrete we can do please let me know. Thanks!
