### ISSUE TITLE
Component not working and its name is Unknown

### ISSUE THREAD

**Issue by titanve** [paypal/downshift#375]
* `downshift` version: 1.30.0
* `node` version: 8.9.1
* `npm` (or `yarn`) version: yarn v1.5.1

Relevant code or config

```javascript
```

What you did: moving from local server to production server

What happened:

![image](https://user-images.githubusercontent.com/4803351/37431330-f31c9024-27a2-11e8-850b-3096eb90a60b.png)

Reproduction repository:

Problem description: I moved from dev server (local) to production server (remote hostgator). I can write what I want to search, it receives the items to show on the selection list but it doesn't show the items so I can select the one I want.

Suggested solution:

**Comment by kentcdodds** [comment]
Hi @titanve,
I'm sorry this happened. I'm afraid there's not much we can do to help you unless you give use a reproduction. Please follow the issue template and create a reproduction or at least an example of your code in a codesandbox: http://kcd.im/ds-example

**Comment by titanve** [comment]
Hey Kent,

I'm sorry, the problem was my `itemToString` function

it's now fixed! Thanks! 😄
