### ISSUE TITLE
Add Label component

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#38]
Related to #36: One thing that you want for a11y is a `label` for your `input`. Normally this is done by putting an `id` on the `input` and a `for="the-id"` on a `label`. So we could expose a `Label` component that automatically hooks up with the `Input`. That could be nice because it could generate a random ID to label the input. If the user provides an `id` prop to the `Input`, then we use that.

**Comment by souporserious** [comment]
Would this make sense for Dropdowns? So you would use `<Label/>` with `<Menu/>` and `<Item/>`? I can work on this today by the way 😉

**Comment by kentcdodds** [comment]
Sounds great.

As an aside: normally I would like to avoid adding things to the API like this (because it can clearly be done on your own), but in the case of accessibility, I want to make the pit of success as wide as possible and I want autocompletes built with these primitives to be as accessible as possible.

**Comment by souporserious** [comment]
I just started implementing this and wondering if it's necessary now. A label could be used to either focus the `Input` or a `Button` which makes things a little more complex now. Since it's not terribly hard to hook up an `id` and `htmlFor` maybe we just mention this in the docs and show a simple example?

**Comment by nndung179** [comment]
It is more nice with material style. I will update label to my example

**Comment by souporserious** [comment]
After the recent API changes, do you think it would be helpful to add an `id` to controller state to make building labels super easy? Or we can just leave it up the user since all we'll really be doing is adding a unique id.

**Comment by kentcdodds** [comment]
Well the `label` would have a `for` assigned to the same thing that's the `id` that's applied to the `input` right? So we could generate a random ID per instance of the Autocomplete component and in `getInputProps` return that randomly generated ID. Then a `getLabelProps` that returns `htmlFor: 'the-random-id'`

Should be pretty simple and also widen the a11y pit of success.

**Comment by CMTegner** [comment]
>That could be nice because it could generate a random ID to label the input.

Note that this doesn't play well with SSR in React 15. Checksums are going away in v16, so eventually this won't be a problem :)

**Comment by bliitzkrieg** [comment]
@CMTegner is there a way around the checksum error?
