### ISSUE TITLE
Remove .default & .resetIdCounter from index.js

### ISSUE THREAD

**Issue by Andarist** [paypal/downshift#380]
Problem description:
Such static property assignments prevent tree-shaking (which is still relevant in case of `downshift` in case it gets imported by some some unused part of the code, i.e. some ui-kit library which index.js reexports bunch of stuff):

https://github.com/paypal/downshift/blob/d2df6ec05198609ec5abbbad92bdc91dcac3b8c9/src/index.js#L9-L10

Not mentioning that adding `.default` is not proper way of supporting a default import declaration. We've discussed this once here - https://github.com/kentcdodds/kcd-scripts/pull/28

Suggested solution:

1. Remove `.default` and use `exports: 'named'` in rollup.config.js or create a separate file for `cjs` that could wrap the original entry to provide `.default`
2. make `.resetIdCounter` a separate export and not a static property of `Downshift` class

**Comment by Andarist** [comment]
@kentcdodds if you specify which one of those:
- remove .default and use exports: 'named' in rollup.config.js
- create a separate file for cjs that could wrap the original entry to provide .default
would u like to have done, then I can work on this one - although not sure if I manage to do that before the weekend and I'm not sure how fast you'd like to release the new version

**Comment by kentcdodds** [comment]
No worries. This change is pretty easy to make so I'll go ahead and do it myself.

I'm going to do:

> remove .default and use exports: 'named' in rollup.config.js

Considering the `rollup.config.js` is already using `exports: 'named'` :+1:

**Comment by kentcdodds** [comment]
Fixed!
