### ISSUE TITLE
Rename `getButtonProps` to `getToggleButtonProps`

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#386]
Because `getButtonProps` is ambiguous.

I think I'll release this in 1.0.0 and just support both. Then I'll remove it in 2.0.0

**Comment by 50bbx** [comment]
I think that the alias is not working as expected. I'm using 1.31.1. When using this component

```jsx
import React from 'react'
import Downshift from 'downshift'

const ExampleComponent = ({
  options,
}) => (
  <Downshift
    onSelect={(selection, { closeMenu }) => {}}
    render={({
      getButtonProps,
      onToggleMenu,
      getItemProps
    }) => (
        <div
          {...getButtonProps({ onClick: onToggleMenu }) }
        >
            <div>
                {options
                  .map((item, index) => (
                    <div
                      key={item.value}
                      {...getItemProps({
                        item,
                        index,
                      }) }
                    >
                      {item.label}
                    </div>
                  ))
                }
            </div>
        </div>
    )}
  />
)

export default ExampleComponent
```

gives `getButtonProps is not a function` error. Changing the function name to `getToggleButtonProps` resolve the issue. Is the breaking change happening in a minor? Or is the alias not working properly?

**Comment by donysukardi** [comment]
@50bbx You're right. The alias is not working properly. It was supposed to be a non breaking change (since there's aliasing). The issue is being tracked here - https://github.com/paypal/downshift/issues/387

**Comment by kentcdodds** [comment]
PR has been merged. I'm terribly sorry about my silly miss there. Normally I would have asked for a review, but I was working quickly and didn't want to wait. My bad :-/
