### ISSUE TITLE
getButtonProps is not a function

### ISSUE THREAD

**Issue by gsimone** [paypal/downshift#387]
As of version v1.31.1 we get `getButtonProps is not a function`.
There supposedly is an alias since the change tonight to `getToggleButtonProps`, but something is not working as expected, looking through the code right now, will update if I find the problem.

**Comment by donysukardi** [comment]
The aliasing wasn’t not done properly (ref to Line 552) as the getButtonProps don’t get passed down along with getToggleButtonProps to the render function.

This change was introduced as minor patch and need to be rectified as soon as possible.

Would you like to makeapullrequest.com @gsimone?

**Comment by gsimone** [comment]
Working on the PR @donysukardi

**Comment by kentcdodds** [comment]
I'm terribly sorry about that. Thank you for the quick PR!
