### ISSUE TITLE
[Typescript] Missing setItemCount & unsetItemCount action typings

### ISSUE THREAD

**Issue by ghost** [paypal/downshift#389]
* `downshift` version:   All since v1.22.0
* `node` version:   v8.9.4
* `npm` (or `yarn`) version:   npm v5.6.0 / yarn v1.5.1

**What you did:**
Tried using the `setItemCount` and/or `unsetItemCount` actions within a Typescript project.

**What happened:**
"Type 'ControllerStateAndHelpers' has no property 'setItemCount' and no string index signature".

**Problem description / Suggested solution:**
The typings file needs `setItemCount` and `unsetItemCount` added to the `Actions` interface signature:

```javascript
export interface Actions {
  ...
  setItemCount: (count: number) => void
  unsetItemCount: () => void
  ...
}
```

**Comment by stereobooster** [comment]
Hi @Sharakai. Do you want to do PR for this?

**Comment by Sharakai** [comment]
@stereobooster Happy to when I get home from work, but won't be until late night (~9pm UTC).

**Comment by stereobooster** [comment]
No need to rush. Team is across the globe. Somebody will handle it as soon as you do your PR.
