### ISSUE TITLE
[discussion] Issue with types

### ISSUE THREAD

**Issue by stereobooster** [paypal/downshift#400]
As of now supporting type signatures is manual and error prone process. Possible solutions:

1. Rewrite downshift in TypeScript or Flow. At build time compile source down to JS and type signatures.

- [TypeScript to Flow](https://github.com/stereobooster/type-o-rama#typescript-to-flow)
- [Flow to TypeScript](https://github.com/stereobooster/type-o-rama#flow-to-typescript)
- [JavaScript to TypeScript](https://github.com/stereobooster/type-o-rama#javascript-to-typescript)

2. Use some kind of type signature verifier, like [TSTools](http://www.brics.dk/tstools/#/) or [Property based testing](https://github.com/stereobooster/type-o-rama#property-based-testing). But those tools are pretty immature and/or tricky to use.

---

Also I need to say some of the functions are pretty hard to type, especially property "proxy" functions, like `getRootProps`, `getButtonProps` etc. Can we simplify those (this will be braking change)

Instead of

```js
<CustomListItem
  key={index}
  {...getItemProps({
    item,
    index,
    isSelected: selectedItem === item,
  })}
>
```

use this

```js
<CustomListItem
  key={index}
  {...getItemProps({
    item,
    index,
  })}
  isSelected={selectedItem === item}
>
```

**Comment by Antontelesh** [comment]
I support the intention, although it would be harder for people that are unfamiliar with TS/Flow to contribute to the project.

**Comment by kentcdodds** [comment]
Thanks for the issue @stereobooster.

At work I use flow for pretty much everything. But I've abstained from doing this in my OSS work because I'm worried about the barrier to contributors this would cause. I can understand the burden this puts on those (like yourself) maintaining the typings, but I think it's worth it.

**Comment by stereobooster** [comment]
There is also approach which puppeteer picked up - they use JS + TypeScript flavored JSDoc. It is possible to use TypeScript to verify those signatures, but [not possible to generate signature files based on it yet](https://github.com/Microsoft/TypeScript/issues/7546). Also [there are bunch of bugs in JSDoc implementation](https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+label%3A%22Domain%3A+JSDoc%22).

> I'm worried about the barrier to contributors this would cause

Is it really that much of barrier? I just wonder. Most of the time type signatures are trivial.

**Comment by kentcdodds** [comment]
If we do add types it'll be Flow, not TypeScript. There's also some comment support from flow.

Regardless, it _is_ a barrier for the uninitiated and I don't find it worth the barrier I'm afraid. So I don't think we'll do this.
