### ISSUE TITLE
IE11: Exception onBlur when next focused element is SVG

### ISSUE THREAD

**Issue by psachs21** [paypal/downshift#409]
* `downshift` version: 1.31.2
* `node` version: 8.9.1
* `npm` (or `yarn`) version: yarn 1.5.1

Relevant code or config

```javascript
input_handleBlur = () => {
    // Need setTimeout, so that when the user presses Tab, the activeElement is the next focused element, not the body element
    setTimeout(() => {
      const downshiftButtonIsActive =
        this.props.environment.document.activeElement.dataset.toggle &&
        (this._rootNode &&
          this._rootNode.contains(
            this.props.environment.document.activeElement,
          ))
      if (!this.isMouseDown && !downshiftButtonIsActive) {
        this.reset({type: Downshift.stateChangeTypes.blurInput})
      }
    })
  }
```

What you did:

Click the clear button (in IE11)

What happened:

```Unable to get property 'toggle' of undefined or null reference```

Reproduction repository:

```jsx
<Downshift>
  {({ getButtonProps, getInputProps, clearSelection }) =>(
    <div>
      <input {...getInputProps()}/>
      <div>
        <button onClick={clearSelection}>X</button>
        <svg>
           {/* some SVG here */}
        </svg>
      </div>
    </div>
  )
</Downshift>
```

Problem description:
dataset doesn't exist on svg elements in IE11.

Suggested solution:
Add additional check:

```js
const downshiftButtonIsActive =
  this.props.environment.document.activeElement.dataset &&
  this.props.environment.document.activeElement.dataset.toggle &&
    (this._rootNode &&
    this._rootNode.contains(
    his.props.environment.document.activeElement,
   ))
```

**Comment by kentcdodds** [comment]
Hmmm... Why is the `activeElement` the `svg` when you click the button though?

**Comment by psachs21** [comment]
Not 100% sure. It seems that IE11 considers SVG elements focusable by default. One fix I came up with was adding `focusable="false"` to the svg. That gets around the issue. If we're good with that, we can close this.

**Comment by kentcdodds** [comment]
I think I'm good with that as a workaround. If you could figure out why that ever gets set to the activeElement after you click the button though that's probably where the real problem lies. I'm fairly confident that it doesn't have anything do do with downshift though.

**Comment by psachs21** [comment]
Alright, thanks @kentcdodds

**Comment by kentcdodds** [comment]
Thanks @psachs21. If you come up with something else or discover there's a problem in downshift, please let us know and we can dig further!

**Comment by nathanforce** [comment]
Just ran into this one as well!  

Seems that `{ pointer-events: none; }` on the SVG will also fix.

**Comment by kentcdodds** [comment]
Yeah, I'm open to an extra check 👍 PRs welcome.

**Comment by nmchaves** [comment]
Today I saw this exception for an IE 11 user on our system:
```
TypeError: Unable to get property 'dataset' of undefined or null reference
  at fn(../../node_modules/downshift/dist/downshift.esm.js:855:1)
```
My team is using Downshift v3.2.0.

The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement#Value) explain that `activeElement` will be null if there is no focused element. The [current logic](https://github.com/downshift-js/downshift/blob/9fb1524a2d5f83db243001807cf890b0657aa8a6/src/downshift.js#L817) that resolved this issue doesn't test if `document.activeElement` is non-null. Unfortunately, I'm not exactly sure how the user got into this state, and I haven't been able to reproduce the issue myself. Based on our Sentry error report, it doesn't look like the user did anything unusual...I just haven't been able to reproduce it 😅. 

@kentcdodds would you be open to a PR with _another_ check to make sure that `activeElement` is non-null?

**Comment by kentcdodds** [comment]
I'm fine with extra null checks.
