### ISSUE TITLE
Contribute to Tests

### ISSUE THREAD

**Issue by zsid** [paypal/downshift#41]
Hi Kent,

If I want to contribute to tests, what will be the best way to start? Have you considered what functionality should be covered first and move to the next i.e. priority list?

**Comment by kentcdodds** [comment]
Thanks @zsid! If you don't mind I would like to be the one to start on testing. I have opinions about this and want to make sure I get this project going in the right direction before folks start contributing. I should be able to get to it within the next day or two.

**Comment by zsid** [comment]
Hey Kent, excellent. No rush, I just wanted to get your thoughts on it. Looking forward to your test commit 😃

**Comment by kentcdodds** [comment]
Let's leave it open :+1: Thanks!

**Comment by kentcdodds** [comment]
I'm finally going to start working on this. It's the last thing we need before our first release candidate :smile:

**Comment by kentcdodds** [comment]
We're at 81% code coverage now. Getting really close :tada:

```
+ downshift@1.0.0-beta.21
```

This is basically the release candidate :wink:

**Comment by the-simian** [comment]
Anything I can do to help on testing? I'll update my examples to v 1.0.0-beta.21

**Comment by kentcdodds** [comment]
No worries on helping with testing. I think it'll be easier to have me just push ahead on it. I should finish it this morning. Thanks!
