### ISSUE TITLE
items not listed under props in readme

### ISSUE THREAD

**Issue by SteveALee** [paypal/downshift#411]
Looking at latest README I don't see 'items' listed and documented though it is used in the example

**Comment by kentcdodds** [comment]
Hmm... Are you talking about the example in the usage section? The `items` are passed to the `BasicAutocomplete` component via the `App` component.

**Comment by SteveALee** [comment]
That's annoying - I can;t select lines when viewing a markdown file as I can for otehr files types :(

I mean 'items' is not listed in this section https://github.com/paypal/downshift/blob/master/README.md#props

surely it should be, even though is fairly obvious

**Comment by Antontelesh** [comment]
As far as I know, Downshift does not accept any `items`. It’s your custom component is up to use this prop. Or it can be named differently. It's up to you.

**Comment by SteveALee** [comment]
@Antontelesh oh, yes you are probably correct. I confused myself :) thanks

**Comment by Antontelesh** [comment]
You are welcome. This issue might be a sign that the example could be improved somehow

**Comment by SteveALee** [comment]
That's very good thinking in general :)
Alternatively just me being perverse as usual :-P
