### ISSUE TITLE
IE11: exeception when document.activeElement is not an HTML

### ISSUE THREAD

**Issue by blobor** [paypal/downshift#418]
* `downshift` version: 1.31.2
* browser:  IE11
* `yarn` version: 1.5.1

Problem description:
Sometimes getting an error (`TypeError · Unable to get property 'id' of undefined or null reference`) from this line https://github.com/paypal/downshift/blob/master/src/downshift.js#L583. Apparently in IE 11 `activeElement `can be null, so this line throws an error 😅.

Simplest solution whould be to check `activeElement != null`.

PS: I saw similar issue were open recently https://github.com/paypal/downshift/issues/409, but as I understood root cause of this exception is different.

**Comment by kentcdodds** [comment]
Ok, I think I'd be fine to do a null check in that if statement. Would you like to make a pull request for that?

```javascript
      if (
        !this.isMouseDown &&
        (!this.props.environment.document.activeElement ||
        this.props.environment.document.activeElement.id !== this.inputId)
      )
```

**Comment by blobor** [comment]
Sure, will throw a PR!
