### ISSUE TITLE
when selecting a item , it pushes they other grids column in my page .

### ISSUE THREAD

**Issue by damild15** [paypal/downshift#422]
Hi  if anybod can help me with this ,

Problem description:
when selecting a item on the menu , it pushes they other grids column in my page .
if i select another item it pushes gaing the they other grids column more further like giving them more width automatically, how to prevent that ? thanks for the help 

Suggested solution:

**Comment by austintackaberry** [comment]
Are you able to reproduce the issue in a [codesandbox](codesandbox.io)? I don't fully understand what you mean

**Comment by damild15** [comment]
yeah it was a problem with my form width , once i give it a fixed width , the chips stop over-floating , it fixed..
