### ISSUE TITLE
inputValue incorrectly initialized when selectedItem is 0

### ISSUE THREAD

**Issue by Brushedoctopus** [paypal/downshift#430]
* `downshift` version:1.31.7
* `node` version: 9.11.1
* `yarn` version: 1.3.2

Code example:
https://codesandbox.io/s/o4m0znror9
itemToString isn't called when selectedValue is 0. Setting selectedValue to 1 will call it.

Problem description:
When mounting a component with selectedValue as a falsy value (e.g. 0), inputValue is an empty string.

Suggested solution:
Change `if (state.selectedItem)` to `if (state.selectedItem != null)` in the Downshift constructor

**Comment by kentcdodds** [comment]
Hi @Brushedoctopus,

Thanks for this issue. Classic rookie mistake :sweat_smile: My bad. If you (or anyone else) could please [make that change](http://makeapullrequest.com/) I would be very grateful. I think it'd be great to include a simple test as well.

**Comment by tvthatsme** [comment]
@Brushedoctopus and @kentcdodds, I'd like to pick this up!

**Comment by austintackaberry** [comment]
Looks like @Brushedoctopus already submitted a PR. If you're looking for ways to contribute, I recommend "watch"ing the repository if you're not already!

**Comment by kentcdodds** [comment]
This was resolved and released. Thanks @Brushedoctopus!
