### ISSUE TITLE
button_handleClick setTimeout not triggered for Enzyme test

### ISSUE THREAD

**Issue by nicoxxie** [paypal/downshift#437]
* `downshift` version: 1.31.12
* `node` version: 8.x
* `npm` (or `yarn`) version: 6.x

Relevant code or config

What you did:

We have unit test that simulates a click and test the dropdown populates the right options.
```
enzymeWrapper.find('#randomButtonID').simulate('click');
```

What happened:

Our getToggleButtonProps passed in `onClick` function is working as designed but the button_handleClick fuction is not working right and isOpen state is never updated. https://github.com/paypal/downshift/blob/master/src/downshift.js#L548
```
onClick: composeEventHandlers(onClick, this.button_handleClick)
```

I debugged the latest few releases then found that the setTimeout function added 12 days ago is never triggered.  If I take the setTimeout out, the test will immediately pass. https://github.com/paypal/downshift/blob/master/src/downshift.js#L574
```
    setTimeout(() =>
      this.toggleMenu({type: Downshift.stateChangeTypes.clickButton}),
    )
```

Reproduction repository:

Problem description:

Since toggleMenu is never called, the isOpen state is always false and no drop-downs are populated in our unit test.  This has worked in v1.31.7 but fails after v1.31.9.

Suggested solution:

I did manage to bypass the test with mock timer setup, something like
```
    jest.useFakeTimers();
    enzymeWrapper.find('#randomButtonID').simulate('click');
    jest.runAllTimers();
    enzymeWrapper.update();
```
but is the setTimeout necessary? just to unit test a simple click do we have to always mock the timer?
I'm not familiar with ios blur or not sure why a setTimeout is needed in this case, maybe another solution https://codereview.stackexchange.com/questions/47889/alternative-to-setinterval-and-settimeout?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by kentcdodds** [comment]
Yeah, it's unfortunate that this was necessary and I'd love to come up with a different solution if possible. Do you know if `requestAnimationFrame` will really solve your problem?

If not, perhaps we could add an `if` check to not use the timeout if `process.env.NODE_ENV === 'test'` or something 🤔

**Comment by nicoxxie** [comment]
@kentcdodds Thank you for your reply.  I have not personally tried `requestAnimationFrame` as I'm not doing any ios development, wonder if someone here more knowledgable would know.

The if check might be a good idea.  Or if we can have a check to call only for ios/mobile? does `process.env.BUILD_REACT_NATIVE` do that job?

**Comment by kentcdodds** [comment]
I'm pretty certain that the original bug was ios mobile web, so `BUILD_REACT_NATIVE` wont work for that case. But I do feel like the `NODE_ENV` check would be acceptable. I'm 99% certain that I'd accept a PR for that :)

**Comment by nicoxxie** [comment]
Ok I will draft up a PR tomorrow, unless someone figure out an alternative in the next couple hours :)

**Comment by aMollusk** [comment]
I'll have a look around today and see if I can come up with a better solution.

If we can avoid this focus (in the click handler) triggering the blur event in mobile, then we can avoid the `setTimeout`. Just will require a bit of testing on different devices. Will let you know.

```
    if (
      this.props.environment.document.activeElement ===
      this.props.environment.document.body
    ) {
      event.target.focus()
    }
```

**Comment by kentcdodds** [comment]
@aMollusk, if you can get that to work that'd be swell. @nicoxxie made a PR which I just merged to resolve this using the `NODE_ENV` check. We can move to something better if that comes along :) Thanks!
