### ISSUE TITLE
double space after text results in a period

### ISSUE THREAD

**Issue by joshpitzalis** [paypal/downshift#438]
In the sandbox demo https://codesandbox.io/s/6z67jvklw3?from-embed if you start typing out a fruit and then enter two spaces it gives you a period. 

Is there a way to stop this. Or a way around this so that I can enter double spaces in my string?

**Comment by kentcdodds** [comment]
Hi @joshpitzalis, I'm pretty sure that must be a setting on your computer. Downshift doesn't do that. Look at your computer settings. Good luck!
