### ISSUE TITLE
Preact compatibility

### ISSUE THREAD

**Issue by zouhir** [paypal/downshift#44]
hey friends,

I've been trying to get this component to be compatible with `preact` by using a very thin compatibility layer instead of `preact-compat` module.

The final component renders fine in a pure preact project without compat but it hits a blocker on this line:

https://github.com/paypal/react-autocompletely/blob/master/src/menu.js#L132

would you be open to changing this single line from:
```
{children(this.autocomplete.getControllerStateAndHelpers())}
```
to something like:
```
React.Children.only(children)(  ..  )
```

if that's a possibility I think I should be able to complete the out of the box compat.

thanks!

**Comment by kentcdodds** [comment]
As long as it works with both and there's a comment explaining why then I say yes! Let's do it!

**Comment by nouh** [comment]
Test

**Comment by kentcdodds** [comment]
I'm going to close this in favor of #4 

Also, we have in fact switched to `React.Children.only(children)( .. )` :smile:
