### ISSUE TITLE
Toggle Menu on Focus

### ISSUE THREAD

**Issue by klapouchy** [paypal/downshift#442]
Is there a generic way to toggle menu when input field is on focus?

```javascript
onFocus={e => e.target.value == inputValue ? openMenu() : closeMenu()}
```

**Comment by kentcdodds** [comment]
As noted [in the docs](https://github.com/paypal/downshift#actions), there's a `toggleMenu` function you can call :)

**Comment by klapouchy** [comment]
@kentcdodds I missed it. However, I am still unsure how to call it from within `onFocus`.

**Comment by klapouchy** [comment]
@kentcdodds thanks! This leads to my next question. How to open the entire menu if an item is selected. 

Here is the behavior I am trying to achieve:

1. Typeahead show results
2. User selects one item
3. Next user clicks on the input 
4. The entire menu is shown with selected item (instead of just one item)
