### ISSUE TITLE
Input controll

### ISSUE THREAD

**Issue by VanillaWulf** [paypal/downshift#445]
`downshift` version: 5.6.0
`node` version: 10.0.0
`npm` (or `yarn`) version: npm

Hi, thanks for really comfortable component, but I have one question.

The problem: Not to reset the input with onBlur or onOuterclick, because I have my own validation for selections.

What I tried.
1. Try to make selectItem = inputvalue — but notice, that it make a request to data again.

2. Try to make my own onBlur and  onOuterclick with controlling state of openning( in my case Outerclick  didn`t work). 

But I am sure that it is suppose to be a better way of ignoring selectedItems

**Comment by kentcdodds** [comment]
Hi @VanillaWulf!

I'm pretty sure you can accomplish what you're trying to do with a `stateReducer`. Check out the README about that.

I'm going to go ahead and close this, but feel free to comment if you have further questions.
