### ISSUE TITLE
can items be an array of objects?

### ISSUE THREAD

**Issue by petercutting** [paypal/downshift#448]
The downshift examples tend to set items to an array of strings eg ["red","blue"]. These simple examples annoy me because they immeadiately block the developer from using them in a realistic scenario.

A realistic API call returns an array of objects (items) where each object has an attribute that will be displayed and an attribute that is a unique id (and other attributes). An example at this complexity would require less digging in the documentation. The documentaion sais very little about "items" even though it is one of the main downshift objects, and unfortunaltely it does not answer my question. 

So I tried anyway of course, but all I got is crashes. After a few hours, it is still not clear to me whether it should work or not. I would be a little disappointed if I had to reduce my array of objects to an array of strings

**Comment by kentcdodds** [comment]
Hi @petercutting,

This is a _very_ common question, so I've updated the example in the README. You need to use the `itemToString` prop. I hope that helps. Good luck!

**Comment by kentcdodds** [comment]
It's because that example is not using `match-sorter` properly for the data. Check out the `TypeAheadField.js` file and read the [`match-sorter`](https://github.com/kentcdodds/match-sorter) docs.

Good luck.
