### ISSUE TITLE
Add ability to get the target element from the onChange method

### ISSUE THREAD

**Issue by 9jaswag** [paypal/downshift#460]
To get more context on this issue, please check [here](https://github.com/paypal/downshift/issues/452#issuecomment-396423298)

Problem description: When using a single downshift component for multiple input fields on a page, one is unable to easily get the current input element being interracted with by the user. In my case, I had to write extra lines of code to get the target element

Suggested solution: A method that can be called and returns the current input element being interracted with. Here's how I was able to get it done with a few lines of code

```javascript
onChange(selectedItem, stateAndHelpers) {
    const element = document.querySelector(`#${stateAndHelpers.id}-input`)
  }
```

**Comment by kentcdodds** [comment]
Hi @9jaswag!
I don't think that we'll do this. Generally you shouldn't need access to the element itself and when you do you can [use a ref to do this](https://codesandbox.io/s/20x8plpm1r)

Thanks!
