### ISSUE TITLE
memory leak warning

### ISSUE THREAD

**Issue by stefanoferretti** [paypal/downshift#476]
- `downshift` version: 2.0.2
- `node` version: 9.11.1
- `npm` (or `yarn`) version: 1.7.0

Relevant code or config

See problem description

What you did:
Submitted a form with enter when focus is on the autocomplete component

What happened:
React warns that "Can't call setState (or forceUpdate) on an unmounted component"

Problem description:
Every time I submit a form when the focus is on a component that uses downshift and that component has the focus, if the component is unmounted after the submit (for example for a form in a dialog that's dismissed after submission), react warns that "Can't call setState (or forceUpdate) on an unmounted component"

Suggested solution:
setTimeout is used to manage blur events but is not cleared when the component is unmounted. When a form is submitted and unmounted after submission (for example a form in a dialog), this causes a memory leak.
I suggest to clear pending timeouts in componentWillUnmount

**Comment by kentcdodds** [comment]
> I suggest to clear pending timeouts in componentWillUnmount

I think that'd probably be best. We could have a `timeouts` instance property that's an array of all current timeouts, then iterate through and clear them in `componentWillUnmount`.

Alternatively, we could have an instance property called `_isMounted` that's a boolean, set it to `true` in `componentDidMount`, then set it to false in `componentWillUnmount`, and in our `internalSetState` method we could check `_isMounted` and return early if it's false.

I think that'd probably be the easiest. Thoughts? Anyone willing to implement this?
