### ISSUE TITLE
Clear Selection via an external button click

### ISSUE THREAD

**Issue by preraksola** [paypal/downshift#480]
- `downshift` version: 1.31.16
- `node` version: 8.11.12
- `npm` (or `yarn`) version: 5.6.0

What you did:
I have integrated downshift in a form in my react application to display a list of users fetched from an API. I have a button in this form, which is used to clear all the fields. 
However, I am not able to clear the autocomplete text field of Downshift upon clicking the button.

So, is there a way that I can use the `clearSelection` method in another function?  
If not, is there any other alternative?

Thank you.

**Comment by geeofree** [comment]
Hi! :wave: Perhaps we can make `Downshift` have a `ref` callback prop that gets called inside the `cDU` with `Downshift` as an argument to it? Something like this:

```js
class Downshift extends Component {
  // Downshift Stuff...
  componentDidMount() {
    const {ref} = this.props
    if (ref && typeof ref === 'function') {
      ref(this)
    }
  }
  // ...Other Downshift stuff
}
```

That way we can use `Downshift`'s various methods on stateful components like this:
```js
class MyForm extends Component {
  setDownshift = (downshift) => {
    this.downshift = downshift
  }

  resetForm = (e) => {
    ...Your reset logic here
    this.downshift.clearSelection()
  }

  render() {
    return <Downshift ref={setDownshift} render={SomeComponent} />
  }
}
```

What do you think?

**Comment by kentcdodds** [comment]
You can do that already. That's how refs in react work. No need to change the code.

That said, it would be very imperative so it'd probably be better to do this a different way.

If you want to control the selectedItem state outside downshift, the solution is to use control props. See the documentation for how to accomplish that. There's also [an example for this as well](https://github.com/paypal/downshift/blob/master/stories/examples/controlled.js).

Either way, this is definitely possible, so I'll go ahead and close this issue. Thanks!

**Comment by kentcdodds** [comment]
Here's a permalink: https://github.com/paypal/downshift/blob/e1273c8df4d6b33365d8f2bf69cee9d6f8b97760/stories/examples/controlled.js

**Comment by aysegulkavakli** [comment]
Is there any solution with React function components or can we use the clearSelection method outside of the downshift ?
