### ISSUE TITLE
Menu closes when touching an item inside a menu which is in a portal

### ISSUE THREAD

**Issue by green-arrow** [paypal/downshift#485]
- `downshift` version: 2.0.9
- `node` version: 8.9.4
- `npm` (or `yarn`) version: yarn 1.7.0

Relevant code or config

```javascript
<Portal>
  <ul {...getMenuProps()}
    // Items with getItemProps inside
  </ul>
</Portal>
```

What you did: Click on an item inside the menu, which is being rendered inside of a portal.

What happened:

Menu item was not selected and the menu was closed.

Reproduction repository:

N/A - Can create a code sandbox if needed

Problem description:

When touching an item, Downshift determines whether or not to reset based off of `event.target` being contained inside of `this._rootNode`. In this case, the target is outside of `this._rootNode` since it is in a portal.

Suggested solution:

Take `this._menuNode` into account inside of `onTouchStart` in addition to `this._rootNode`.

Relevant code: https://github.com/paypal/downshift/blob/master/src/downshift.js#L937-L945

Relevant issue: #444

**Comment by kentcdodds** [comment]
Let's do it :+1: Thanks for filing the issue. Would you like to contribute the changes?

**Comment by green-arrow** [comment]
Yep, sure will!
