### ISSUE TITLE
Type Ahead Example Differences in v1 & v2

### ISSUE THREAD

**Issue by damonbauer** [paypal/downshift#489]
- `downshift` version: 2.0.10

**Relevant code or config**
https://codesandbox.io/s/2w0ww46pqj

**What you did:**
Updated the Type Ahead example ([v1](https://codesandbox.io/s/82m2px40q9)) to version 2.0.10.

**Problem description:**
When filtering the list with the character "a", then selecting "apple", an alert shows & says I chose "apple". However, the input still shows "a", as well as the "Selected Fruit" text above the input.

In version 1, the input & the text above would show "apple".

**Suggested solution:**
Not sure.

**Comment by kentcdodds** [comment]
This was one of the few breaking changes in downshift 2. Here's a working version of your sandbox: https://codesandbox.io/s/n991m9ol4p

In addition, I added a more complete example to the examples here: https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=%2Fsrc%2Fordered-examples%2F03-typeahead.js&moduleview=1

Thanks for inspiring me to update that :)
