### ISSUE TITLE
parent.contains is not a function when used with styled components

### ISSUE THREAD

**Issue by davereid91** [paypal/downshift#490]
- `downshift` version: 2.0.10
- `node` version: 9.5.0
- `npm` (or `yarn`) version: 1.5.1

Relevant code or config

```javascript
        <Downshift
            defaultSelectedItem={selectedOption}
            itemToString={item => (item ? item.message : '')}
        >
            {({
                highlightedIndex,
                itemToString,
                getItemProps,
                getMenuProps,
                getToggleButtonProps,
                isOpen,
                selectedItem,
                toggleMenu,
            }) => (
                <div>
                    <Dropdown.Container>
                        <Button {...getToggleButtonProps()}>Button Toggle</Button>
                        <Dropdown isOpen={isOpen} {...getMenuProps()}>
                            {options.map((option, index) => (
                                 <div
                                    {...getItemProps({
                                        key: option.id,
                                        index,
                                        item: option,
                                        isActive: highlightedIndex === index,
                                    })}
                                />
                            ))}
                        </Dropdown>
                    </Dropdown.Container>
                </div>
            )}
        </Downshift>
```

What you did:
The code above is pseudo code but roughly equates to what I am doing. I am building a dropdown using downshift that toggles when you click a button. I am combining this with styled components and when I click outside of the div I am getting an error from within downshift.

What happened:
The error that I am getting is the following:

<img width="410" alt="screen shot 2018-06-27 at 14 40 47" src="https://user-images.githubusercontent.com/17887108/41977816-40c85868-7a18-11e8-8b32-dbdf9b2fcc2c.png">

When digging deeper into this, it's because the parent in isOrContainsNode is coming through as a Styled Component wrapper as you can see in the screenshot below:

<img width="811" alt="screen shot 2018-06-27 at 14 45 08" src="https://user-images.githubusercontent.com/17887108/41978035-cdd70aa6-7a18-11e8-9d0c-810793553d63.png">

Problem description:
Clicking outside of the downshift container div when using styled components is throwing an error and the dropdown window stays open.

**Comment by alexandernanberg** [comment]
I think the problem is that the `getMenuProps` is trying to set a `ref` on the `<Dropdown />`. Styled components accepts an `innerRef` prop for this, so please try with this instead 
```javascript
<Dropdown isOpen={isOpen} {...getMenuProps({ refKey: 'innerRef' })} />
```

Altough we should probably add a check if the `ref` exists before we try accessing it.

**Comment by kentcdodds** [comment]
> we should probably add a check if the ref exists before we try accessing it.

Agreed. I'd accept a PR for that :+1:

**Comment by davereid91** [comment]
Yep that fixed it, thanks very much @alexandernanberg :)

**Comment by alexandernanberg** [comment]
@kentcdodds Been thinking a bit more about this one. Wouldn't it be good to also print a warning when this happens? The `ref` is there for solving issues when using the menu inside a portal, so this could lead to unexpected behavior 🤔

**Comment by morajabi** [comment]
Also, it seems it's not in type definitions.

**Comment by kentcdodds** [comment]
Yes, we should log a warning 👍

**Comment by kentcdodds** [comment]
And we should add type definitions.

**Comment by franklixuefei** [comment]
If nobody is working on this, I’ll take a stab later.

**Comment by xshyne88** [comment]
Is there any update on this, I'm still hitting it in my codebase.

**Comment by kentcdodds** [comment]
@xshyne88, this is the solution: https://github.com/paypal/downshift/issues/490#issuecomment-400745565

**Comment by franklixuefei** [comment]
Uh... I need some help here...

I applied `getMenuProps()` to a primitive element, `<div>`, but it still complains that getMenuProps() was not applied correctly.

my code looks something like below, where I applied `getMenuProps` on a div, but that div itself is under some composite component.

```ts
<SomeCompositeComponent>
  <div {...getMenuProps()}>
    {here goes the menu items}
  </div>
</SomeCompositeComponent>
```

I thought we only need to specify a `refKey` if `getMenuProps` is applied to a composite component, no?

I literally have no idea how to fix this. Please help! Thanks!

**Comment by kentcdodds** [comment]
Hmmm... I'm unable to reproduce this: https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=%2Fsrc%2Fordered-examples%2F01-basic-autocomplete.js&moduleview=1

**Comment by franklixuefei** [comment]
@kentcdodds Okay I found the problem. I was mounting and unmounting the entire menu as needed. Apparently menu should mean to be mounted all the time. Not sure if we want to document this explicitly?

**Comment by kentcdodds** [comment]
Yes, for accessibility reasons it should always be rendered. Feel free to make a PR to improve docs. I think it is mentioned but could probably be called out better.
