### ISSUE TITLE
Default autoComplete to "nope"

### ISSUE THREAD

**Issue by TLadd** [paypal/downshift#497]
Currently with my inputs, I am following the advice in https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion and overriding Downshift's `autoComplete="off"` to `autoComplete="nope"`. Otherwise, the autocomplete behavior still occurs in at least Chrome. I'm curious if it would make sense for downshift to use a default of nope, if the goal is to actually prevent autocomplete behavior.

**Comment by stipsan** [comment]
Thanks for sharing this info! 😄 

I managed to reproduce it but only if the input is directly followed by this element that uses `autoComplete`: 
```jsx
<input autoComplete="current-password" type="password" name="password" />
```

Sandbox link: https://codesandbox.io/s/p7769vo227

Adding `autoComplete="nope"` does indeed fix it, but if this is the only case where it's needed then I'm not sure if it makes sense to change the default 🤔

**Comment by kentcdodds** [comment]
I'm actually good with the suggested change. Things like this are the reason people use libraries. We deal with the weird stuff so people don't have to know what's going on. A pull request would be welcome here (with code comments that link to the article). 👍

**Comment by stipsan** [comment]
> For me, this problem is quite pervasive.
Ah fair point.

> Could you clarify what you mean by only if the input is directly followed by this element that uses autoComplete.

In the code sandbox I shared if you remove the password input element chrome no longer autocompletes the downshift input. I haven't seen this problem with chrome ignoring `autocomplete="off"` for other things than username, email or password fields myself but I know better than relying on my own experience 😄 

Good fix 👍
