### ISSUE TITLE
touchStart is missing from Downshift.stateChangeTypes typing

### ISSUE THREAD

**Issue by lixualinta** [paypal/downshift#508]
`downshift` version: 2.0.0

**What you did**:
I would like to use `Downshift.stateChangeTypes.touchStart`

**What happened**:
`touchStart` is missing in typing

**Suggested solution**:
Add `touchStart to StateChangeTypes`

**Comment by kentcdodds** [comment]
Thanks! Would you like to [make a pull request](http://makeapullrequest.com/)?!

**Comment by alexandernanberg** [comment]
Closing as it was fixed by #511 and #513
