### ISSUE TITLE
Displaying suggestions in dropdown only after n number of characters are typed in searchbox instead of one

### ISSUE THREAD

**Issue by licypal** [paypal/downshift#516]
- `downshift` version: 2.0.16
- `node` version: 6.12.0
- `npm` version: 5.8.0

**Relevant code or config**
https://codesandbox.io/s/82m2px40q9

**What you did**:

I tried to use Downshift to select a value from the dropdown

**What happened**:

Everything works fine. I have a question though. Currently it works in such a way that when I type one letter in the searchbox, dropdown starts showing suggestions as shown below:

![image](https://user-images.githubusercontent.com/6519992/42912528-af5a5712-8aa4-11e8-913e-8c2889114dd8.png)

What if I need to show the suggestions only after at least 3 letters are typed into the searchbox instead? Please let me know if you have any suggestions. Thanks!

**Comment by kentcdodds** [comment]
Hi, here's one thing you could try: https://codesandbox.io/s/kpm4v628r

If that's not enough, please ask on our [spectrum community](https://spectrum.chat/downshift)

**Comment by licypal** [comment]
@kentcdodds Thank you so much! Appreciate your help.
