### ISSUE TITLE
*Id props not specified on ts type for Downshift component

### ISSUE THREAD

**Issue by nealfwilliams** [paypal/downshift#530]
- `downshift` version: 2.0.19

**Problem description**:
The Downshift component has these props -- labelId, inputId, menuId, and getItemId -- that aren't declared on the ts type for the component.
https://github.com/paypal/downshift/blob/v2.0.19/src/downshift.js#L61
https://github.com/paypal/downshift/blob/v2.0.19/typings/index.d.ts#L71

**Suggested solution**:
Update typings/index.d.ts.  I can submit a PR for this if that would be helpful.

**Comment by kentcdodds** [comment]
Cool, could you [make a pull request](http://makeapullrequest.com)?
