### ISSUE TITLE
On IOS: Text Input Field Cleared When Keyboard is Hidden

### ISSUE THREAD

**Issue by VikR0001** [paypal/downshift#532]
- `downshift` version: downshift@2.0.20 
- `node` version: v8.11.3
- `npm` (or `yarn`) version: npm 5.6.0

**Relevant code or config**

No changes made to Downshift sample code.

**What you did**:

No changes made to Downshift sample code.

**What happened**:

Input field cleared at inappropriate time.

**Reproduction repository**:

Unmodified Downshift example for Apollo:

https://codesandbox.io/s/m5zrvqj85p

**Problem description**:

On iPhone/IOS 11.4.1, when you click in the text search box, the IOS keyboard appears as usual. You enter search text, and the list of search results appears -- which could be a lengthy list as in the app I'm developing. When you click the "Done" button on the keyboard to hide the keyboard and see any search results hidden by the keyboard, the text input field is cleared, and all results are deleted before you can see them.

**Suggested solution**:

Is it possible to detect the "Hide keyboard" event and avoid clearing the text input field?

Thanks very much in advance for advice!

**Comment by kentcdodds** [comment]
Hi @VikR0001!

> Is it possible to detect the "Hide keyboard" event

That's a great question. Can you find the answer? If that's possible, then I think we can investigate avoiding calling `reset` when that event is fired. I'm guessing what's happening is hiding the keyboard removes focus from the input which will reset downshift. There is a simple workaround for this behavior using a `stateReducer`, but I think it'd be better to see if we can detect when the user is simply hiding the keyboard.

**Comment by VikR0001** [comment]
The input field appears to be getting blanked in `this.reset`, when it is called by `this.input_handleblur()` after the Done key is pressed:

```
  this.reset = function () {
    var otherStateToSet = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
    var cb = arguments[1];

    _this5.internalSetState(function (_ref7) {
      var selectedItem = _ref7.selectedItem;
      return _extends({
        isOpen: false,
        highlightedIndex: null,
        inputValue: _this5.props.itemToString(selectedItem)
      }, otherStateToSet);
    }, cbToCb(cb));
  };
```
`selectedItem` is `null` here. Would it potentially be helpful to avoid changing `inputValue` when `selectedItem` is null?

**Comment by kentcdodds** [comment]
No, this behavior is intentional and there's a way to disable it for a specific use case (using a `stateReducer` as I indicated) and you can feel free to do that, but I'd suggest instead that if we can find a way to determine if the blur event was fired due to the keyboard being dismissed then we could prevent reset in that situation.

**Comment by VikR0001** [comment]
`handleblur` calls `this.reset` with:

`_this4.reset({ type: Downshift.stateChangeTypes.blurButton });`

Would it be helpful for `this.reset` to test `type`, and if it  == `Downshift.stateChangeTypes.blurButton`, skip changing the inputValue?

**Comment by kentcdodds** [comment]
There are many different use cases for components that you can build with downshift. The original use case for why I built downshift was to only show the selected item, if the user doesn't change the selection then the input should revert to the currently selected item. In the case that there is no selected item then that's an empty string.

As I said, if this doesn't satisfy your use case, you change this behavior using a `stateReducer` as in the example I made for you here: https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=%2Fsrc%2Fother-examples%2Fprevent-reset-on-blur.js&moduleview=1

I hope that's helpful. I'm guessing we wont be able to find a way to detect when the keyboard is being hidden so I'm going to close this. If you do find a way, let us know!

**Comment by VikR0001** [comment]
Awesome. Thanks!
