### ISSUE TITLE
Provide option to customize scrollIntoView.block

### ISSUE THREAD

**Issue by adrienharnay** [paypal/downshift#537]
- `downshift` version: 2.0.20
- `node` version: 10.5.0
- `npm` (or `yarn`) version: yarn 1.7.0

**Relevant code or config**

```js
<Downshift defaultHighlightedIndex={12} />
```

**What you did**:

Instantiate Downshift with `defaultHighlightedIndex`

**What happened**:

It scrolled to the 13th element, but it ended at the bottom of the Select (because `block: 'nearest'` [here](https://github.com/paypal/downshift/blob/e34f5bcbcfa6024cbaf73dcc0ee1ae65cbfdc029/src/utils.js#L29-L33)).

**Reproduction repository**:

/

**Problem description**:

I would like the highlighted element to be at the top of the Select, instead of being at the bottom.

**Suggested solution**:

I would like to provide an option to change `scrollIntoview.block`. Are you fine with me opening a PR? Thanks!

**Comment by kentcdodds** [comment]
I think I have a better idea. I'll make a PR :)

**Comment by kentcdodds** [comment]
What do you think of this @adrienharnay? https://github.com/paypal/downshift/pull/538

**Comment by adrienharnay** [comment]
Really nice :+1: Thanks a lot, always a pleasure to use Downshift and to interact with you on Github!
