### ISSUE TITLE
Improve build-conditional logic code with a custom macro

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#540]
There are a few places in downshift that we do stuff like this:

```javascript
preval`module.exports = process.env.BUILD_REACT_NATIVE !== 'true'`
```

For example:

https://github.com/paypal/downshift/blob/4b659d083f3ec0c7709b9bc9a060bab7438fdbc4/src/downshift.js#L249-L255

I'm pretty sure we could write a custom [macro](https://github.com/kentcdodds/babel-plugin-macros) to make this simpler:

```javascript
import {isReactNative} from './env.macro'

// ...

  scrollHighlightedItemIntoView() {
    /* istanbul ignore else (react-native) */
    if (!isReactNative) {
      const node = this.getItemNodeFromIndex(this.getState().highlightedIndex)
      this.props.scrollIntoView(node, this._rootNode)
    }
  }
```

I'm fairly certain all we'd need to do is replace `isReactNative` with `true` or `false` and rely on rollup's dead code elimination, or perhaps add a babel plugin for dead code elimination. Either that, or we could just eliminate the code ourselves, though I feel like that would make it harder to maintain, so I'd prefer the alternatives.

**Comment by Andarist** [comment]
Dibs 😉
