### ISSUE TITLE
Working with a huge list of elements makes app super slow, using downshift, match-sorter and react-tiny-virtual-list

### ISSUE THREAD

**Issue by lauraSantillan** [paypal/downshift#549]
- `downshift` version: 2.1.1
- `node` version: 10.6.0
- `npm` version: 6.2.0

**What you did**: I write an app using downshift, match-sorter and react-tiny-virtual-list, in order to generate certificates for students, the campus has around 180000 students. On my first try, I split the data and used only a thousand students, everything was working great until I started using the whole set of data. The app works, but it's super slow, definitely no user-friendly. 

**Relevant code or config**

```javascript
function Autocomplete({ itemToString, students, ...rest }) {
    return (
        <Downshift itemToString={itemToString}  {...rest}>
            {({
                getInputProps,
                getToggleButtonProps,
                getMenuProps,
                getItemProps,
                isOpen,
                clearSelection,
                selectedItem,
                highlightedIndex,
                inputValue
            }) => (
                    <div {...css({ width: '100%', margin: 'auto' })}>
                        <div {...css({ position: 'relative' })}>
                            <Input
                                {...css({ fontFamily: `inherit` })}
                                {...getInputProps({
                                    isOpen,
                                    placeholder: 'Ingrese el nombre del alumno'
                                })}
                            />
                            {selectedItem
                                ? <ControllerButton
                                    onClick={clearSelection}
                                    aria-label="clear selection"
                                >
                                    <XIcon />
                                </ControllerButton>
                                :
                                <ControllerButton {...getToggleButtonProps()}>
                                    <ArrowIcon isOpen={isOpen} />
                                </ControllerButton>
                            }
                        </div>
                        <div {...css({ position: 'relative' })}>
                            <Menu {...getMenuProps({ isOpen })}>
                                {isOpen && students.length ? (
                                    <VirtualList
                                        width={300}
                                        scrollToIndex={highlightedIndex || 0}
                                        scrollToAlignment="auto"
                                        height={students.length < 5 ? students.length * 50 : 200}
                                        itemCount={students.length}
                                        itemSize={50}
                                        renderItem={({ index, style }) => (
                                            <Item
                                                key={students[index].CodEstudiante}
                                                {...getItemProps({
                                                    style,
                                                    item: students[index],
                                                    index,
                                                    isActive: highlightedIndex === index,
                                                    isSelected: selectedItem === students[index]
                                                })}
                                            >
                                                {itemToString(students[index])}
                                            </Item>
                                        )}
                                    />
                                ) : null}
                            </Menu>
                        </div>
                    </div>
                )}
        </Downshift>
    );
}

  handleStateChange = changes => {
    if (changes.hasOwnProperty('inputValue')) {
      this.setState({
        alumnos: this.getItems(changes.inputValue)
      });
    }
  };
  getItems = value => {
    return value
      ? matchSorter(this.state.alumnosData, value, {
        keys: ['NombreCompleto']
      })
      : this.state.alumnosData;
  };

```

**Comment by kentcdodds** [comment]
That's a LOT of data 😅 Definitely more than I've tried before. Let me play around with a few things and see if I can help you. Interesting problem.

**Comment by kentcdodds** [comment]
Ok, based on this I think the problem is match-sorter: https://codesandbox.io/s/pkqp0n97mj?module=%2Fsrc%2Fother-examples%2Ftons-of-data.js&moduleview=1

It's not very fast using the `filter` method, but it's unbearably slow if you set `const useMatchSorter = true`.

I'm afraid there's not much we can do for you here in downshift. downshift is performing really really well with tons of data (you can verify this by clearing the input value and scrolling through the list without any filter). You just hit the limit of match-sorter. We may be able to do something to speed up match-sorter, but that's not something I have time to work on myself.

Something you may consider is doing the filtering server-side where you can have more resources to crunch through the data to do your filtering, then loading the top matches asynchronously.

Good luck!

**Comment by lauraSantillan** [comment]
Thank you so much! =D

**Comment by sachiner** [comment]
@kentcdodds how can I get the index of the selected value in onchange function

**Comment by kentcdodds** [comment]
Use [`Array.prototype.indexOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf) :+1:

**Comment by brenoos** [comment]
Hello @lauraSantillan 

I Have the same problem, with this code:

`getSuggestions = value => {
    const funds = this.props.autoComplete.fundsList
    const inputValue = deburr(value.trim()).toLowerCase().replace(/(\.|\/|\-)/g, "")
    const inputLength = inputValue.length
    let count = 0

    return inputLength === 0
      ? []
      : _.filter(funds, fund => {
        
        const keep =
          count < 10 && (fund.n.toLowerCase().includes(inputValue.toLowerCase()) || fund.c.slice(0, inputLength) === inputValue)
        if (keep) {
          count += 1
        }
        return keep
      })
  }`

It works pretty fast, only showing 10 items, but the "includes" not work so well like with match-sorter.

Did you get any solution?

Thanks

**Comment by brenoos** [comment]
@lauraSantillan I solved in my application using another lib instead match-sorter, the lib called Fuzzy-Search

`  getItems = filter => {
    const searcher = new FuzzySearch(this.props.autoComplete.fundsList, ['n', 'c'], {
      sort: true,
    })
    
    return filter
    ? searcher.search(filter).splice(0, 10)
    : []
  } `

Now its pretty fast
