### ISSUE TITLE
Idea: Overload getItemProps for Advanced Props

### ISSUE THREAD

**Issue by nathanforce** [paypal/downshift#561]
- `downshift` version: 2.1.5

How would you feel about a PR implementing the added functionality below to `getItemProps`? These props are simple for Downshift to calculate internally but can be difficult or impossible to determine in userland.

```javascript
const props = getItemProps(({ index, itemCount, isSelected, isHighlighted }) => ({
    style: {
        fontWeight: isSelected ? 'bold' : 'normal',
        background: isHighlighted ? 'purple' : 'transparent',
    }
}))
```

Let me know what you think! Happy to make the PR if we think people might want this.

Thanks!

**Comment by kentcdodds** [comment]
To be clear, prop getters could accept an object of props or a function that accepts the same thing as children and returns an object of props.

If that's true, yes that sounds great. We'll need docs, tests, and implemention. Do you want to do that?

**Comment by nathanforce** [comment]
Not quite.  The function would accept the same thing plus some other helpful props like `isHighlighted` or `isSelected` that are trivial for Downshift to determine internally.

For example..

```
isSelected: this.getState().selectedItem === item,
isHighlighted: this.getState().highlightedIndex === index,
itemCount: this.items.length,
```

**Comment by kentcdodds** [comment]
Ah, gotcha.

Yes, that would be acceptable I think. Though the itemCount may not be accurate. The items are reset in every render and added to a you call `getItemProps`, so for the first item the itemCount would be 0...

In addition, I would like all other prop getters to support the function capabilities!

**Comment by nathanforce** [comment]
Okay I can do that.

Do you have any ideas on which values each prop getter would expose?

**Comment by kentcdodds** [comment]
Let's start with `this.getStateAndHelpers()` for all of them + `isHighlighted` and `isSelected` for `getItemProps`

**Comment by nathanforce** [comment]
@kentcdodds This is what I've got for `getItemProps` currently.  Wanted to get some feedback before doing the others.

Open discussion:

- This introduces a second argument to `getItemProps`. I could not come up with a way to do the overloading, as `{ item, index? }` are required to determine `isSelected` and `isHighlighted`
- What should happen if you pass an argument other than `{ item, index? }` while also passing a transform function? Should we pass through? Do we merge the results of the two? What about conflicts?


![image](https://user-images.githubusercontent.com/6694194/44596009-c95d4280-a798-11e8-8f2f-b773e3be6a3c.png)

**Comment by kentcdodds** [comment]
Let's go ahead and merge the conflicts. Similar to `Object.assign`, we'll have the second one win in the event of a conflict. And we'll do a shallow merge (similar to `Object.assign` or object spread which is what I'd recommend using).

**Comment by third774** [comment]
Glad to see this issue!

I'd love to see `isHighlighted` provided by `getItemProps()`. I'm currently working on refactoring a Dropdown component to use Downshift, and unfortunately there are some spots where comparing the index would be quite cumbersome if not impossible.

Right now all I've come up with is a super gross hack that I really don't want to use.

```jsx
const mergeClassName = (highlightedIndex, getClassName) => propsFromGetItemProps => {
  const isHighlighted = highlightedIndex === +propsFromGetItemProps.id.split("item-")[1]
  return {
    ...propsFromGetItemProps,
    className: getClassName(isHighlighted),
  }
}
```

**Comment by kentcdodds** [comment]
Could you use this workaround? https://github.com/paypal/downshift/pull/563#issuecomment-421428072

**Comment by kentcdodds** [comment]
I had intended on closing this per that conversation.

**Comment by third774** [comment]
Yeah - looks like I'm doing something similar. I suppose it's not so bad. Thanks! :)
