### ISSUE TITLE
Passing item object to getItemProps

### ISSUE THREAD

**Issue by klapouchy** [paypal/downshift#564]
I need to pass additional data to `onChange` function. 

The below code works however, since I am passing an Object I am getting a warning:

 `An object was passed to the default implementation of 'itemToString'`.

How can I pass `item` object without getting the above warning?

```js
{
  data.filter(i => {
    if (inputValue === selectedItem) {
      return i.name.includes(inputValue)
    }
  }).map((item, index, arr) => {
    return (
      <div
        {...getItemProps({
          key: index
          index,
          item: {
            name: item.name,
            id: item.id
          }
        })}
      >
        {item.name}
      </div>
    )
  })
}
```

**Comment by kentcdodds** [comment]
Hi @klapouchy,

Use the `itemToString` prop :)

**Comment by brandonreid** [comment]
For future noobs like me, here's an example of a custom `itemToString` function used to format the selected item string (needed for accessibility): https://github.com/downshift-js/downshift/issues/564
