### ISSUE TITLE
Strange, hard-to-debug behavior when `selectedItem` changes to `undefined`

### ISSUE THREAD

**Issue by dallonf** [paypal/downshift#566]
- `downshift` version: 2.1.4
- `node` version: 8.11.3
- `npm` (or `yarn`) version: Yarn 1.9.4

**Relevant code or config**

Note that the `Downshift` is controlled, but it can set itself to `undefined`, which I believe switches it to being uncontrolled. (`NONE_OPTION` is just a `Symbol`)

```javascript
<Downshift
  selectedItem={selectedItem}
  onChange={newItem => onChange(newItem === NONE_OPTION ? undefined : newItem)}
>
  {({ getItemProps }) => (
    <div>
      <Item
        {...getItemProps({
          item: NONE_OPTION,
        })}
      >
        None
      </Item>
      {items.map(item => (
        <Item
          {...getItemProps({
            item,
          })}
          key={item}
        >
          {item}
        </Item>
      ))}
    </div>
  )}
</Downshift>
```

**What you did and what happened**:

Open the reproduction repository: https://codesandbox.io/s/w08on9y7nl

1. Click on the button ("Black")
2. The dropdown opens. Choose "None."
3. Click on the button ("Select an item ...") again
4. "Black" is still highlight in the dropdown. (expected: None should be highlighted)
5. Choosing "Black" closes the dropdown and otherwise does not change the state; the button still reads "Select an item..." (expected: the dropdown should close and "Black" should now be selected).

**Reproduction repository**:

https://codesandbox.io/s/w08on9y7nl

**Problem description**:

The flow of changing a selection to "None" and then not being able to change back to what was previously selected is surprising.

The problem can be worked around by making "none" translate to `null` instead of `undefined`, and maybe it's not reasonable to expect "undefined" to be an accepted value of `selectedItem`, but the current behavior is so bizarre that it took me a good few hours to figure out what was going on.

**Suggested solution**:

One or both of these options would solve the problem, I think:

1. Warn when switching between controlled and uncontrolled, like React itself does for `input` elements.
2. When switching from controlled to uncontrolled, also clear the selected item from the internal state so that it's not left over from when the component was controlled.

**Comment by kentcdodds** [comment]
I think I'd prefer option 1! Thank you!

Could you make a pull request for it?

**Comment by dallonf** [comment]
Sure! I'll start working on that.

**Comment by dallonf** [comment]
Here's a PR for this: https://github.com/paypal/downshift/pull/568
