### ISSUE TITLE
[BUG] autoComplete="off" edge case

### ISSUE THREAD

**Issue by lucasbesen** [paypal/downshift#571]
- `downshift` version: 2.2.0
- `node` version: 10.9.0
- `npm` (or `yarn`) version: 1.9.4

**Relevant code or config**

```javascript
autoComplete="off"
```

**Problem description**:
`autoComplete="off"` works well to normal text auto fill on Chrome, but in name/e-mail, it doesn't work.

![image](https://user-images.githubusercontent.com/13984388/45065553-35408480-b090-11e8-9bb9-1211c41810b5.png)

**Comment by kentcdodds** [comment]
How frustrating. Do you have a suggestion for a fix?

**Comment by kentcdodds** [comment]
I think this has been resolved as much as we're able.
