### ISSUE TITLE
Add `getToggleButtonProps` as breaking change to 2.0.0 release notes

### ISSUE THREAD

**Issue by kirillku** [paypal/downshift#575]
Can you add renaming `getButtonProps` to `getToggleButtonProps` to breaking changes section of [2.0.0](https://github.com/paypal/downshift/releases/tag/v2.0.0). 

Got `Uncaught TypeError: getButtonProps is not a function` error and was not able to find in the changelog, why it's not there anymore. Later found that it's deprecated in bug fixes section of [1.31.1](https://github.com/paypal/downshift/releases/tag/v1.31.1)

related to #386

**Comment by kentcdodds** [comment]
Sorry about that! I've updated the changelog 👍 Thank you!
