### ISSUE TITLE
Record `highlightedItem` instead of just `highlightedIndex`

### ISSUE THREAD

**Issue by jamestalmage** [paypal/downshift#578]
It seems like, if people are calling `getItemProps` correctly, you could record the `highlightedItem` in addition to just the `highlightedIndex`.

This would just be for convenience when using (for example) `stateReducer` to handle blur events.

See #577

**Comment by kentcdodds** [comment]
I'm not sure I understand what you mean. The state reducer does have access to the highlighted index which you should be able to use to derive the highlighted item.

**Comment by jamestalmage** [comment]
If you are keeping the list of items in memory yourself, yes, that's true. I wasn't initially. I had a larger set of items which I was filtering and sorting based on `inputValue` - but I wasn't keeping the result of that filter/sort. I am now, but for the sole purpose of being able to derive the highlighted item.

As I said, there's workarounds for this. This would be a convenience method.

**Comment by kentcdodds** [comment]
Oh, I see what you mean. Yeah, I don't think we're going to do any work on this. The workarounds are sufficient I think. Thanks anyway!
