### ISSUE TITLE
A component has changed the uncontrolled prop "inputValue" to be controlled. 

### ISSUE THREAD

**Issue by matt-erhart** [paypal/downshift#585]
Sorry for the unformated issue. I'll forget about it if I don't post now.

this works when currentWordText is a string
```
        inputValue={this.state.currentWordText}
```
this gives the warning in the title
```
        inputValue={this.state.currentWord.text}
```
No idea why dotting into a text field would result in this error but thought you should know. Feel free to close.

**Comment by kentcdodds** [comment]
It's probably because the way your state object is. Make sure you're accessing the right value.

Good luck.
