### ISSUE TITLE
[Enhancement][Accessibility] When Listbox is closed, Up/Down should also highlight last/first option 

### ISSUE THREAD

**Issue by silviuavram** [paypal/downshift#589]
- `downshift` version: 2.2.3
- `node` version: 8.11.3
- `npm` (or `yarn`) version: npm, 5.6.0

**Enhancement description**:
According to ARIA 1.1 guidelines related to the Combobox, when Listbox is closed and you hit Up / Down as focus is on the Input, the Listbox should open, and the highlighted option should be last / first item. More on that [here](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html#Textbox).

At the moment, the scenario just opens the Listbox, without highlighting anything.

Since I am using Downshift for a prototype in the Stardust project, I managed to fix it from our side, but I believe this accessibility enhancement should also be implemented here, in the source.

**Suggested solution**:
If Listbox is not open and Up/Down is pressed, highlight last/first option after opening the Listbox.

Now working on a PR with a proposed solution. Updating some unit tests to reflect the changes.

**Comment by kentcdodds** [comment]
I'm pretty sure that if you set the `defaultHighlightedIndex` to `0` that's the behavior you'll get.

**Comment by silviuavram** [comment]
https://github.com/paypal/downshift/pull/590

Related to your answer, if I do that, the dropdown will always open with first item highlighted.

I only want for it to 1) open with first highlighted when I press Arrow Down and 2) open with last highlighted when I press Arrow Up.

When opened at click / text input, behaviour should remain the same. Do you agree?
