### ISSUE TITLE
Typeahead example: unexpected behavior on selection

### ISSUE THREAD

**Issue by whirledsol** [paypal/downshift#593]
- `downshift` version: 2.2.3
- `node` version: 8.9.4
- `npm` (or `yarn`) version: yarn 1.6.1

This is occurring in [the "typeahead" example from the downshift documentation.](https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=%2Fsrc%2Fordered-examples%2F03-typeahead.js&moduleview=1) I am able to replicate it on my local version as well.

**What you did**:
1. Type in "Luke Skywalker" so that the inputValue matches the selectedItem value.
2. Click on the "Luke Skywalker" Menu Item

**What happened**:
After clicking on the Menu Item, the inputValue blanks out to an empty string. No information of the selected item is passed to the onStateChange callback.

**Problem description**:
The expected behavior would be that the "Luke Skywalker" item was selected and shown in the inputValue. Similar to typing in "Luke Skywalk" and making the selection - this use case behaves as expected.

**Suggested solution**:
That's where you come in! I am new to React and the downshift library so be kind/have pity. I have a temporary solution of hiding the dropdown item if the inputValue matches.

**Comment by kentcdodds** [comment]
Yeah, I think this is the same problem reported in https://github.com/paypal/downshift/issues/512

We'll be releasing a fix for this on Monday I think. See #592 :)

Thanks!
