### ISSUE TITLE
Excessive `div` elements created within `#a11y-status-message`

### ISSUE THREAD

**Issue by morrisallison** [paypal/downshift#597]
- `downshift` version: `3.0.0`
- `node` version: `N/A`
- `npm` (or `yarn`) version: `N/A`

**Relevant code or config**

https://codesandbox.io/s/oxzn3x8jq5

```javascript
export class App extends React.Component {
  state = {
    unrelatedState: 0
  };

  updateUnrelatedState = () => {
    this.setState({
      unrelatedState: Math.random()
    });
  }

  componentDidMount() {
    setInterval(this.updateUnrelatedState, 1000);
  }
  
  render() {
    return (
      <Downshift initialSelectedItem="foo" />
    );
  }
}
```

**What you did**:

The Autodesk HIG team has created a dropdown component ([`@hig/dropdown`](https://github.com/Autodesk/hig/tree/development/packages/dropdown)) using Downshift. One of our consumers needs to use the dropdown inside another component which has state that's updated on an interval.

**What happened**:

`<div />` elements are infinitely created within the `#a11y-status-message` element.

![image](https://user-images.githubusercontent.com/3189455/46689758-6d6a4400-cbb5-11e8-903b-c8a53202beac.png)

**Reproduction repository**:

https://codesandbox.io/s/oxzn3x8jq5

All you need to do is inspect this page: https://oxzn3x8jq5.codesandbox.io/

**Problem description**:

The a11y functionality is creating an excessive amount of DOM nodes.

**Suggested solution**:

Prevent the a11y functionality from creating an excessive amount of DOM nodes. 😊

**Comment by kentcdodds** [comment]
Hi @morrisallison,

Those will be removed when the next message is anything other than `foo`. It's unlikely in a real application situation that the message would be the same thing over and over again like this. This isn't a practical issue, in reality there will likely only be a handful of divs in there at any given time (normally there will only be one).

We're not going to change the way that this works, this is working as intended for accessibility purposes. Thanks anyway!

**Comment by morrisallison** [comment]
@kentcdodds is this documented somewhere so I can properly relay the message?

With that said, I still don't understand why new messages are being added, when the value doesn't change.

**Comment by kentcdodds** [comment]
Turn on a screen reader when using downshift.

> is this documented somewhere so I can properly relay the message?

I'm not sure what you mean by "relay the message." That div is an implementation detail that you shouldn't concern yourself with.

**Comment by morrisallison** [comment]
> Turn on a screen reader when using downshift.

I understand this is a feature for screen readers. A screen reader will say "foo" each second with the given sandbox.

> I'm not sure what you mean by "relay the message." That div is an implementation detail that you shouldn't concern yourself with.

Sorry for the confusion. I meant, is there more information about this implementation so that we can better explain how this functionality works to our consumers.

Regardless, thanks for you time @kentcdodds 😊

**Comment by kentcdodds** [comment]
Why do your consumers need to know how this functionality works?

**Comment by toolness** [comment]
Wait, I am confused.  While I just tried this out with a screenreader and it doesn't seem to spuriously announce the extra `<div>`s as I thought it might, the fact remains that the component in the original description is nonetheless adding a new `<div>` to the page until the input changes.  So if a user were to leave their browser on a page with that component, without touching the keyboard for a very long time, wouldn't the system eventually run out of memory?

**Comment by silviuavram** [comment]
we are not doing this anymore since 3.2.9. We are adding one div with message then clean it up after 500ms

**Comment by toolness** [comment]
Oh cool, I guess I just need to upgrade then.  Thanks @silviuavram!
