### ISSUE TITLE
Windowing

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#6]
One thing that could really help with performance is if we window the scrollable area for the autocomplete. I'm thinking that we could either just have an example of how to use this with react-virtualized _or_ if it's not too complex, we could include our own miny implementation of windowing. Thoughts/ideas appreciated!

**Comment by kentcdodds** [comment]
Feel free to do this, but I don't want to keep this issue open.

I've decided that windowing is out of scope for `downshift` (heck, it doesn't even know that you're rendering a list of things really, you do all that rendering stuff yourself).

**Comment by abumuawiyah** [comment]
@tizmagik if you don't mind can you share sample code downshift+react-virtualized

**Comment by kentcdodds** [comment]
I'm guessing this example will be very similar to react-virtualized: https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=%2Fsrc%2Fother-examples%2Freact-window%2Findex.js&moduleview=1

**Comment by abumuawiyah** [comment]
> I'm guessing this example will be very similar to react-virtualized: https://codesandbox.io/s/github/kentcdodds/downshift-examples/tree/master/?module=%2Fsrc%2Fother-examples%2Freact-window%2Findex.js&moduleview=1

Cool. Thanks.
