### ISSUE TITLE
styled-components and ref

### ISSUE THREAD

**Issue by rifler** [paypal/downshift#604]
- `downshift` version: 3.1.0
- `node` version: 10.6.0
- `npm` (or `yarn`) version: 6.4.1

**Relevant code or config**

```typescript
const Main = styled('div')`
	color: red;
`;
...
<Downshift>
	{() => (
		<Main>...</Main>
	)}
</Downshift>
// downshift: If you return a non-DOM element, you must use apply the getRootProps function
...

<Downshift>
	{() => (
		// btw code says I can call getRootProps without args, but typings not
		<Main {...getRootProps({} as any)}>...</Main>
	)}
</Downshift>
// downshift: You returned a non-DOM element. You must specify a refKey in getRootProps
// downshift: You must apply the ref prop "ref" from getRootProps onto your root element
```

**Problem description**:
Since v4 styled-components uses forwardRef and accepts ref prop without any problems
https://www.styled-components.com/docs/advanced/#refs
![image](https://user-images.githubusercontent.com/871583/46996807-97c48000-d126-11e8-8c4d-af039a596173.png)

**Suggested solution**:
For now I fixed it like this
```typescript
<Main {...getRootProps({} as any, { suppressRefError: true })}>
```
It would be great to invent solution for this kind of components

**Comment by kentcdodds** [comment]
Hi @rifler. This is tough. I want to error early so people who don't know what they're doing know that they've done something wrong....

Hmmm... What if we do something like this:

```javascript
import {isForwardRef} from 'react-is'

// ... code

// then here: https://github.com/paypal/downshift/blob/3c6733b1b66077b5492af1ba48deaba944948064/src/downshift.js#L1159

if (isComposite && !refKeySpecified || isForwardRef(element)) {

```

I think that should work. Thoughts? Would you like to open a PR?

**Comment by rifler** [comment]
Of course, I will.

**Comment by chmaltsp** [comment]
@rifler  to get around this error all you need to do is pass the ref key down to the styled compoent
```
 <InputWrapper
            {...getRootProps({
              refKey: 'innerRef',
            })}
          >
```

**Comment by rifler** [comment]
@chmaltsp do you use v4? In v4 they use `forwardRef` API and `ref` key. `innerRef` is deprecated now

**Comment by rifler** [comment]
Thanks!

**Comment by chekkan** [comment]
Shouldn't the same change also be done for the `getMenuProps` method? Getting the following error when running unit tests. The menu element is a composite `styled.ul` component in my case.
```
console.error node_modules/downshift/dist/downshift.cjs.js:1510
downshift: The ref prop "ref" from getMenuProps was not applied correctly on your menu element.
```

**Comment by kentcdodds** [comment]
Probably. [PRs welcome](http://makeapullrequest.com)!

**Comment by kiranmarshall** [comment]
I'm almost certainly in the 'don't know what they're doing' camp, so if this solution is not optimal, it would be great to know, but for anyone with this issue when using `react-transition-group`, you need to add a ref to the `CSSTransition`'s child, and then pass that ref to the `nodeRef` prop:

`
         <CSSTransition in={isOpen && !!inputItems.length} timeout={500} unmountOnExit classNames="slide-down" nodeRef={ulRef}>
            <ul {...getMenuProps()}  ref={ulRef}>
            {isOpen &&
               inputItems.map((item, index) => (
                  <li
                     key={`${item}${index}`}
                     {...getItemProps({ item, index })}
                  >
                     {item}
                  </li>
               ))}
         </ul>
         </CSSTransition>
`

At least that cleared the error for me!

**Comment by seb-lean** [comment]
fwiw I had an issue where my scrollToView stopped working, I eventually figured it was something to do with the menu elem and `getMenuProps`, as when I removed that elem it worked.. 
I'm using Styled Components so I struggled for ages with forwardRef and inner ref and all that stuff, but eventually found that just adding `getRootProps` on a Styled Component root div made it work. I don't need a Styled Component there, but that's the only way it would work! 

```
<$ComboBox {...getRootProps()}>
  <$SearchInput {...getInputProps()} />
  <div data-cy="bank-list">
    {items.length ? (
      items.map((item, index) => (
...
```

Hope this helps someone else
