### ISSUE TITLE
Prop initialSelectedItem renders typescript error

### ISSUE THREAD

**Issue by Morton** [paypal/downshift#606]
- `downshift` version: 3.1.0
- `node` version: v10.7.0
- `npm` (or `yarn`) version: 6.1.0

**Relevant code or config**

```typescript
<Downshift
  onInputValueChange={setSearchTerm}
  itemToString={itemToString}
  onChange={onChange}
  stateReducer={reducer}
  initialSelectedItem={getSelectedItem(selection.response)}
>
  {props => <div>{children({ ...props, isLoading, response })}</div>}
</Downshift>
```

**What you did**:
I am using typescript for running above code snippet. Everything works fine until adding the `initialSelectedItem`-prop. 

**What happened**:
TypeScript will showing following stack trace:
`Property 'initialSelectedItem' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DownshiftProps<any>, ComponentState, any...'.`

**Reproduction repository**:
Any Downshift-Component usage with `initialSelectedItem` in typescript will produce the error.

**Problem description**:
It looks like the typings/index.d.ts is referencing different props:
```typescript
export interface DownshiftProps<Item> {
  defaultSelectedItem?: Item
```

**Suggested solution**:
Just confirm to me that I am on the correct path and I will create a PR updating the DownshiftProps-interface.
Thanks.

**Comment by rifler** [comment]
will be fixed after https://github.com/paypal/downshift/pull/603

**Comment by kentcdodds** [comment]
Merged.
