### ISSUE TITLE
ARIA Attributes Follow Best Practices

### ISSUE THREAD

**Issue by GuidovdRiet** [paypal/downshift#607]
- `downshift` version: 3.1.0
- `node` version: 9.2
- `npm` (or `yarn`) version: 5.6

Receiving the following errors while testing Downshift in Chromes Audit:

1. Elements with [role] that require specific children [role]s, are missing:

`<div role="combobox" aria-expanded="false" aria-haspopup="listbox" aria-labelledby="lang-switcher-label"><button type="button" role="button" aria-label="open menu" aria-haspopup="true" data-toggle="true">nl</button></div>`

2. [aria-*] attributes do not have valid values

`<div role="combobox" aria-expanded="false" aria-haspopup="listbox" aria-labelledby="lang-switcher-label"><button type="button" role="button" aria-label="open menu" aria-haspopup="true" data-toggle="true">nl</button></div>`

**Comment by silviuavram** [comment]
For error number 1, your failure comes from failing to supply an `<input>` element inside the `<div role="combobox" />`. A combobox needs a input to type into as its child. You may also be required to supply an `aria-owns` with the listbox ID if you plan to use the listbox outside the combobox div, but that is not the problem right now. Take a look at [aria combobx](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html) to see how you should organize your HTML inside the downshift children function.

For error number 2, your failure comes from `aria-labelledby="lang-switcher-label"`. The element with the ID you supplied as parameter does not exist probably.

**Comment by silviuavram** [comment]
@kentcdodds can we close this? unless you have something more to add.
