### ISSUE TITLE
Allow multiple values to be selected

### ISSUE THREAD

**Issue by souporserious** [paypal/downshift#61]
I think multiple selection is pretty common, as seen here in [react-select](https://github.com/JedWatson/react-select#multiselect-options). I'm going to take a stab at this since I need it. I sort of implemented something similar already in [selectly](https://github.com/souporserious/selectly) so hopefully I can just pull all of that stuff over.

**Comment by souporserious** [comment]
Alright, I have this working in a local branch and it's pretty dang cool 🤓 I think we can build every demo from react-select with this functionality. Once I get my other PR's reviewed, I'll submit this to see if you want it 😇

**Comment by kentcdodds** [comment]
Sounds great :+1:

**Comment by geoffdavis92** [comment]
@souporserious I actually sketched one of those out for the examples! Here: https://www.codesandbox.io/s/M89KQOBRB

**Comment by souporserious** [comment]
Nice! That's pretty much what I'm doing, just internally now :) I think it's ok to be opinionated about this part since it seems fairly common in UI's and the code to handle it will pretty much be the same. But, I'm open to whatever. Do you think it would be better not to include this in the library @kentcdodds? Maybe we can add helper utils for specific things like this.

**Comment by geoffdavis92** [comment]
@souporserious that sounds awesome. Yeah mine is a little rough and perhaps a bit over-engineered. 

I second the desire to have a Helper utils/components sub-library, and would love to contribute if desired.

**Comment by kentcdodds** [comment]
I think this is common enough that it'd be nice to expose a helper for it.

**Comment by souporserious** [comment]
I created similar utilities for my selectly library, maybe I can port them over here :) https://github.com/souporserious/selectly/tree/master/src/utils

**Comment by souporserious** [comment]
done 💯
