### ISSUE TITLE
Checkbox just selected when click in the box and not in the whole item

### ISSUE THREAD

**Issue by tatimoreira** [paypal/downshift#614]
Hello is there any way I can use checkbox in Downshift but just select an option clicking in the box and not in the whole label/text/option ? I would like to achieve this because I have a nested object which will show its subOptions when clicked and will just be selected when the box on the checkbox is clicked.

**Comment by silviuavram** [comment]
@tatimoreira is this issue still active? If not I will close it. If yes, I will try to assist you with a solution.
