### ISSUE TITLE
Provide `getInputProps` to the consumer after I used it?

### ISSUE THREAD

**Issue by FezVrasta** [paypal/downshift#615]
Hi, this is more an usage question than a bug request, I hope it's fine to ask it here.

I want to provide this kind of API to my consumers:

```jsx
const myCustomStuff = () => console.log('foo');

[...]

<Dropdown>
  {getInputProps => <input {...getInputProps({ onFocus: myCustomStuff })} />}
</Dropdown>
```

but, internally, I need to do this:

```
render() {
  children(getInputProps({ onFocus: this.openMenu }));
}
```

So, basically, I need to use `getInputProps` internally, to make sure both the Downshift `onFocus` is called, together with my `openMenu` function.

But then, I want to allow my consumer to use `getInputProps` as well to further enhance the `onFocus` handler with his own logic.

Do you have any suggestion?

Thanks!

**Comment by kentcdodds** [comment]
I think something like this should work:

```javascript
render() {
  children({
    ...downshift,
    getInputProps: ({ onFocus, ...props }) =>
      downshift.getInputProps({
        ...props,
        onFocus: callAll(onFocus, this.openMenu)
      })
  })
}
```

I've done this in the past and it works great. :)

**Comment by FezVrasta** [comment]
Thanks! Is the `callAll` helper exposed by Downshift?

**Comment by gabrielmicko** [comment]
This is great! Thanks!

**Comment by kentcdodds** [comment]
No, `callAll` is not exposed, but it's pretty simple:

```javascript
const callAll = (...fns) => (...args) => fns.forEach(fn => fn && fn(...args))
```

**Comment by FezVrasta** [comment]
Ok cool, thanks for the support :-)
