### ISSUE TITLE
stateChangeTypes is badly documented

### ISSUE THREAD

**Issue by aureooms** [paypal/downshift#620]
**Problem description**:
The current documentation suggest the user to *run* the following *in his app*

```js
console.log(Object.keys(Downshift.stateChangeTypes))
```

**Suggested solution**:
Add an explicit list of those keys to the documentation.

**Comment by kentcdodds** [comment]
I think this is a good idea. Would you like to open a pull request for this please @aureooms? Thanks!

**Comment by aureooms** [comment]
Sure! Can you tell me which file(s) define(s) those keys?

**Comment by kentcdodds** [comment]
https://github.com/paypal/downshift/blob/master/src/stateChangeTypes.js

**Comment by kentcdodds** [comment]
By the way, use `keyDownEscape` not `__autocomplete_keydown_escape__`.
