### ISSUE TITLE
Weird Voiceover behavior in latest version of Chrome

### ISSUE THREAD

**Issue by dstapleton92** [paypal/downshift#621]
- `downshift` version: 1.31.16
- `node` version: 10.11.0
- `npm` (or `yarn`) version: yarn 1.10.1

Has anyone else noticed weird behavior when using Voiceover on the autocomplete suggestions in Chrome in macOS Mojave? Our autocomplete suggestions are read partially, and then read again. For example, if you type "apple" into the search field, and scroll down to a suggestion for "apple sauce", VO will read "apple apple sauce". Or for "chicken", scrolling to "chicken noodle soup" reads "chicken noo chicken noodle soup".

After some troubleshooting, I suspect there has been a change in behavior and the suggestions are being read directly by VO **in addition to the live region** that Downshift is updating with the A11y status message.

Note that this does not occur with Safari, and I'm not sure if this is something that changed in Chrome with the latest version, or with VO in Mojave, as I updated both around the same time. Can anyone confirm this behavior? Am I crazy or is this real?

Thanks!

**Comment by silviuavram** [comment]
confirmed here as well, after tried to fix it from my end for about an hour.

**Comment by silviuavram** [comment]
Reproduced it with other screen readers as well, only that Jaws and NVDA will narrate the autocomplete suggestion twice. Narrator just stops while narrating first and then narrates it again.

Issue comes from `getA11yStatusMessage` because it returns `itemToString(highlightedItem)` when you go through the suggestions in the list. Screen readers read the <li> option naturally, without us needing to explicitly set an `aria-live` message for it.

As I don't think anything changed in that area in `Downshift`, I am curious how did this issue just occurred? Was it always there and we did not notice?

A quick workaround would be to override `getA11yStatusMessage` with our own one via props, but we might also need to change the default one in `Downshift`, as it is not providing a correct behaviour. What do you guys think @kentcdodds @dstapleton92 ?

**Comment by kentcdodds** [comment]
Interesting! Could you open a PR for the fix and I'll give it a look. Thank you so much for all the time you've spent helping make the corner of the internet that uses downshift more accessible 🤗

**Comment by dstapleton92** [comment]
For our use case, overriding `getAllyStatusMessage` with a similar function that doesn't read the selected item was a no-go. The reason why is because Safari does **not** automatically read the selected item of the aria combobox, so this would exclude Safari users from being able to use a screen reader.

Knowing that the autocomplete suggestions are just plain divs with no tab index, I thought "what is it about the selected item that is making Chrome read it aloud?" After some digging, I discovered it is the usage of `aria-activedescendant` on the input. We have resolved this issue in our code by passing `'aria-activedescendant': null` into the call to `getInputProps({ ... })`.

Eventually, when all browsers read the selected item of an aria combobox aloud, using `aria-activedescendant` will be great. But for now, for us at least, we disabled this because not all browsers read it aloud, so we need the aria live region, and cannot have double-reading on Chrome.

**Comment by kentcdodds** [comment]
Maybe downshift should just do that by default. Part of the benefit of an abstraction like downshift is it allows people to do the right thing by default without proper having to know what Hanks are going on to make it work.

Anyone up for a pull request? Should be simple.

**Comment by dstapleton92** [comment]
@kentcdodds 👍 Just opened PR #626.

**Comment by silviuavram** [comment]
@kentcdodds please take a look over changes I made in https://github.com/paypal/downshift/pull/629 and see if they make sense.
@dstapleton92 please also take a look over the PR, and check if it solves the issue in Safari. I tried it in the docs example and it worked for me. But I want to also test with other screen readers and also need input from you as well.

Thank you everyone for your patience and hopefully we can make a decision that will improve the behaviour and fix the problem.
