### ISSUE TITLE
Behaviour when moving before the first item

### ISSUE THREAD

**Issue by miiimooo** [paypal/downshift#625]
- `downshift` version: 3.1.5
- `node` version: 8.9
- `npm` (or `yarn`) version: 5.6.0 (1.3.2)

**Relevant code or config**

```javascript
<form onSubmit={this.onSubmit}>
          <Downshift
              onChange={this.downshiftOnChange}
              itemToString={this.downshiftItemToString} >
            {({ selectedItem, getInputProps, getItemProps, highlightedIndex, isOpen, inputValue, getLabelProps }) => (
                <div>
                  <input {...getInputProps({
                    placeholder: Search products,
                    onChange: this.inputOnChange
                  })} ref={this.input} />
{isOpen ? (
                      <div className="downshift-dropdown">
...
            )}
          </Downshift>
          <input type="submit" value="Submit" className="dropdown-button" />
        </form>
```

**What you did**:
* I enter a term like "test", I see a list of suggested results
* press the down cursor key, selects first item of results
* press the up key, I'm on the last item of the results

![image 11](https://user-images.githubusercontent.com/1226434/48941102-7b341880-ef1a-11e8-82f8-0fa80e527e54.png)

**Suggested solution**:
* I would like to return to the input text box

**Comment by kentcdodds** [comment]
> I would like to return to the input text box

You're actually _always_ in the input box... At any point you can continue typing because the focus never leaves the input box.

**Comment by kentcdodds** [comment]
I think this can be closed
