### ISSUE TITLE
Downshift without an input

### ISSUE THREAD

**Issue by nmaves** [paypal/downshift#628]
- `downshift` version: 3.1.5

This is a common error but one that I would like to see hidden for my specific use case.

An object was passed to the default implementation of `itemToString`. You should probably provide your own `itemToString` implementation. Please refer to the `itemToString` API documentation. The object that was passed: {label: "Add all to Cart"}

I am trying to use Downshift for a drop-down menu of sorts.  There is no input so there is really no need for the itemToString in my case.  Could there be a way internally to check if there getInputProps() has been applied and if so then display this warning?

Nathan

**Comment by kentcdodds** [comment]
Hi @nmaves 👋

If you don't need it, you could just do: `<Downshift itemToString={() => {}} />`

I don't think I want to add any code for this use-case. It's not very common.

Thanks!

**Comment by nmaves** [comment]
Sounds good, that is what I have already done 🏅

**Comment by Harsh1796** [comment]
@kentcdodds using <Input> tag without an actual input (like in this case or of building dropdowns) would create accessibility issues as the aria roles are according to an Input tag not an option for select or does downshift consider any such use case.
