### ISSUE TITLE
Make getItemCount available in getStateAndHelpers

### ISSUE THREAD

**Issue by Wgil** [paypal/downshift#637]
Hello,

I see there is a `resultCount` variable used for ARIA statuses. I was wondering if there's a reason of why `getItemCount` or `resultCount` aren't available in the response object of `getStateAndHelpers` function.

**Problem description**:
My current problem is that I would like to show a No Results message only when the API results are available without adding another piece of state to manage it. 

**Suggested solution**:
It would be good to expose the `resultCount` in Downshift and simply do something like:
```js
{!resultCount && 'Nothing Found'}
```

Is there any possibility to do so?

Cheers.

**Comment by kentcdodds** [comment]
Hi @Wgil!

I'm not sure this is going to do what you want it to. How do you know that the result count is `0` because there was nothing found vs it's `0` because they haven't been loaded yet?

**Comment by Wgil** [comment]
I thought it could be:
```js
{!resultCount && !loading && "Nothing found"}
```
but now I can't find any difference than checking for `this.state.items.length` 😅 . I think it got confused with `isOpen`. So now to show my items I'm going to do `{isOpen && isLoaded && (...)}`

I'm closing this,
Have happy holidays!
