### ISSUE TITLE
Issue #630 regarding key event propagation is a breaking change.  I cannot find a workaround that is reasonable

### ISSUE THREAD

**Issue by timvracer** [paypal/downshift#642]
- `downshift` version: 3.8
- `node` version: 
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```

**What you did**:

**What happened**:

**Reproduction repository**:

**Problem description**:

Issue #680 was implemented in 3.8, and unfortunately is a breaking change for anybody who needs the ESCAPE key further up in the component chain.    I'd like to suggest that the previous behavior be returned or a controlling property added.  My rationale:
a) It is trivial to stop propagation on keycodes you wish not be propagated with an input key handler
b) It is non-trivial to workaround the key event being stopped by Downshift when the listener is several layers up in the component chain.
c) an alternative would be to add a property to control this for ESCAPE, such as "escapeDoesNotPropagate", which is similar to what I have seen in some material-ui components

I could understand this change when the menu box is open (Escape closes the box), but there are many application situations for which Escape has a more global impact desired, and is relevant beyond the Downshift context.  (for example, escape always exits a particular edit state for an entire form while within an edit control).  Escape has always been a pretty important method to exit an edit state, so it is necessary to receive the event from controls that may be in a form.  Sometimes the form is complicated, and the input control that will receive the events is several components in from the parent component that listens to the event, and the onKeyDown is not chained throughout all those components.

**Suggested solution**:

**Comment by johnjesse** [comment]
sorry that this broke your app @timvracer , I take it you can't use preventDownshiftDefault to stop this behaviour because you still want downshift to handle it too.

Also... It was my understanding that the escape event handler only ran if the dropdown was open... i.e. if it actually reset the control. If the control was already reset and escape would do nothing I agree it should not be marking the event as handled or stopping propagation (or preventing default) 

I'm not sure about the work around you suggest about it being "trivial" to stop propagation on keycodes you don't want
1) This ties anything I'm wrapping downshift in to understand downshifts implementation details to decide whether it even needs to bother stopping propagation events
2) As above, propagation should depend on the state of the downshift control... as I don't always want to stop the events - only when downshift has used them... so whatever was wrapping would need to know things like the open state etc... 

For the case you suggest, where you always want escape to do something, could you potentially use the capture phase of the event instead? I'm not sure that's the desired solution but it might help you get around the problem

**Comment by kentcdodds** [comment]
I think it would be useful to see examples of both use cases (can use an older version of downshift for the previous behavior) and see which is more awkward/flexible.

**Comment by timvracer** [comment]
John,
You are correct, I still want Downshift behavior (e.g. close the menu on Escape and reset the value), but in the case where them menu is already closed, I also need to close my dialog box, as you also note above in your assumption that in fact it would not stop propagation if the menu was closed. 

Indeed, I am having to keep track of the menu open/close state myself via onStateChange to make this work, and it is awkward as you surmise.

I suggest, and am happy to try and implement, a property to control this behavior.  First of all, I think we all agree that if the menu is open, Escape should close the menu and stopPropagation(), this is consistent with all UI models I have seen.  However, if the menu is NOT open, I suggest we create a property "disableEscapeKeyPropagation" or some other such name (I suck at naming) that would simply execute the behavior desired by the component user.  If the menu is closed, and this property is not set, then stopPropagation will be called on Escape.  If the menu is not closed, then it will not stop the propagation.

I am hoping and presuming that the menu open/close state will be accessible in the keyDown handler, I have not looked yet.

**Comment by timvracer** [comment]
BTW.. not sure what you meant by "capture phase of the event", what I am trying to do now to work around it is fire a simulated event using Simulate from test utils, but this is bad -- has many issues, and  it sorta works... but not breaks as well -- so not going to work I think.

**Comment by timvracer** [comment]
causes 2 tests to fail, of course will need to update those too.  What do you all think?

**Comment by johnjesse** [comment]
Tim,
the idea sounds good to me,  I'd suggest the prop be a little more general... something like 
`stopPropgationOfKeyDownEvents` that defaults to false, can be true, or an object specifying the names of key events to stop propagation on? as the `stopPropagation` on other key events could also cause issues for others.

As for the capture phase, I meant that if you have some global behaviour that always wants to happen on escape (I think the example behaviour you suggested was in a form), then you could handle the keyDown event on capture. It was only intended as a quick workaround in that case. It clearly doesn't fit the more general use case of the dialog element containing the downshift element that you describe, that only wants to conditionally handle escape based on the downshift state.

**Comment by timvracer** [comment]
I submitted a PR request for this issue.  However, it appears a test is failing in Travis, but the tests all run for me.  hmm... not sure why. Will look...

**Comment by silviuavram** [comment]
@timvracer can I close this? I am not fully aware of the context, but from what I saw there was not any agreement on any changes.

**Comment by timvracer** [comment]
I believe this was resolved by reverting the prior change, so yes, we
should be able to close this.  Thanks!
