### ISSUE TITLE
Scrolling to selectedItem on menu open?

### ISSUE THREAD

**Issue by bestguy** [paypal/downshift#645]
- `downshift` version: 3.1.10

I'm trying to implement a combobox that lists all items in a scrollable menu. The combobox does not filter or reduce the list of items.

When the menu opens (on focus or button click), I would like the menu to automatically scroll to the selected item (if any).  

Is this something supported by Downshift?

Basic example:
https://codesandbox.io/s/wynv166o7

**Comment by kentcdodds** [comment]
Hi @bestguy,

The simplest way is to use a `stateReducer` like so:

```js
    stateReducer={(state, changes) => {
      // if the user is opening the menu, then let's make sure
      // that the highlighted index is set to the selected index
      if (changes.hasOwnProperty('isOpen') && changes.isOpen) {
        return {
          ...changes,
          highlightedIndex: options.indexOf(state.selectedItem),
        }
      }
      return changes
    }}
```

https://codesandbox.io/s/8k2vrlv589

I noticed that it made the highlighted index appear at the bottom of the scroll view. If you'd like to change that then you can specify your own [`scrollIntoView`](https://github.com/paypal/downshift#scrollintoview) function. Good luck!

**Comment by bestguy** [comment]
Terrific!  Thanks!

**Comment by bestguy** [comment]
Actually @kentcdodds I'm seeing a little odd/counfusing behavior, if you toggle the menu, but then focus the input without changing text, sometimes the menu does not scroll to selectedItem when open.  If you toggle the menu a few times it will then scroll to selectedItem.

Maybe I don't fully understand stateReducer but unable to clear it up if you have any ideas.

**Comment by kentcdodds** [comment]
I'm not sure I understand what you mean. Could you make a gif?

**Comment by stipsan** [comment]
Looks like the sandbox link @kentcdodds shared is missing the stateReducer prop. Try this one: https://codesandbox.io/s/yq7pw7zm0v

**Comment by bestguy** [comment]
Looks like I can resolve the issue by setting the `highlightedIndex` to `null` when the menu is closing (`isOpen: false`):

```javascript
      stateReducer={(state, changes) => {
        // if opening the menu, then ensure highlighted index is set to the selected index,
        // if closing the menu, then ensure highlighted index is set to null:
        if (changes.hasOwnProperty('isOpen')) {
          return {
            ...changes,
            highlightedIndex: changes.isOpen ? options.indexOf(state.selectedItem) : null
          };
        }
        return changes;
      }}
```

I don't understand why this fixes the issue or is necessary, but I stumbled on the fix by noticing the issue was triggered by alternating between input focus and clicking toggle button.  In that case the `changes` are:

```javascript
{ isOpen: false, type: "__autocomplete_click_button__" }
```

But also noticed alternating between input focus and clicking outside the component does not trigger issue.  In that case the `changes` are:

```javascript
{ isOpen: false, highlightedIndex: null, inputValue: "Indonesia", type: "__autocomplete_mouseup__" }
```

Tried returning `highlightedIndex: null` when `isOpen: false` and it works!  Happy to close if this looks correct.  Would be good to understand why I need to do this though.  Thanks for the help.

**Comment by kentcdodds** [comment]
My guess is the `highlightedIndex` gets set to something superfluous at some point. I'm not sure why. Glad that you worked out a good solution though!
