### ISSUE TITLE
New primary maintainer needed

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#647]
Hey folks,

I'm drowning in GitHub notification emails and need to lighten my load. So with heavy heart I'm picking a few projects to detach myself from and unfortunately this is one of them. I'm choosing downshift particularly because I haven't personally used it in over a year so it really doesn't make a lot of sense for me to continue to maintain it.

I would like to hand this project off to someone who's _already_ been contributing to the project (I'd like to avoid another incident like [this](https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream/)). If you would like to take ownership of this project, please let me know by emailing me at the address found on my github profile.

I'm unwatching this repository effective immediately. I'm sorry about that, but I've just been stretched too thin. Even if nobody takes up the maintenance of this project, it works well in its current form for its current users and I hope that's good enough until someone is willing to take up the mantel as maintainer.

**Comment by silviuavram** [comment]
I will help out Kent with maintaining this project starting immediately. It will take some time for me to work out all the necessary operations, so please be a bit more patient than usually. There won't be any major changes in the near future, the library is stable, we will work towards clearing the issues and open PRs.

Thank you.

**Comment by kentcdodds** [comment]
Thanks!
