### ISSUE TITLE
Uneccessary ARIA role for Buttons 

### ISSUE THREAD

**Issue by camdub** [paypal/downshift#650]
- `downshift` version: `3.1.12`
- `node` version: `10.14.1`
- `npm` (or `yarn`) version: `npm 6.4.1`

I am using the method on a `button` like this:

```
<button {...getToggleButtonProps()}>
  <div>{selectedItem}</div>
</button>
```

One of the ARIA attributes that the `getToggleButtonProps` method sets is `role="button"`.  This works fine, but I ran the `axe-core` testing engine on the output and it flagged the output of the above code as follows:

```
Expected the HTML found at $('button') to have no violations:

    <button type="button" role="button" aria-label="open menu" aria-haspopup="true" data-toggle="true" class="css-1c1hyfz"><div>item1</div></button>

Received:

"ARIA role must be appropriate for the element (aria-allowed-role)"

Try fixing it with this help: https://dequeuniversity.com/rules/axe/3.1/aria-allowed-role?application=axeAPI
```

Upon more research, I found this note which is the reason this error is triggered:

> **Note**: In the majority of cases setting an ARIA role and/or aria-* attribute that matches the default implicit ARIA semantics is unnecessary and not recommended as these properties are already set by the browser.

https://www.w3.org/TR/2014/REC-html5-20141028/dom.html#aria-usage-note

`<button>` already has the implicit role of button. The current solutions to this are to disable the rule in aXe or use a non-button element. Neither seem great.

I realize that this might be a tough issue to fix as the `getToggleButtonProps` doesn't know what type of element is calling it, so I'm not sure how to conditionally add the role here. Another option is to allow the user opt-out of the role attribute like in https://github.com/paypal/downshift/issues/607.

Otherwise I'm not really sure the best approach.

**Comment by silviuavram** [comment]
Hi @camdub, thank you for your issue.

If I remember from a course I did some months ago, `<button role="button">` is an overkill, but it's not breaking anything. Theoretically.

We are adding it just in case your `toggleButton` is a `div` or a `span` or an `i` or whatever. We may need to think a bit about the `aria-label` from it, maybe we can make a better default value from that, but it's a story for another time.

What you can do right now is to use your `button` like this:
`<button {...getToggleButtonProps({role: undefined})}>
  <div>{selectedItem}</div>
</button>`

It will override our default role value. And this is the case with all our get<Something>Props() methods. In case you need something they output overriden, you pass in the object parameter (here it was `{role: undefined}`) and you will override them.

Apart from event handlers. In case you want some custom event handler, you can pass it to that object and we will call it, but we will call our own default as well.

Let me know if you have further questions. If not, you can close this issue. Thanks!

**Comment by camdub** [comment]
@silviuavram sounds good.

Setting `role` to `undefined` for the button passed the aXe a11y checks.
