### ISSUE TITLE
[Accessibility] Highlight defaultHighlightedIndex +/- 1 on Up/Down Arrow

### ISSUE THREAD

**Issue by silviuavram** [paypal/downshift#651]
If `defaultHighlightedIndex` prop is passed to Downshift, opening the list with Up/Down Arrow will highlight the defaultHighlightedIndex -/+ 1.

At the moment the behaviour is to highlight 0/count - 1 when you open the list with Down/Up Arrow. This behaviour will not be changed if you don't pass `defaultHighlightedIndex`. It will act as a default.

Work in progress, will add a PR today, maybe tomorrow.

- `downshift` version: 3.1.12
- `node` version: 10.13.0
- `npm` (or `yarn`) version: 6.4.1

**Comment by silviuavram** [comment]
Created Pull Request.

**Comment by Gregoor** [comment]
Glad to see this fixed, thanks for the hard work :)

What I've noticed is that onChange is still not fired, until the cursor keys are used. Is that on purpose?

**Comment by silviuavram** [comment]
I will take a look and will come back to you. Thank you!
