### ISSUE TITLE
More props for Input or possible additional component

### ISSUE THREAD

**Issue by souporserious** [paypal/downshift#67]
I'm trying build this [react-select multiselect demo](https://jedwatson.github.io/react-select/) and wondering if you have any ideas on how to handle this use case?

Should we add some props to determine how the Input is being used? I'm not sure the best way to handle this with our current setup. Seems like we just need to be able to clear the input value after an item has been selected 🤔

**Comment by kentcdodds** [comment]
I'm thinking that the best thing we could do is have another `Input` component that we expose (`Autocomplete.MultiInput`?) That seems like it'd be the most straightforward way to do things...

**Comment by souporserious** [comment]
👌 I like that. I'll start playing around with things 😁
