### ISSUE TITLE
What can we remove, need to add to getControllerStateAndHelpers?

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#71]
[The `getControllerStateAndHelpers` function](https://github.com/paypal/react-autocompletely/blob/d644435e2415fefa734baad8de5fd8f589dc1041/src/autocomplete.js#L166-L200) currently exposes a bunch of things which we use to send to the users of the component. What should we add or remove from this?

State:

- `value`
- `isOpen`
- `selectedItem`
- `highlightedIndex`

Actions:

- `toggleMenu`
- `openMenu` - shortcut to `toggleMenu(true)`, nice because you can pass it directly to an `onClick={openMenu}` rather than having to do: `onClick={() => toggleMenu(true)}`
- `closeMenu` - shortcut to `toggleMenu(false)`, nice for the same reasons as `openMenu`
- `selectItem`
- `selectItemAtIndex` - if we were to expose `getItemFromIndex`, then this could be a shortcut to `selectItem(getItemFromIndex(index))`
- `selectHighlightedItem` - shortcut to `selectItemAtIndex(highlightedIndex)`
- `clearSelection`
- `setHighlightedIndex`

Prop getters:

- `getRootProps`
- `getButtonProps`
- `getInputProps`
- `getItemProps`

I think we should probably expose `getItemFromIndex`. What else should we expose? What should we hide? Is there a way to restructure/rename things?

**Comment by jgoux** [comment]
Hello,

maybe we could remove `clearSelection` and accept `null` or `undefined` on `selectItem` ?

**Comment by kentcdodds** [comment]
As discussed in another issue, `clearSelection` does a amount more than set the selectedItem to `null`:

```js
  clearSelection = () => {
    this.internalSetState(
      {
        selectedItem: null,
        inputValue: '',
        isOpen: false,
      },
      () => {
        const inputNode = document.getElementById(this.inputId)
        inputNode && inputNode.focus && inputNode.focus()
      },
    )
  }
```

I'm feeling pretty good about the API now so I'm going to close this issue.
