### ISSUE TITLE
A note on equlity testing

### ISSUE THREAD

**Issue by ferdinandsalis** [paypal/downshift#83]
We should add a note somewhere about equality testing for props like `isSelected`. This will bite people (me just now ☺️) since objects might not be the 'same' across different render cycles. Maybe in the examples or in a notes section.

**Comment by kentcdodds** [comment]
Sounds great! Why don't you create a "Common Pitfalls" section in the README and add this to it :+1: Thanks!

**Comment by ferdinandsalis** [comment]
Will do.

**Comment by souporserious** [comment]
I was wondering about this. I was thinking we could treat `selectedValue` as `selectedValue: this.props.getValue(itemValue)` this way we are only working with strings or an array of strings so it's easier to do these things and avoid pitfalls. But that also might make it more complicated since you probably will need to find the item with helper like `getItemFromValue` or something.

**Comment by kentcdodds** [comment]
I think that the `selectedValue` should be `item.value` personally...

**Comment by souporserious** [comment]
I like it because you avoid the pitfalls. Do you think we should provide a helper like `getItemFromValue`?

**Comment by kentcdodds** [comment]
Maybe I'm confused by what you're suggesting....

**Comment by ferdinandsalis** [comment]
To be honest I am a bit confused about the different 'values'. This is my understanding of each of the 'values'.

* `selectedValue` — `selectedItem`, item is already a term used in the code
* `inputValue` — value of the input (this one is obvious) which is always a `string`
* `value` — the value from `getValue(selectedValue)` it kinda serves the purpose of an id, right?
* `defaultValue` — the `initialValue` of `value`

Also there is `getValue` which operates on `selectedValue`. I think of it as `getValueFromItem`. What are your thoughts. Hope this makes sense 😅. The gist of it, we should think hard about the names.

**Comment by souporserious** [comment]
Some old API's in there, sorry 😅  `value` is no longer a thing. It seems `selectedValue` might not make sense, maybe `selectedItemValue` is better? And then maybe `defaultValue` to `defaultSelectedValue` or something.

**Comment by ferdinandsalis** [comment]
… continued from above. The way how values are treated currently seem to be at odds with my thinking. I am trying to  implement a basic select input, similar to the one you find in the browser. Along those lines I pass in the options in the following format `[{ label: 'Arbeiten auf Papier', value: 'works_on_paper' }, …]`. If the select input already has value I pass it in like this `<Select defaultValue='works_on_paper' …`. When it renders I get `selectedValue` which is of course `fair`. Now I want to get the actual item and display a nice label (maybe even an image) for that value. So I go about finding the item like so,
```js
const selectedIndex = findIndex(propEq('value', selectedItem), items);
const selectedItem = items[selectedIndex];
```
That works and I see the select input with the nice label. However once I go about selecting a different option my logic chokes. Since the `selectedValue` is now them 'item', lets say `{ label: 'Skulpturen', value: 'sculptures' }` and that is where I am confused and my above logic does not work. Of course I could go about solve it (check if its an object and if yes just get the label) however that seems awfully verbose and 'complex'.

Maybe I am missing something very obvious or I am just not experienced enough to grok it. Maybe you can enlighten me. Thank you!

**Comment by souporserious** [comment]
[Here's an example](https://codesandbox.io/s/Q0Nxnqn39) I just did that shows how you can build a multi-select. Maybe we need better docs or there can be better naming for these values. @kentcdodds what are your thoughts here?

**Comment by ferdinandsalis** [comment]
So to give your example an initial value you would need to pass the following to your component `defaultValue={[{name: "Aayla Secura", id: "aayla secura"}]}`. Thats fine for this example. But lets say I have the select hooked up to a form and I am getting the values from an api, I will get some kind of string that serves as id for the selected item.

I guess what I could do  —
```js
export const Select = ({
  items = [],
  onChange,
  value: defaultValue,
  placeholder = 'Wähle …',
  getValue = prop('value'),
  name
}) => {
  if (defaultValue) {
    const selectedIndex = findIndex(propEq('value', defaultValue), items);
    defaultValue = items[selectedIndex];
  }
  return (<Downshift
    defaultValue={defaultValue}
    getValue={getValue}
    onChange={compose(onChange, ({ selectedValue }) => getValue(selectedValue))}
  > 
  …
  </Downshift>)
```

**Comment by ferdinandsalis** [comment]
Sorry guys if I am confusing you. Will take another thorough look at my design. I am sure there are some wrong assumptions on my side ☺️

**Comment by kentcdodds** [comment]
Ok, sorry, I'm not sure I'm following everything in this thread, however I'm pretty certain that the best way to determine whether something is selected would be to check some sort of identifier on the object. I don't think there's much more we can reasonably do here...
