### ISSUE TITLE
What can we remove?

### ISSUE THREAD

**Issue by kentcdodds** [paypal/downshift#93]
I think we are getting to a point where we could move/remove things before 1.0.0. Ideas welcome. I think that we might be able to remove `multiple` with the new controlled/uncontrolled capabilities. We may be able to merge `onChange` and `onStateChange`... What else?

**Comment by souporserious** [comment]
I think we can get rid of `onChange` in favor of just `onStateChange` since they are fairly similar. I'm curious why you think `multiple` isn't valid anymore? Do you have an example of what that looks like if we remove it? I was out most of yesterday and missed some of the API additions and how `onStateChange` might help here 😇

**Comment by kentcdodds** [comment]
Could you create a multiple select example in the repo? Then I can see if I can change it to not use multiple an see if we can reasonable remove that. I'm actually almost tempted to remove selectedValue from State and force you to pass that in... That would make it pretty flexible I think...

**Comment by souporserious** [comment]
Is the latest beta released? Trying to create a multiple example on Codesandbox, but it seems I can only get 1.0.0-beta.8 to install 😕

**Comment by kentcdodds** [comment]
It is published. To update you can't click the refresh button on the dependency. You have to add it like you're adding it from the start: `downshift` `beta`

**Comment by souporserious** [comment]
Thanks! 😄  I put together a [small multiple demo](https://codesandbox.io/s/Q0Nxnqn39). Sorry, it's not the best. I'm leaving for two weeks tomorrow on vacation. But I'll be able to help with whatever when I get back 😅

**Comment by kentcdodds** [comment]
Everything will be different when you get back 😈😈😈
Jkjk, have fun!

**Comment by kentcdodds** [comment]
Ok, awesome! So I'm much happier with [this solution that doesn't use `multiple`](https://codesandbox.io/s/W6gyJ30kn) and by removing `multiple` from the implementation that simplifies things considerable :smile:

So :wave: multiple!

**Comment by kentcdodds** [comment]
I think I've removed all I want to remove that this point. We're getting closer!
